//===- TopDialect.h - Topos dialect C++ interface -----------*- C++ -*-===//
//
// Public header of the Topos dialect. Exposes:
//   - mlir::topos::ToposDialect : the dialect class
//   - The types (WorldType, PlaceType, SectionType, ProbeType, CellType, ...)
//   - The operations (generated by TableGen and included here)
//
// Use from C++: include this header to use the Topos dialect in custom MLIR
// passes or in standalone tools.
//
// Use from Rust (yoner-mlir-sys): the C symbols exposed via FFI are declared in
// TopCApi.h, which internally calls these C++ APIs.
//
//===----------------------------------------------------------------------===//

#ifndef TOPOS_DIALECT_H
#define TOPOS_DIALECT_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"

// Include il dialect generato da TableGen.
#include "TopDialect.h.inc"

// Include i tipi generati.
#define GET_TYPEDEF_CLASSES
#include "TopTypes.h.inc"

// Include gli enum generati.
#include "TopEnums.h.inc"

// Include le operations generate.
#define GET_OP_CLASSES
#include "TopOps.h.inc"

#endif // TOPOS_DIALECT_H
