//===- TopDialect.cpp - Topos dialect implementation --------*- C++ -*-===//
//
// Minimal implementation of the Topos dialect: registration of the
// operations, types, and attributes generated by TableGen.
//
// Custom verifier logic goes here when needed (e.g. verifying that an
// operation invoked by topos.op_apply is actually declared in the instance's
// place).
//
//===----------------------------------------------------------------------===//

#include "TopDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/BuiltinAttributeInterfaces.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/FunctionImplementation.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"

using namespace mlir;
using namespace mlir::topos;

// Generates the dialect implementation.
#include "TopDialect.cpp.inc"

void ToposDialect::initialize() {
  // Registra le operations generate.
  addOperations<
#define GET_OP_LIST
#include "TopOps.cpp.inc"
  >();

  // Registra i tipi generati.
  addTypes<
#define GET_TYPEDEF_LIST
#include "TopTypes.cpp.inc"
  >();

  // Note: the Topos dialect attributes are only enums (ReductionDirection,
  // ReductionPolicy, ShotOrdering, HeytingValue); they have no custom AttrDef,
  // so no addAttributes<> is necessary.
}

// Verifier for operation-level attributes (required by
// hasOperationAttrVerify = 1 in the dialect TD).
LogicalResult ToposDialect::verifyOperationAttribute(Operation *op,
                                                       NamedAttribute attr) {
  // For now: no special constraint. Extend when the passes require it (e.g.
  // validate that `policy` is one of the enumerated ReductionPolicy values).
  return success();
}

// Generates the implementation of the operations.
#define GET_OP_CLASSES
#include "TopOps.cpp.inc"

// Generates the implementation of the types.
#define GET_TYPEDEF_CLASSES
#include "TopTypes.cpp.inc"

// Generates the implementation of the enums.
#include "TopEnums.cpp.inc"
