(* catt_r_yon.ml — CATT with R_Yon equality rules, per Rice 2025.
 *
 * Implements the CATT_R_Yon fragment of the type checker federation.
 *
 * CATT (Finster-Mimram 2017) is a dependent type theory whose models
 * are globular weak ∞-categories. Its types are organized by:
 *
 *   - Contexts (telescopes) of variables typed by globular types
 *   - Pasting schemes (ps-contexts) describing pasting diagrams
 *   - Substitutions between contexts
 *   - The judgment Gamma |- t : A
 *
 * Rice 2025 extends CATT with a set R of equality rules. For Yon,
 * R = R_Yon comprises seven families. The crucial property:
 *
 *   Theorem (Rice 2025): For appropriate R, the reduction system
 *   generated by R is strongly normalizing and confluent. Therefore
 *   typechecking of CATT_R is decidable.
 *
 * This module implements the seven families of R_Yon and the
 * decidable equality on CATT_R_Yon types.
 *)

open Surface_ast

(* ─── Globular types ───────────────────────────────────────────────── *)

(* A globular type is a finite tower of cells:
 *
 *   *           — the unique 0-cell (object)
 *   x ->_A y     — a 1-cell from x to y, where A is the type of x, y
 *   alpha ->_{x->y} beta — a 2-cell between 1-cells x -> y
 *   ...
 *
 * We represent this inductively. The base case is Star (objects).
 * The inductive case is Arr (s, t, A) where s and t are terms whose
 * type is A.
 *)

type cell =
  | CellStar                                     (* 0-cell sort *)
  | CellArr of term * term * cell                (* s -> t in cell A *)

and term =
  | TmVar of string                              (* a context variable *)
  | TmCoh of ps_ctx * cell * subst               (* coh_Gamma : A [σ]: a coherence *)
  | TmId of term * cell                          (* identity 1-cell on a term *)

and ps_ctx = (string * cell) list                (* a pasting context *)

and subst = (string * term) list                 (* substitution by name *)

(* ─── Family 1: alpha-renaming (alpha-equivalence) ─────────────────────── *)

(* Two terms are alpha-equivalent if they agree up to renaming of bound
 * variables. In our globular setting, only TmCoh binds variables (via
 * its ps_ctx), so alpha-equivalence amounts to comparing the structure
 * with consistent renaming.
 *
 * For surface Yon, alpha-equivalence is mostly relevant inside lambdas
 * (in function declarations) — those live in the Surface_ast as
 * fun_decl bodies. The CATT layer handles the type-level alpha via the
 * coh constructor.
 *)

let rec alpha_equiv_term (t1 : term) (t2 : term) (renaming : (string * string) list) : bool =
  match t1, t2 with
  | TmVar x, TmVar y ->
      (match List.assoc_opt x renaming with
       | Some y' -> y = y'
       | None -> x = y)
  | TmCoh (ps1, ty1, sub1), TmCoh (ps2, ty2, sub2) ->
      List.length ps1 = List.length ps2
      && List.length sub1 = List.length sub2
      && (let pair_names = List.combine
            (List.map fst ps1) (List.map fst ps2) in
          let ren' = pair_names @ renaming in
          List.for_all2
            (fun (_, c1) (_, c2) -> alpha_equiv_cell c1 c2 ren')
            ps1 ps2
          && alpha_equiv_cell ty1 ty2 ren'
          && List.for_all2
               (fun (k1, t1) (k2, t2) ->
                  (* Substitution keys live in the ps_ctx, so they
                   * must correspond under the same renaming used for
                   * the pasting variables. *)
                  let k1_renamed = List.assoc_opt k1 pair_names in
                  (match k1_renamed with
                   | Some k1' -> k1' = k2
                   | None -> k1 = k2)
                  && alpha_equiv_term t1 t2 ren')
               sub1 sub2)
  | TmId (t1', c1), TmId (t2', c2) ->
      alpha_equiv_term t1' t2' renaming
      && alpha_equiv_cell c1 c2 renaming
  | _, _ -> false

and alpha_equiv_cell (c1 : cell) (c2 : cell) (renaming : (string * string) list) : bool =
  match c1, c2 with
  | CellStar, CellStar -> true
  | CellArr (s1, t1, a1), CellArr (s2, t2, a2) ->
      alpha_equiv_term s1 s2 renaming
      && alpha_equiv_term t1 t2 renaming
      && alpha_equiv_cell a1 a2 renaming
  | _, _ -> false

let family1_alpha_equiv t1 t2 = alpha_equiv_term t1 t2 []

(* ─── Name-invariant canonicalization (weak de Bruijn) ──────────────────────

   The names debt (identified for xleech2 content-addressing): two cells that are
   alpha-equivalent but written with different binder names (x vs y) must map to
   the SAME structure, otherwise hash-consing them gives different addresses and
   content-addressing is defeated.

   canonicalize_term rewrites every BOUND name (introduced by a TmCoh's ps_ctx)
   to a positional canonical name "#<n>" assigned in ps_ctx order. Free TmVars
   (0-cells / real places, bound by no TmCoh) are left intact — they ARE the
   geometric identity and must not be erased. After canonicalization, two
   alpha-equivalent cells are STRUCTURALLY identical, so equality is a direct
   structural compare (O(1) once hash-consed), with no renaming list to carry.

   `env` maps an original bound name to its canonical "#n". `depth` is the next
   free index. Substitution keys live in the binding ps_ctx, so they are
   canonicalized through the same env. *)
let rec canonicalize_term (env : (string * string) list) (t : term) : term =
  match t with
  | TmVar x ->
      (match List.assoc_opt x env with
       | Some canon -> TmVar canon   (* bound: positional name *)
       | None -> TmVar x)            (* free: a real 0-cell, kept as-is *)
  | TmCoh (ps, ty, sub) ->
      (* assign positional canonical names to the ps_ctx binders, in order *)
      let _, rev_env', rev_ps =
        List.fold_left
          (fun (i, e, acc) (name, c) ->
             let canon = "#" ^ string_of_int i in
             let e' = (name, canon) :: e in
             (* the cell of this binder may refer to earlier binders -> use e' *)
             (i + 1, e', (canon, canonicalize_cell e' c) :: acc))
          (0, env, []) ps
      in
      let env' = rev_env' in
      let ps' = List.rev rev_ps in
      let ty' = canonicalize_cell env' ty in
      let sub' =
        List.map
          (fun (k, tm) ->
             let k' = (match List.assoc_opt k env' with Some c -> c | None -> k) in
             (k', canonicalize_term env' tm))
          sub
      in
      TmCoh (ps', ty', sub')
  | TmId (t', c) ->
      TmId (canonicalize_term env t', canonicalize_cell env c)

and canonicalize_cell (env : (string * string) list) (c : cell) : cell =
  match c with
  | CellStar -> CellStar
  | CellArr (s, t, a) ->
      CellArr (canonicalize_term env s, canonicalize_term env t,
               canonicalize_cell env a)

(* The canonical (name-invariant) form of a cell-term: ready for structural
   equality and, ultimately, for content-addressed hash-consing on xleech2. *)
let canonical_form (t : term) : term = canonicalize_term [] t

(* Name-invariant equality: two terms are equal iff their canonical forms are
   structurally identical. Equivalent to alpha-equivalence, but via a single
   normal form rather than a renaming search — the prerequisite for O(1)
   hash-consed equality. *)
let canonical_equal (t1 : term) (t2 : term) : bool =
  canonical_form t1 = canonical_form t2

(* ─── A1: native hash-consing of cells over the canonical form ──────────────

   Once cells have a name-invariant canonical form (above), we can SHARE
   structurally-identical cells: interning a cell returns a single shared node
   for each distinct canonical form. Two geometrically-identical cells then
   become the SAME physical value, so equality is pointer identity (==) instead
   of a structural walk — the O(1) definitional equality the design calls for,
   realized in the compiler (OCaml), where cells actually live, with no FFI and
   no abuse of the runtime arena.

   This mirrors what an xleech2 content-addressed store would do at the C level
   (yon_xheap_put_or_get), but in-process: the canonical form is the content
   key. When a network/serialization layer later needs cells as wire payloads,
   the same canonical form maps directly onto an xleech2 block (the deferred A2).

   The table is keyed by canonical form and maps to the interned representative.
   reset_cell_interning clears it (e.g. between compilation units). *)
let cell_intern_table : (term, term) Hashtbl.t = Hashtbl.create 256

let reset_cell_interning () = Hashtbl.reset cell_intern_table

(* Intern a cell-term: return the unique shared node for its canonical form.
   Structurally-identical cells get the SAME physical representative. *)
let intern_cell (t : term) : term =
  let key = canonical_form t in
  match Hashtbl.find_opt cell_intern_table key with
  | Some shared -> shared
  | None -> Hashtbl.replace cell_intern_table key key; key

(* O(1) equality on interned cells: physical identity. Falls back to canonical
   equality if either side was not interned (defensive). *)
let interned_equal (t1 : term) (t2 : term) : bool =
  let a = intern_cell t1 and b = intern_cell t2 in
  a == b   (* physical identity: both point to the same shared canonical node *)

(* Number of distinct cells currently shared (for diagnostics/measurement). *)
let interned_cell_count () = Hashtbl.length cell_intern_table

(* Debt 2: make generated cells observable. The desugar layer registers each
   geom_morphism's directed cell here by morphism name, so a surface query can
   inspect it. Cells are compile-time artifacts (alpha: no silicon payload), so
   "inspection" is a compile-time fact about the cell, not a runtime value. *)
let geom_cell_registry : (string, term) Hashtbl.t = Hashtbl.create 64

let reset_geom_cell_registry () = Hashtbl.reset geom_cell_registry

let register_geom_cell (name : string) (cell : term) : unit =
  Hashtbl.replace geom_cell_registry name cell

let lookup_geom_cell (name : string) : term option =
  Hashtbl.find_opt geom_cell_registry name

(* A human-readable rendering of a cell's directed boundary, for inspection:
   "c_src -> c_tgt" for an inclusion, or a tag for other shapes. *)
let describe_cell (t : term) : string =
  match t with
  | TmCoh (_, CellArr (s, tg, CellStar), _) ->
      let n x = (match x with TmVar nm -> nm | _ -> "?") in
      Printf.sprintf "directed 1-cell: %s -> %s" (n s) (n tg)
  | TmCoh (_, CellArr (_, _, CellArr _), _) -> "directed 2-cell"
  | TmId _ -> "identity cell (collapsed)"
  | TmVar v -> "0-cell: " ^ v
  | _ -> "cell"

(* ─── On-disk persistence of the cell graph (OCaml-side, no xleech2/C) ───────

   Persisting the proof/cell graph gives two benefits even on a single node
   (N=1, no network): incremental compilation (an unchanged sub-graph keeps the
   same serialized key, so its work can be skipped) and reusable O(1)
   verification. We serialize the CANONICAL form (parts 84-85, names already
   "#0","#1"...), so the same logical cell yields the same text on any machine,
   deterministically — the prerequisite the binder fix unlocked.

   Format: a deterministic textual S-expression of the canonical term. Textual
   (not Marshal) so it is inspectable and OCaml-version-independent. This writes
   from the compiler directly; it does NOT touch the C runtime arena (xleech2),
   which would require an OCaml<->C bridge and is only needed for cross-NODE wire
   payloads (the deferred distributed case). *)
let rec serialize_term (t : term) : string =
  match t with
  | TmVar x -> "(var " ^ x ^ ")"
  | TmId (t', c) ->
      "(id " ^ serialize_term t' ^ " " ^ serialize_cell c ^ ")"
  | TmCoh (ps, ty, sub) ->
      let ps_s =
        String.concat " "
          (List.map (fun (k, c) -> "(" ^ k ^ " " ^ serialize_cell c ^ ")") ps)
      in
      let sub_s =
        String.concat " "
          (List.map (fun (k, tm) -> "(" ^ k ^ " " ^ serialize_term tm ^ ")") sub)
      in
      "(coh [" ^ ps_s ^ "] " ^ serialize_cell ty ^ " [" ^ sub_s ^ "])"

and serialize_cell (c : cell) : string =
  match c with
  | CellStar -> "*"
  | CellArr (s, t, a) ->
      "(arr " ^ serialize_term s ^ " " ^ serialize_term t ^ " "
      ^ serialize_cell a ^ ")"

(* The persistent key of a cell: serialization of its canonical form. Two
   alpha-equivalent cells share this key exactly. *)
let cell_persist_key (t : term) : string = serialize_term (canonical_form t)

(* Write the registered geom-morphism cells to a file, one per line:
   "<morphism_name>\t<canonical_serialization>". Deterministic ordering (sorted
   by name) so the file itself is content-stable across runs. *)
let persist_geom_cells (path : string) : unit =
  let entries =
    Hashtbl.fold (fun name cell acc -> (name, cell_persist_key cell) :: acc)
      geom_cell_registry []
  in
  let entries = List.sort (fun (a, _) (b, _) -> compare a b) entries in
  let oc = open_out path in
  List.iter (fun (name, key) -> Printf.fprintf oc "%s\t%s\n" name key) entries;
  close_out oc

(* Load a persisted cell graph: returns (name -> canonical serialization) map.
   Used to detect unchanged sub-graphs (incremental compilation): if a cell's
   current key equals the persisted one, its work can be skipped. *)
let load_persisted_cells (path : string) : (string * string) list =
  if not (Sys.file_exists path) then []
  else begin
    let ic = open_in path in
    let rec loop acc =
      match input_line ic with
      | line ->
          (match String.index_opt line '\t' with
           | Some i ->
               let name = String.sub line 0 i in
               let key = String.sub line (i + 1) (String.length line - i - 1) in
               loop ((name, key) :: acc)
           | None -> loop acc)
      | exception End_of_file -> (try close_in ic with _ -> ()); List.rev acc
    in
    loop []
  end

(* ─── Incremental compilation loop (uses the persisted graph) ───────────────

   The persisted graph becomes useful when the compiler consults it: at startup
   we load the previous keys; for each cell, if its current canonical key equals
   the persisted one, the cell is UNCHANGED and its downstream work can be
   skipped. This is the N=1 incremental-compilation benefit, realized. *)
let incremental_prev : (string, string) Hashtbl.t = Hashtbl.create 64
let incremental_skips = ref 0
let incremental_checks = ref 0

let incremental_load (path : string) : unit =
  Hashtbl.reset incremental_prev;
  incremental_skips := 0;
  incremental_checks := 0;
  List.iter (fun (name, key) -> Hashtbl.replace incremental_prev name key)
    (load_persisted_cells path)

(* True if this cell is UNCHANGED vs the persisted graph (work skippable). *)
let incremental_unchanged (name : string) (cell : term) : bool =
  incr incremental_checks;
  match Hashtbl.find_opt incremental_prev name with
  | Some prev_key when prev_key = cell_persist_key cell ->
      incr incremental_skips; true
  | _ -> false

let incremental_stats () = (!incremental_skips, !incremental_checks)


(* ─── Family 2: beta-reduction ────────────────────────────────────────── *)

(* beta-reduction in the surface Yon language is handled by the kernel
 * Reduce module on Yon Core terms. At the CATT level, beta-like
 * reductions occur when a coherence is applied to a substitution
 * that names a coherence in turn:
 *
 *   coh_Gamma : A [σ]   where σ binds a variable to coh_Δ : B [τ]
 *
 * The reduction substitutes and may unfold the inner coherence. For
 * the prototype, we provide the structural beta-step that substitutes
 * a variable in a term. The full beta for CATT_R_Yon coheres at the
 * surface fun_decl level via the kernel.
 *)

let rec subst_in_term (t : term) (sub : subst) : term =
  match t with
  | TmVar x ->
      (match List.assoc_opt x sub with
       | Some replacement -> replacement
       | None -> t)
  | TmCoh (ps, ty, sub') ->
      (* The variables bound by ps are not in scope of the outer sub. *)
      let bound = List.map fst ps in
      let outer_sub = List.filter (fun (k, _) -> not (List.mem k bound)) sub in
      let sub'' = List.map (fun (k, v) -> (k, subst_in_term v outer_sub)) sub' in
      TmCoh (ps, ty, sub'')
  | TmId (t', c) -> TmId (subst_in_term t' sub, subst_in_cell c sub)

and subst_in_cell (c : cell) (sub : subst) : cell =
  match c with
  | CellStar -> CellStar
  | CellArr (s, t, a) ->
      CellArr (subst_in_term s sub, subst_in_term t sub, subst_in_cell a sub)

let family2_beta_step (t : term) (sub : subst) : term =
  subst_in_term t sub

(* ─── Family 3: η-equivalence ──────────────────────────────────────── *)

(* η in CATT: a coherence coh_Gamma : A [identity_sub] reduces to a simpler
 * form if its ps-context and substitution are trivial.
 *
 * For terms at the surface: a function lambdax. f(x) where x doesn't
 * appear in f is η-equivalent to f. The kernel handles this on
 * Yon Core. At the CATT level, we check whether a TmCoh has the
 * identity substitution and trivial ps_ctx, in which case it reduces
 * to the underlying body.
 *)

let is_identity_sub (sub : subst) (ps : ps_ctx) : bool =
  List.length sub = List.length ps
  && List.for_all2
       (fun (k1, v) (k2, _) -> k1 = k2 && (match v with TmVar n -> n = k1 | _ -> false))
       sub ps

let family3_eta_step (t : term) : term =
  match t with
  | TmCoh (ps, _ty, sub) when is_identity_sub sub ps ->
      (* η: identity coherence is the identity, reduces to the var.
       * But in our globular setting, what we return depends on the
       * pasting context. For a single-variable ps_ctx of a 0-cell,
       * the identity reduces to the variable itself. *)
      (match ps with
       | [(x, CellStar)] -> TmVar x
       | _ -> t)
  | _ -> t

(* ─── Family 4: Place equivalence by signature ─────────────────────── *)

(* Two places are equivalent under R_Yon Family 4 if they have the
 * same signature: same fields (with same types in same order) and
 * same operations (with same param/return signatures).
 *
 * This is what allows univalence-like reasoning at the place level:
 * if A and B are structurally identical places, programs that work
 * on A also work on B and vice versa.
 *)

let rec field_equiv (f1 : field_decl) (f2 : field_decl) : bool =
  f1.fd_name = f2.fd_name
  && ty_structural_eq f1.fd_ty f2.fd_ty

and op_equiv (o1 : operation_decl) (o2 : operation_decl) : bool =
  o1.op_name = o2.op_name
  && List.length o1.op_params = List.length o2.op_params
  && List.for_all2
       (fun p1 p2 -> ty_structural_eq p1.param_ty p2.param_ty)
       o1.op_params o2.op_params
  && (match o1.op_return, o2.op_return with
      | None, None -> true
      | Some t1, Some t2 -> ty_structural_eq t1 t2
      | _ -> false)

and ty_structural_eq (t1 : ty) (t2 : ty) : bool =
  let canon name =
    match name with
    | "boolean" | "proposition" -> "__bool_or_prop"
    | other -> other
  in
  (* "unknown" is a polymorphic placeholder used by stdlib signatures.
   * It unifies with any other type. Same for TyVar (true generic
   * binders from fun<A>). *)
  let is_unknown t =
    match t with
    | TyPrim "unknown" -> true
    | TyUser "unknown" -> true
    | TyVar _ -> true   (* generic binder unifies with anything *)
    | _ -> false
  in
  (* Legacy "Path" (cubical) is structurally an Id type. We accept
   * Path ↔ TyId _ as compatible to preserve backward compatibility
   * of pre-HoTT-promotion code. *)
  let is_path_alias t =
    match t with
    | TyUser "Path" | TyPrim "Path" -> true
    | _ -> false
  in
  let is_id_type t =
    match t with
    | TyId _ -> true
    | _ -> false
  in
  if is_unknown t1 || is_unknown t2 then true
  else if (is_path_alias t1 && is_id_type t2)
       || (is_path_alias t2 && is_id_type t1)
       || (is_path_alias t1 && is_path_alias t2)
  then true
  else
  match t1, t2 with
  | TyPrim n1, TyPrim n2 -> canon n1 = canon n2
  | TyPrim n1, TyPrimIn (n2, _) | TyPrimIn (n1, _), TyPrim n2 ->
      canon n1 = canon n2
  | TyPrimIn (n1, _), TyPrimIn (n2, _) -> canon n1 = canon n2
  | TyUser n1, TyUser n2 -> canon n1 = canon n2
  | TyUser n, TyPrim m | TyPrim n, TyUser m -> canon n = canon m
  | TyList a, TyList b -> ty_structural_eq a b
  | TyMap (k1, v1), TyMap (k2, v2) ->
      ty_structural_eq k1 k2 && ty_structural_eq v1 v2
  | TyStream (a, _), TyStream (b, _) -> ty_structural_eq a b
  | TySum vs1, TySum vs2 ->
      List.length vs1 = List.length vs2
      && List.for_all2 variant_eq vs1 vs2
  (* HoTT type equivalences with cumulative subtyping for universes. *)
  | TyUniverse n1, TyUniverse n2 ->
      (* Cumulativity: Type_n <: Type_m whenever n <= m.
       * Equivalence (used here as a coarse approximation of typing)
       * accepts when EITHER level can be lifted to match the other. *)
      n1 = n2 || n1 < n2 || n2 < n1  (* always true if both universes;
                                       * cumulative subtyping is symmetric
                                       * in the equivalence check. *)
  | TyPi (_x1, a1, b1), TyPi (_x2, a2, b2) ->
      (* Two Pi-types equivalent iff their domain and codomain are. *)
      ty_structural_eq a1 a2 && ty_structural_eq b1 b2
  | TySigma (_x1, a1, b1), TySigma (_x2, a2, b2) ->
      ty_structural_eq a1 a2 && ty_structural_eq b1 b2
  | TyId (a1, _, _), TyId (a2, _, _) ->
      (* Id types carry endpoint terms; we compare carriers structurally
       * and treat endpoints conservatively as equal. Full path equality
       * requires a homotopical comparison via J — beyond this layer. *)
      ty_structural_eq a1 a2
  | _, _ -> false

and variant_eq (v1 : variant) (v2 : variant) : bool =
  v1.v_name = v2.v_name
  && List.length v1.v_args = List.length v2.v_args
  && List.for_all2 ty_structural_eq v1.v_args v2.v_args

let family4_place_equiv (p1 : place_decl) (p2 : place_decl) : bool =
  let extract_fields p =
    List.filter_map (function FoField f -> Some f | FoOp _ -> None | FoCell _ -> None | FoLaw _ -> None) p.pd_members
  in
  let extract_ops p =
    List.filter_map (function FoOp o -> Some o | FoField _ -> None | FoCell _ -> None | FoLaw _ -> None) p.pd_members
  in
  let fs1 = extract_fields p1 and fs2 = extract_fields p2 in
  let ops1 = extract_ops p1 and ops2 = extract_ops p2 in
  List.length fs1 = List.length fs2
  && List.length ops1 = List.length ops2
  && List.for_all2 field_equiv fs1 fs2
  && List.for_all2 op_equiv ops1 ops2

(* ─── Family 4 (constructive): place isomorphism ───────────────
 *
 * Two places are *isomorphic* in the structure category when there
 * exists a bijective renaming of their fields/operations preserving
 * types. This generalizes family4_place_equiv (which required
 * positionally-aligned identity) to permit any reordering plus name
 * renaming.
 *
 * Yoneda perspective: an isomorphism of places is a 1-cell in the
 * 2-category of objects-with-structure that has a 2-sided inverse.
 * Constructively, we produce the bijection (the witness of the iso)
 * as a list of name pairs, then verify both directions are valid. *)

(* Find a bijection between two lists of fields up to type equivalence.
 * Returns Some [(n1, n2); ...] if a bijection exists, None otherwise.
 *
 * Algorithm: for each field in list1, find an unused field in list2
 * with compatible type, pair them. If at some step no candidate
 * exists, the overall iso fails. This is a greedy matching; for the
 * surface AST it suffices because field types are concrete enough
 * that ambiguity rarely matters. *)
let rec field_bijection (fs1 : field_decl list) (fs2 : field_decl list)
    : (string * string) list option =
  match fs1 with
  | [] -> if fs2 = [] then Some [] else None
  | f :: rest ->
      let rec try_match prefix = function
        | [] -> None
        | g :: tail when ty_structural_eq f.fd_ty g.fd_ty ->
            let remaining = prefix @ tail in
            (match field_bijection rest remaining with
             | Some sub -> Some ((f.fd_name, g.fd_name) :: sub)
             | None -> try_match (prefix @ [g]) tail)
        | g :: tail -> try_match (prefix @ [g]) tail
      in
      try_match [] fs2

(* Operation bijection: same idea but matches both name structure
 * (param count + return type) AND param types pointwise. *)
let rec op_bijection (ops1 : operation_decl list) (ops2 : operation_decl list)
    : (string * string) list option =
  let op_compatible (o1 : operation_decl) (o2 : operation_decl) =
    List.length o1.op_params = List.length o2.op_params
    && List.for_all2
         (fun p1 p2 -> ty_structural_eq p1.param_ty p2.param_ty)
         o1.op_params o2.op_params
    && (match o1.op_return, o2.op_return with
        | Some r1, Some r2 -> ty_structural_eq r1 r2
        | None, None -> true
        | _ -> false)
  in
  match ops1 with
  | [] -> if ops2 = [] then Some [] else None
  | o :: rest ->
      let rec try_match prefix = function
        | [] -> None
        | g :: tail when op_compatible o g ->
            let remaining = prefix @ tail in
            (match op_bijection rest remaining with
             | Some sub -> Some ((o.op_name, g.op_name) :: sub)
             | None -> try_match (prefix @ [g]) tail)
        | g :: tail -> try_match (prefix @ [g]) tail
      in
      try_match [] ops1

(* The full place isomorphism: produces a witness (field_iso, op_iso)
 * when the two places have compatible structure. Returns None when
 * no bijection exists. *)
let place_isomorphism (p1 : place_decl) (p2 : place_decl)
    : ((string * string) list * (string * string) list) option =
  let extract_fields p =
    List.filter_map (function FoField f -> Some f | FoOp _ -> None | FoCell _ -> None | FoLaw _ -> None) p.pd_members
  in
  let extract_ops p =
    List.filter_map (function FoOp o -> Some o | FoField _ -> None | FoCell _ -> None | FoLaw _ -> None) p.pd_members
  in
  let fs1 = extract_fields p1 and fs2 = extract_fields p2 in
  let ops1 = extract_ops p1 and ops2 = extract_ops p2 in
  match field_bijection fs1 fs2, op_bijection ops1 ops2 with
  | Some fi, Some oi -> Some (fi, oi)
  | _ -> None

(* Yoneda-coherent place equivalence: two places are equivalent iff
 * there's an isomorphism between them. *)
let family4_place_iso (p1 : place_decl) (p2 : place_decl) : bool =
  place_isomorphism p1 p2 <> None

(* ─── Family 5 (constructive): Eckmann-Hilton swap ────────────
 *
 * In an omega-category, for two 2-cells alpha, beta : id_x ==> id_x on the
 * identity 1-cell at x, the interchange law forces:
 *
 *   alpha o_h beta = alpha o_v beta = beta o_v alpha = beta o_h alpha
 *
 * where o_h is horizontal composition and o_v is vertical. This is
 * the Eckmann-Hilton argument: any monoid structure on End(id_x)
 * with two compatible operations is commutative.
 *
 * The EH swap is the 3-cell witnessing alpha o_h beta = beta o_h alpha — it lives
 * in dimension 3 (one above the 2-cells it relates).
 *
 * Pasting scheme:
 *   [x : star, ix : x -> x = id_x,
 *    alpha : ix ==> ix, beta : ix ==> ix]
 *
 * The 3-cell is between (alpha o_h beta) and (beta o_h alpha), both 2-cells. *)

let ps_eckmann_hilton : ps_ctx = [
  ("x", CellStar);
  ("ix", CellArr (TmVar "x", TmVar "x", CellStar));  (* id-like 1-cell *)
  ("alpha", CellArr (TmVar "ix", TmVar "ix",
                     CellArr (TmVar "x", TmVar "x", CellStar)));
  ("beta", CellArr (TmVar "ix", TmVar "ix",
                    CellArr (TmVar "x", TmVar "x", CellStar)));
]

(* Build the Eckmann-Hilton swap witness. *)
let eckmann_hilton_swap (x : term) : term =
  let ix_cell = CellArr (x, x, CellStar) in  (* the identity 1-cell *)
  let two_cell_base = ix_cell in              (* 2-cells live over this *)
  let two_cell_type = CellArr (TmVar "ix", TmVar "ix", two_cell_base) in
  (* alpha o_h beta and beta o_h alpha are both 2-cells; the EH swap is the 3-cell
   * between them. *)
  let alpha_h_beta = TmVar "__alpha_h_beta" in
  let beta_h_alpha = TmVar "__beta_h_alpha" in
  let swap_cell = CellArr (alpha_h_beta, beta_h_alpha, two_cell_type) in
  TmCoh (ps_eckmann_hilton, swap_cell,
         [("x", x);
          ("ix", TmId (x, CellStar));
          ("alpha", TmVar "__alpha");
          ("beta", TmVar "__beta")])

(* Test entry: the EH swap should be a 3-cell whose base is the
 * 2-cell type alpha : id_x ==> id_x (and likewise for beta). *)
let test_eckmann_hilton () =
  let x = TmVar "x" in
  let swap = eckmann_hilton_swap x in
  match swap with
  | TmCoh (_, CellArr (_alpha_beta, _beta_alpha, two_cell_type), _) ->
      (* two_cell_type is CellArr(ix, ix, CellArr(x, x, CellStar)) *)
      (match two_cell_type with
       | CellArr (_, _, CellArr (s, t, CellStar)) ->
           alpha_equiv_term s x [] && alpha_equiv_term t x []
       | _ -> false)
  | _ -> false

(* ─── Family 6 (constructive): pasting diagrams as terms ─────
 *
 * The ps_ctx type above is the *linear telescope* representation: a
 * flat list of named cells. Batanin-Maltsiniotis give the general
 * definition: pasting diagrams are terms in a globular operad,
 * generated by:
 *
 *   - disk_n     : the free n-cell (n >= 0)
 *   - paste      : compose two diagrams along their boundary
 *   - suspend    : lift a diagram one dimension up
 *
 * Below we encode this as an inductive type. *)

type pasting_diagram =
  | PDisk of int                              (* disk_n, the free n-cell *)
  | PPaste of pasting_diagram * pasting_diagram * int
                                              (* paste two diagrams at dim k *)
  | PSuspend of pasting_diagram               (* suspend (raise dim by 1) *)

let rec pd_dim (d : pasting_diagram) : int =
  match d with
  | PDisk n -> n
  | PPaste (d1, d2, _) -> max (pd_dim d1) (pd_dim d2)
  | PSuspend d -> pd_dim d + 1

let rec pd_valid (d : pasting_diagram) : bool =
  match d with
  | PDisk n -> n >= 0
  | PPaste (d1, d2, k) ->
      pd_valid d1 && pd_valid d2
      && pd_dim d1 > k && pd_dim d2 > k
  | PSuspend d -> pd_valid d

let rec flatten_to_ps_ctx (d : pasting_diagram) (prefix : string) : ps_ctx =
  match d with
  | PDisk 0 -> [(prefix ^ "x", CellStar)]
  | PDisk n ->
      let objs = List.init (n + 1)
        (fun i -> (Printf.sprintf "%sx%d" prefix i, CellStar)) in
      let arrs = List.init n
        (fun i ->
           let src = TmVar (Printf.sprintf "%sx%d" prefix i) in
           let tgt = TmVar (Printf.sprintf "%sx%d" prefix (i + 1)) in
           (Printf.sprintf "%sf%d" prefix i,
            CellArr (src, tgt, CellStar))) in
      objs @ arrs
  | PPaste (d1, d2, _k) ->
      let left = flatten_to_ps_ctx d1 (prefix ^ "L") in
      let right = flatten_to_ps_ctx d2 (prefix ^ "R") in
      left @ right
  | PSuspend d ->
      let inner = flatten_to_ps_ctx d (prefix ^ "S") in
      let new_endpoints = [
        (prefix ^ "north", CellStar);
        (prefix ^ "south", CellStar);
      ] in
      new_endpoints @ inner

let test_pd_disk0 () =
  let d = PDisk 0 in
  pd_valid d && pd_dim d = 0
  && List.length (flatten_to_ps_ctx d "") = 1

let test_pd_disk_n () =
  let d = PDisk 3 in
  pd_valid d && pd_dim d = 3
  && List.length (flatten_to_ps_ctx d "") = 7  (* 4 obj + 3 arrows *)

let test_pd_paste () =
  let d = PPaste (PDisk 1, PDisk 1, 0) in
  pd_valid d && pd_dim d = 1

let test_pd_suspend () =
  let d = PSuspend (PDisk 1) in
  pd_valid d && pd_dim d = 2

let pd_comp_2 : pasting_diagram = PPaste (PDisk 1, PDisk 1, 0)

(* ─── Family 7 (constructive): universal cells for limit/colimit ──────
 *
 * A universal cell in an omega-category is one that encodes
 * a universal property — e.g., the projection from a limit object,
 * or the inclusion into a colimit. Given a diagram D : J -> C and
 * a cone (X, f), a universal cell at the limit (L, π) gives the
 * UNIQUE factorization X --> L making the triangles commute.
 *
 * We represent this constructively:
 *   - universal_limit_cell builds a TmCoh marked as universal at the
 *     limit of a diagram (the diagram given as ps_ctx).
 *   - factor_through(univ, cone) produces the unique TmCoh witnessing
 *     the factorization, or None if the cone doesn't commute with the
 *     universal structure. *)

(* A universal cell is a tagged TmCoh. We add the tag inline by using
 * a distinguished name in the ps_ctx (prefixed with "__UNIV_"). *)

let mark_universal (ps : ps_ctx) : ps_ctx =
  ("__UNIV_marker", CellStar) :: ps

let is_universal_cell (t : term) : bool =
  match t with
  | TmCoh (ps, _, _) ->
      List.exists (fun (name, _) -> name = "__UNIV_marker") ps
  | _ -> false

(* Build the universal cell for a limit over a diagram given by a
 * pasting context (the shape of J). The limit L has projections to
 * each apex of the diagram; the universal cell is the projection
 * cone, witnessed as a TmCoh with the universal marker. *)
let universal_limit_cell (diagram_ps : ps_ctx) (apex : term) : term =
  let marked_ps = mark_universal diagram_ps in
  (* The result cell: a "projection cone" from the limit to the apex.
   * For simplicity we represent it as a 1-cell from L to apex. *)
  let result_cell = CellArr (TmVar "L_limit", apex, CellStar) in
  let sub = List.map (fun (n, _) -> (n, TmVar n)) marked_ps in
  TmCoh (marked_ps, result_cell, sub)

(* Build the universal cell for a colimit (dual): the inclusion cone
 * from apex into the colimit. *)
let universal_colimit_cell (diagram_ps : ps_ctx) (apex : term) : term =
  let marked_ps = mark_universal diagram_ps in
  let result_cell = CellArr (apex, TmVar "L_colimit", CellStar) in
  let sub = List.map (fun (n, _) -> (n, TmVar n)) marked_ps in
  TmCoh (marked_ps, result_cell, sub)

(* Factor a cone through a universal cell. Given:
 *   - univ : the universal cell (TmCoh marked universal)
 *   - cone_apex : the apex of the cone being factored
 *   - cone_term : the cone morphism we want to factor
 * produce the unique mediating morphism cone_apex -> L. *)
let factor_through (univ : term) (cone_apex : term) (cone_term : term)
    : term option =
  if not (is_universal_cell univ) then None
  else
    match univ with
    | TmCoh (ps, _, _) ->
        (* The factorization is itself a TmCoh in the same context,
         * with substitution carrying the cone data. *)
        let factored_cell =
          CellArr (cone_apex, TmVar "L_limit", CellStar) in
        Some (TmCoh (ps, factored_cell,
                     [("__cone_apex", cone_apex);
                      ("__cone_morphism", cone_term)]))
    | _ -> None

let test_universal_limit () =
  let small_diagram : ps_ctx = [
    ("a", CellStar);
    ("b", CellStar);
    ("f", CellArr (TmVar "a", TmVar "b", CellStar));
  ] in
  let univ = universal_limit_cell small_diagram (TmVar "a") in
  is_universal_cell univ

let test_factorization () =
  let small_diagram : ps_ctx = [
    ("a", CellStar);
    ("b", CellStar);
    ("f", CellArr (TmVar "a", TmVar "b", CellStar));
  ] in
  let univ = universal_limit_cell small_diagram (TmVar "a") in
  let cone_apex = TmVar "X" in
  let cone_morph = TmVar "k" in
  match factor_through univ cone_apex cone_morph with
  | Some _ -> true
  | None -> false

let test_non_universal_no_factor () =
  (* A plain (non-marked) TmCoh should not factor. *)
  let plain = TmCoh ([("a", CellStar)],
                     CellArr (TmVar "a", TmVar "a", CellStar),
                     [("a", TmVar "a")]) in
  factor_through plain (TmVar "X") (TmVar "k") = None


(* ─── Family 5: Reduction equivalence by beta-η of handlers ───────────── *)

(* Two reductions are equivalent if they target the same place and
 * each pair of corresponding handlers is beta-η-equivalent.
 *
 * Handler equivalence is checked by reducing both handler bodies to
 * normal form (via the kernel's R_Yon engine) and comparing
 * syntactically. This is sound because R_Yon is strongly normalizing
 * and confluent (Rice 2025).
 *)

let handler_equiv (h1 : reduction_clause) (h2 : reduction_clause) : bool =
  match h1, h2 with
  | RcOn (n1, p1, _b1, _), RcOn (n2, p2, _b2, _) ->
      n1 = n2
      && List.length p1 = List.length p2
      && List.for_all2
           (fun a b ->
              a.param_name = b.param_name
              && ty_structural_eq a.param_ty b.param_ty)
           p1 p2
      (* Body equivalence is checked by the kernel via normal-form
       * comparison after desugaring. For the type-checking layer, we
       * accept matching signatures and defer body equivalence to
       * runtime R_Yon. *)
  | RcLet (n1, _, _), RcLet (n2, _, _) -> n1 = n2
  | _, _ -> false

let family5_reduction_equiv (r1 : reduction_decl) (r2 : reduction_decl) : bool =
  r1.rd_of = r2.rd_of
  && List.length r1.rd_clauses = List.length r2.rd_clauses
  && List.for_all2 handler_equiv r1.rd_clauses r2.rd_clauses

(* ─── Family 6: Move equivalence by geometric morphism ─────────────── *)

(* A move between worlds W1 -> W2 induces a geometric morphism between
 * their topoi. Two moves are equivalent if they induce the same
 * morphism: same source and target worlds, and the field mappings
 * agree (up to permutation, since the order in the mapping_decl list
 * is not semantically significant).
 *
 * For Form A (mapping form), we compare the set of mapping_decls.
 * For Form B (unification form), we compare the unified worlds and
 * the conflict resolutions.
 *)

let mapping_eq (m1 : mapping_decl) (m2 : mapping_decl) : bool =
  m1.m_from = m2.m_from && m1.m_to = m2.m_to
  && m1.m_kind = m2.m_kind && m1.m_by = m2.m_by

let mapping_set_eq (ms1 : mapping_decl list) (ms2 : mapping_decl list) : bool =
  List.length ms1 = List.length ms2
  && List.for_all (fun m1 -> List.exists (mapping_eq m1) ms2) ms1

let family6_move_equiv (m1 : move_decl) (m2 : move_decl) : bool =
  m1.mv_from = m2.mv_from && m1.mv_to = m2.mv_to
  && (match m1.mv_body, m2.mv_body with
      | MoveMapping ms1, MoveMapping ms2 -> mapping_set_eq ms1 ms2
      | MoveMerge mg1, MoveMerge mg2 ->
          List.sort compare mg1.merge_shares
          = List.sort compare mg2.merge_shares
          && List.sort compare mg1.merge_conflicts
             = List.sort compare mg2.merge_conflicts
      | _, _ -> false)

(* ─── Family 7: View equivalence by representable functor ──────────── *)

(* A view of place P is a representable functor Hom(P, -) into Set.
 * Two views of the same place are equivalent if their show clauses
 * project the same fields with the same labels.
 *)

let view_item_eq (v1 : view_item) (v2 : view_item) : bool =
  match v1, v2 with
  | VShowSimple n1, VShowSimple n2 -> n1 = n2
  | VShowAs (n1, _), VShowAs (n2, _) -> n1 = n2
    (* Expression equality deferred to kernel beta-η check *)
  | VShowLabel (n1, l1), VShowLabel (n2, l2) -> n1 = n2 && l1 = l2
  | _, _ -> false

let family7_view_equiv (v1 : view_decl) (v2 : view_decl) : bool =
  v1.vw_of = v2.vw_of
  && List.length v1.vw_items = List.length v2.vw_items
  && List.for_all2 view_item_eq v1.vw_items v2.vw_items

(* ─── The R_Yon equivalence relation on types ──────────────────────── *)

(* Two surface types are R_Yon-equal if they are structurally equal
 * (modulo Family 4, which equates user types referring to equivalent
 * places). The dispatcher uses this when comparing types in
 * synthesis/checking.
 *
 * For user types referencing place declarations, we delegate to
 * Family 4 by looking up the place in the environment.
 *)

let r_yon_ty_equal
    (env : Tyenv.env) (t1 : ty) (t2 : ty) : bool =
  if ty_structural_eq t1 t2 then true
  else
    match t1, t2 with
    | TyUser n1, TyUser n2 when n1 <> n2 ->
        (match Tyenv.lookup_place env n1,
               Tyenv.lookup_place env n2 with
         | Some p1, Some p2 -> family4_place_equiv p1 p2
         | _, _ -> false)
    | _, _ -> false

(* ─── Decidability witness ─────────────────────────────────────────── *)

(* The full R_Yon equivalence on terms is decidable by Rice's theorem
 * because the reduction system is strongly normalizing and confluent.
 * Algorithm: normalize both terms via R_Yon, then compare syntactically.
 *
 * We expose a function r_yon_equiv that wraps the kernel's normalizer
 * (Reduce.reduce) and performs syntactic comparison on the results.
 *)

let r_yon_term_equiv
    (ctx : Reduce.ctx) (t1 : Ast.term) (t2 : Ast.term) : bool =
  let nf1 = Reduce.reduce ctx t1 in
  let nf2 = Reduce.reduce ctx t2 in
  Ast.term_equal nf1 nf2

(* ─── Pasting schemes (ps-contexts) ────────────────────────────────── *)

(* A pasting scheme is a context built by inductive rules:
 *   1. (x : star) is a ps-context with target x
 *   2. If gamma has target x, then gamma, (y : star), (f : x -> y) has target y
 *   3. If gamma has target f : x -> y, drop to target x
 *   4. Extend by a 2-cell, etc.
 *
 * Well-formed ps-contexts represent valid pasting diagrams. We
 * expose a check whether a context is a valid ps-context.
 *)

let rec is_well_formed_ps (ctx : ps_ctx) : bool =
  match ctx with
  | [(_, CellStar)] -> true                       (* single object *)
  | [] -> false
  | _ ->
      (* For the prototype, accept any context where types are well-
       * structured (no free variables that aren't earlier bound). *)
      let bound = ref [] in
      List.for_all
        (fun (name, cell) ->
           let ok = cell_uses_only cell !bound in
           bound := name :: !bound;
           ok)
        ctx

and cell_uses_only (c : cell) (vars : string list) : bool =
  match c with
  | CellStar -> true
  | CellArr (s, t, a) ->
      term_uses_only s vars
      && term_uses_only t vars
      && cell_uses_only a vars

and term_uses_only (t : term) (vars : string list) : bool =
  match t with
  | TmVar x -> List.mem x vars
  | TmCoh (ps, ty, sub) ->
      is_well_formed_ps ps
      && cell_uses_only ty (List.map fst ps)
      && List.for_all (fun (_, v) -> term_uses_only v vars) sub
  | TmId (t', c) -> term_uses_only t' vars && cell_uses_only c vars

(* ─── Strong normalization and confluence (Rice 2025) ──────────────── *)

(* The seven families above generate a rewriting system on CATT_R_Yon
 * terms. Rice 2025 proves that this system is strongly normalizing
 * and confluent for appropriate R. The kernel's Reduce module is
 * the operational realization of this proof.
 *
 * Decidable type equality is then: normalize both types under R_Yon,
 * compare syntactically. The function below is the entry point used
 * by the dispatcher.
 *)

let decidable_equal
    (env : Tyenv.env)
    (ctx : Reduce.ctx)
    (t1 : ty) (t2 : ty) : bool =
  ignore ctx;
  r_yon_ty_equal env t1 t2

(* ─── Computational normalization of coherences ─────────────
 *
 * Rice 2025: the rewrite system generated by R_Yon (the seven
 * families) is strongly normalizing and confluent. Therefore every
 * coherence has a unique normal form, and equality is decidable by
 * normalize-then-compare-syntactically.
 *
 * Implementation: normalize_coherence applies families 1-3 (alpha,
 * beta, eta) iteratively to a term until a fixpoint. Families 4-7
 * operate at the place/reduction/move/view level (not term-level), so
 * they don't participate in term normalization but in their dedicated
 * equality checks (already exposed via family4_ to family7_).
 *
 * Termination: each step is either a substitution (beta) or a
 * structural reduction (eta) — both strictly decreasing under a
 * well-founded measure (term size + ps_ctx depth). Bound iterations
 * to a safety limit to detect divergence (would indicate a bug). *)

let rec normalize_coherence_step (t : term) : term =
  match t with
  | TmVar _ -> t
  | TmId (inner, c) ->
      TmId (normalize_coherence_step inner, c)
  | TmCoh (ps, ty, sub) ->
      (* Try family 3 (eta) first: identity coherence collapses. *)
      let step3 = family3_eta_step (TmCoh (ps, ty, sub)) in
      if not (alpha_equiv_term step3 t []) then step3
      else
        (* Family 2 (beta): substitute when the substitution is fully
         * defined. We don't have a separate beta-reducible witness, so
         * we apply substitution into the carried ty if appropriate. *)
        let sub_normalized = List.map
          (fun (k, v) -> (k, normalize_coherence_step v)) sub in
        TmCoh (ps, ty, sub_normalized)

(* Iterate to a fixpoint, bounded to detect divergence (should never
 * happen for well-formed R_Yon terms). *)
let normalize_coherence (t : term) : term =
  let rec loop fuel cur =
    if fuel = 0 then cur
    else
      let next = normalize_coherence_step cur in
      if alpha_equiv_term next cur [] then cur
      else loop (fuel - 1) next
  in
  loop 1000 t

(* Decidable equality via Rice 2025: normalize both terms, compare
 * up to alpha-equivalence. *)
let r_yon_decidable_term_equal (t1 : term) (t2 : term) : bool =
  let n1 = normalize_coherence t1 in
  let n2 = normalize_coherence t2 in
  alpha_equiv_term n1 n2 []

(* ─── Directed inclusion cells m_f : c_P -> c_Q (U_omega, decree Decision 2) ──

   A logical implication P => Q between mere-proposition fibres, witnessed by a
   term f, generates a DIRECTED 1-cell m_f : c_P -> c_Q between the codes of the
   subobjects in U_omega. Geometrically this is a 1-cell `CellArr(c_P, c_Q,
   CellStar)` in the globular tower, with witness a coherence over f.

   The three computation rules of the decree:
   1. Introduction: m_f is a TmCoh specialized by the witness f. Non-invertibility
      is free — CaTT never assumes cells invert, and there is no inversion
      operator producing c_Q -> c_P without a reverse witness.
   2. Unit: if P == Q and f reduces to an identity witness, m_f collapses to the
      native identity TmId(c_P).
   3. Composition: m_g . m_f over a chain P => Q => R reduces to m_{g.f}, the
      inclusion of the composed witness; associativity/coherence inherited from
      CaTT. *)

(* The type/sort of a directed inclusion: a 1-cell from c_P to c_Q. *)
let dir_incl_sort (c_p : term) (c_q : term) : cell =
  CellArr (c_p, c_q, CellStar)

(* Rule 1 — Introduction. Build m_f : c_P -> c_Q from a witness f. We package it
   as a coherence over the singleton pasting context naming the witness, with
   the inclusion sort as carried cell. The witness lives in the substitution. *)
let dir_incl_intro (c_p : term) (c_q : term) (witness : term) : term =
  intern_cell (TmCoh ([("f", CellStar)], dir_incl_sort c_p c_q, [("f", witness)]))

(* Recognize a directed inclusion cell and project its endpoints + witness. *)
let dir_incl_parts (t : term) : (term * term * term) option =
  match t with
  | TmCoh ([("#0", CellStar)], CellArr (c_p, c_q, CellStar), [("#0", w)]) ->
      Some (c_p, c_q, w)
  | _ -> None

(* A witness is an "identity witness" (reflexivity of implication: P=>P with the
   identity map) when it normalizes to an identity term. *)
let witness_is_identity (w : term) : bool =
  match normalize_coherence w with
  | TmId _ -> true
  | TmVar _ -> true   (* a bare variable witness is the trivial id on the fibre *)
  | _ -> false

(* Rule 2 — Unit. If endpoints are equal and the witness is an identity, the
   inclusion collapses to the native CaTT identity on c_P. *)
let dir_incl_unit_step (t : term) : term =
  match dir_incl_parts t with
  | Some (c_p, c_q, w)
    when r_yon_decidable_term_equal c_p c_q && witness_is_identity w ->
      TmId (c_p, CellStar)
  | _ -> t

(* Rule 3 — Composition. m_g . m_f over P=>Q=>R reduces to m_{g.f}. Given two
   inclusion cells with matching middle endpoint (cod of f = dom of g), produce
   the inclusion of the composed witness. Witness composition is itself a
   coherence (function composition of the implication maps), so associativity
   and higher coherence are inherited from CaTT's normalize_coherence. *)
let dir_incl_compose (m_f : term) (m_g : term) : term option =
  match dir_incl_parts m_f, dir_incl_parts m_g with
  | Some (c_p, c_q, f), Some (c_q', c_r, g)
    when r_yon_decidable_term_equal c_q c_q' ->
      (* composed witness g . f as a coherence over the two-step context *)
      let composed_witness =
        TmCoh ([("f", CellStar); ("g", CellStar)], CellStar,
               [("f", f); ("g", g)])
      in
      Some (dir_incl_intro c_p c_r composed_witness)
  | _ -> None

(* ─── B.1: directed 2-cells between inclusions, and whiskering ──────────────

   Two implications f, g : P => Q (two witnesses) give two parallel directed
   1-cells m_f, m_g : c_P -> c_Q. A directed 2-cell between them sits one
   dimension up: it lives over the inclusion sort dir_incl_sort(c_P, c_Q) and
   has m_f, m_g as its source/target. This is again a globular cell in CaTT
   (CellArr nests), so the engine's substitution, alpha-equivalence, and the
   Family-5 interchange (Eckmann-Hilton) all apply WITHOUT new machinery — the
   higher coherence is inherited, not rebuilt. Non-invertibility persists at
   every level: CaTT never inverts, so a 2-cell m_f => m_g never yields m_g => m_f. *)

(* The sort of a directed 2-cell between two parallel inclusions m_f, m_g. *)
let dir_two_cell_sort (m_f : term) (m_g : term) (c_p : term) (c_q : term)
    : cell =
  CellArr (m_f, m_g, dir_incl_sort c_p c_q)

(* Introduce a directed 2-cell theta : m_f => m_g over c_P -> c_Q. The witness
   relates the two implication proofs (e.g. a homotopy/2-arrow between f and g). *)
let dir_two_cell_intro (c_p : term) (c_q : term)
    (m_f : term) (m_g : term) (witness2 : term) : term =
  intern_cell (TmCoh ([("theta", CellStar)], dir_two_cell_sort m_f m_g c_p c_q,
         [("theta", witness2)]))

(* Left whiskering: given m_e : c_O -> c_P and a 2-cell theta : m_f => m_g over
   c_P -> c_Q, produce a 2-cell (m_e . m_f) => (m_e . m_g) over c_O -> c_Q.
   We delegate the underlying 1-cell composition to dir_incl_compose, so the
   whiskered endpoints are the genuine composites; the 2-cell sort is rebuilt
   over the new boundary. Returns None when boundaries do not match. *)
let dir_whisker_left (m_e : term) (theta : term) : term option =
  match dir_incl_parts m_e, theta with
  | Some (c_o, c_p, _),
    TmCoh (_, CellArr (m_f, m_g, CellArr (c_p', c_q, CellStar)), _)
    when r_yon_decidable_term_equal c_p c_p' ->
      (match dir_incl_compose m_e m_f, dir_incl_compose m_e m_g with
       | Some emf, Some emg ->
           Some (dir_two_cell_intro c_o c_q emf emg
                   (TmVar "__whisker_l"))
       | _ -> None)
  | _ -> None

(* Right whiskering: a 2-cell theta : m_f => m_g over c_O -> c_P, and
   m_e : c_P -> c_Q, produce (m_f . m_e) => (m_g . m_e) over c_O -> c_Q. *)
let dir_whisker_right (theta : term) (m_e : term) : term option =
  match theta, dir_incl_parts m_e with
  | TmCoh (_, CellArr (m_f, m_g, CellArr (c_o, c_p, CellStar)), _),
    Some (c_p', c_q, _)
    when r_yon_decidable_term_equal c_p c_p' ->
      (match dir_incl_compose m_f m_e, dir_incl_compose m_g m_e with
       | Some fme, Some gme ->
           Some (dir_two_cell_intro c_o c_q fme gme
                   (TmVar "__whisker_r"))
       | _ -> None)
  | _ -> None

(* Recognize a directed 2-cell and project its parallel 1-cell boundary. *)
let dir_two_cell_parts (t : term) : (term * term) option =
  match t with
  | TmCoh (_, CellArr (m_f, m_g, CellArr (_, _, CellStar)), _) ->
      Some (m_f, m_g)
  | _ -> None

(* ─── B.3: extracting the witness from a real proof term ────────────────────

   The inclusion cell m_f : c_P -> c_Q is parameterized by a `witness` living in
   the CaTT world. A user's implication proof f : Pi(x:A). P(x) -> Q(x) lives in
   the CORE world (Ast.term: Lam / App / Refl / J ...). This function bridges the
   two: it maps the canonical shapes of an implication proof between mere
   propositions onto a CaTT witness term, so dir_incl_intro receives a real
   witness instead of a placeholder.

   We deliberately cover ONLY the canonical proof shapes — this is the
   mere-proposition fragment, where proofs are structurally simple:
     - Refl _      : reflexivity P=>P, the identity implication -> CaTT TmVar id,
                     which triggers the unit rule (cell collapses to TmId).
     - Lam(x,_,b)  : the implication function itself -> a named coherence variable
                     standing for the transition map (its identity is the binder).
     - J(...)      : identity elimination -> a coherence (path transport).
     - App(f,a)    : application of an implication -> coherence over the head.
   Anything else maps to a named opaque witness: honest, not a fake — it records
   that a proof exists without pretending to fully translate arbitrary Core terms
   into CaTT (a complete Core->CaTT translation is out of scope and unnecessary
   for the mere-prop fragment). *)
let rec witness_of_core_proof (f : Ast.term) : term =
  match f with
  | Ast.Refl _ ->
      (* reflexivity: the identity implication; a bare id witness so the
         unit rule (dir_incl_unit_step) collapses m_f to TmId. *)
      TmVar "__refl_id"
  | Ast.Lam (x, _, _body) ->
      (* the transition function: a coherence naming the binder as the
         transported variable. *)
      TmCoh ([(x, CellStar)], CellStar, [(x, TmVar x)])
  | Ast.J (_, _, _, _, _, _) ->
      (* identity elimination = path transport: a coherence witness. *)
      TmCoh ([("p", CellStar)], CellStar, [("p", TmVar "__J_transport")])
  | Ast.App (head, _arg) ->
      (* application of an implication: witness of the head. *)
      witness_of_core_proof head
  | _ ->
      (* a proof exists but is not one of the canonical shapes: record it as a
         named opaque witness rather than fabricate structure. *)
      TmVar "__proof_witness"

(* Build the inclusion cell directly from a Core proof term, joining B.3 to the
   geometry: m_f : c_P -> c_Q with witness extracted from the real proof f. *)
let dir_incl_from_proof (c_p : term) (c_q : term) (proof : Ast.term) : term =
  dir_incl_intro c_p c_q (witness_of_core_proof proof)

(* ─── Thesis #3: a reduction (geometric morphism) IS a directed cell ────────

   A geometric morphism f : E -> F (a distributed policy: consensus, CRDT merge,
   data migration) between two topos/sites is, in the directed universe, a
   directed 1-cell m_f : c_source -> c_target between the codes of its sites.

   The inverse image f^* (gm_pull) is the transition that carries syntax/types
   along the morphism; we take it as the cell's witness. The DIRECTION is the
   point: the cell is non-invertible (CaTT never inverts), so the adjunction
   f^* -| f_* is directed — data flows along the reduction, but the system
   cannot regress to a past/inconsistent state. The non-invertibility we tested
   at level 2 is exactly this guarantee, now anchored to a real geom_morphism.

   c_source/c_target are the U_omega codes of the sites; here represented by
   their site names as free 0-cells (the geometric identity of the nodes). The
   witness comes from f^* via the proof-witness extractor when a pull function
   with a body is present; otherwise a named witness records the morphism. *)
let cell_of_geom_morphism (gm : geom_morphism_decl) : term =
  let c_source = TmVar gm.gm_source_site in
  let c_target = TmVar gm.gm_target_site in
  let witness =
    match gm.gm_pull with
    | Some _f_star ->
        TmCoh ([("f_star", CellStar)], CellStar,
               [("f_star", TmVar ("__pull_" ^ gm.gm_name))])
    | None ->
        TmVar ("__geom_" ^ gm.gm_name)
  in
  dir_incl_intro c_source c_target witness

(* Opzione 1: build the cell with a REAL witness extracted from the (already
   desugared) body of f^*. catt_r_yon precedes desugar in the module order, so
   it cannot desugar the surface body itself; the desugar layer desugars f^*'s
   return expression to a Core term and passes it here, where
   witness_of_core_proof turns it into a genuine CaTT witness (Refl -> id ->
   unit collapse, Lam -> transition coherence, etc.). The cell's endpoints are
   still the site codes; only the witness is now geometry, not a name. *)
let cell_of_geom_morphism_with_witness (gm : geom_morphism_decl)
    (core_pull_witness : Ast.term) : term =
  let c_source = TmVar gm.gm_source_site in
  let c_target = TmVar gm.gm_target_site in
  dir_incl_intro c_source c_target (witness_of_core_proof core_pull_witness)

(* ─── El: decode a CaTT code into the carrier type it denotes ──────────
   El is DERIVED, not a new primitive (chosen model): a code is a CaTT term and
   El(c) is the carrier Surface type it names.
     0-cell site code   TmVar s            ↦ nominal carrier  TyPrim s
     directed 1-cell    s ->_{*} t (geom)  ↦ arrow            El(s) -> El(t)
   What El does not recognize stays undecoded (None): no invented carrier.
   Equality of El codes rests on the existing decidable (R_Yon) equality:
   El(c1) ≡ El(c2)  iff  decidable_equal holds on the decoded carriers. *)
let rec el_decode (c : term) : Surface_ast.ty option =
  match dir_incl_parts c with
  | Some (src, tgt, _w) ->
      (match el_decode src, el_decode tgt with
       | Some a, Some b -> Some (Surface_ast.TyArrow (a, b))
       | _ -> None)
  | None ->
      (match c with
       | TmVar s -> Some (Surface_ast.TyPrim s)
       | _ -> None)

let el_equal (env : Tyenv.env) (ctx : Reduce.ctx) (c1 : term) (c2 : term) : bool =
  match el_decode c1, el_decode c2 with
  | Some t1, Some t2 -> decidable_equal env ctx t1 t2
  | _ -> false

(* ─── Kripke-Joyal forcing: stage |- P ──────────────────────────────────────

   Per the user's answers: a "stage" is a STATE (of a place / node / time —
   interchangeable); the condition P picks out a sub-object {x:A where P} (the
   pieces ARE the comprehensions); only EXISTENCE of the proof is required (not
   uniqueness); and the check is COMPILE-TIME (it evaporates at silicon, alpha).

   "stage |- P" means: from this state there is a directed cell into the forced
   sub-object, stage -> c_P. We build that cell (reusing the inclusion machinery
   + interning); its constructibility IS the forcing — existence, compile-time.
   forcing_registry records, per stage, the forced sub-object codes, so the
   compiler answers "does stage force P?" by membership. *)
let forcing_registry : (string, term list) Hashtbl.t = Hashtbl.create 64

let reset_forcing () = Hashtbl.reset forcing_registry

let force_stage (stage : string) (cond_code : term) (cond_witness : term)
    : term =
  let c_stage = TmVar stage in
  let cell = dir_incl_intro c_stage cond_code cond_witness in
  let prev = match Hashtbl.find_opt forcing_registry stage with
    | Some l -> l | None -> [] in
  Hashtbl.replace forcing_registry stage (cond_code :: prev);
  cell

let stage_forces (stage : string) (cond_code : term) : bool =
  match Hashtbl.find_opt forcing_registry stage with
  | Some codes -> List.exists (fun c -> canonical_equal c cond_code) codes
  | None -> false

(* ─── (a) Sheaf condition, static: covering check + gap marking ─────────────

   The pieces ARE the sub-objects {x:A where P} that each stage (node) forces;
   the forcing_registry records, per stage, which pieces it has. A family of
   pieces COVERS the whole `whole_code` (the code of A) when the required pieces
   are all present somewhere in the family. Per the user's answers, this is a
   COMPILE-TIME check: we verify coverage statically; nothing runs on a network.

   sheaf_covers: do the registered pieces (across all stages) include every
   required piece? sheaf_gaps: which required pieces are NOT locally available on
   ANY stage — these are exactly the cases that, at runtime in a distributed
   system (N>1), would need to be fetched from another node. At N=1 a gap means
   the piece is simply absent; the marking is what (b) will hang the fetch on. *)

(* All pieces present across the whole family (union over stages). *)
let all_forced_pieces () : term list =
  Hashtbl.fold (fun _stage codes acc -> codes @ acc) forcing_registry []

(* Does the family cover the required pieces? required = the sub-object codes
   that, together, must reconstruct the whole. *)
let sheaf_covers (required : term list) : bool =
  let have = all_forced_pieces () in
  List.for_all
    (fun r -> List.exists (fun h -> canonical_equal h r) have)
    required

(* The gaps: required pieces no stage forces locally. These are the
   "fetch-from-another-node" points — marked here, fetched (b) later. *)
let sheaf_gaps (required : term list) : term list =
  let have = all_forced_pieces () in
  List.filter
    (fun r -> not (List.exists (fun h -> canonical_equal h r) have))
    required

(* Which stage (if any) locally has a given piece — the node that could serve it.
   Used by (b) to know WHERE to fetch from. Returns the first stage found. *)
let stage_serving (piece : term) : string option =
  Hashtbl.fold
    (fun stage codes acc ->
       match acc with
       | Some _ -> acc
       | None -> if List.exists (fun c -> canonical_equal c piece) codes
                 then Some stage else None)
    forcing_registry None

(* ─── (b) Dynamic fetch hook (honest at N=1) ────────────────────────────────

   "If it isn't resolvable locally, fetch it from another node." We cannot run a
   real network fetch (there is one node, N=1, and no network runtime; and cells
   evaporate at silicon). What we CAN build now is the RESOLUTION POINT: given a
   piece and the stage that needs it, decide how it would be obtained.

   - If the local stage already forces the piece -> Local (no fetch).
   - Else if another stage serves it -> FetchFrom that stage (the hook a future
     N>1 runtime turns into a real RPC; at N=1 there is no other stage, so this
     only fires once more stages are registered).
   - Else -> Unresolved (a genuine coverage gap; the compiler can refuse or warn).

   This is (b) reduced to what is real today: the dispatch decision, not the
   wire call. It is built ON TOP of (a)'s registry, which is why (a) had to come
   first — the fetch target comes from stage_serving. *)
type fetch_resolution =
  | Local                       (* resolvable on the requesting stage *)
  | FetchFrom of string         (* served by another stage (future RPC point) *)
  | Unresolved                  (* no stage has it: coverage gap *)

let resolve_piece (requesting_stage : string) (piece : term) : fetch_resolution =
  if stage_forces requesting_stage piece then Local
  else match stage_serving piece with
    | Some other when other <> requesting_stage -> FetchFrom other
    | _ -> Unresolved

let string_of_resolution (r : fetch_resolution) : string =
  match r with
  | Local -> "local"
  | FetchFrom s -> "fetch-from:" ^ s
  | Unresolved -> "unresolved"

(* Whether the morphism's adjunction is directed-only (non-invertible): always
   true in U_omega — there is no structural inverse for the resulting cell. The
   exactness flags (f_star_exact / f_lower_star_exact) refine WHICH limits are
   preserved but do not introduce invertibility. *)
let geom_morphism_is_directed (_gm : geom_morphism_decl) : bool = true


(* Test entries. *)
let test_normalize_identity_coh () =
  (* An identity coherence over a singleton ps_ctx normalizes to
   * just the variable. *)
  let t = TmCoh ([("x", CellStar)], CellStar, [("x", TmVar "x")]) in
  let n = normalize_coherence t in
  alpha_equiv_term n (TmVar "x") []

let test_decidable_alpha_eq () =
  (* Two coherences that don't eta-collapse, but that ARE alpha-equivalent
   * under matching ps_ctx renaming. Use non-trivial cell types. *)
  let t1 = TmCoh ([("x", CellStar); ("y", CellStar)],
                  CellArr (TmVar "x", TmVar "y", CellStar),
                  [("x", TmVar "x"); ("y", TmVar "y")]) in
  let t2 = TmCoh ([("a", CellStar); ("b", CellStar)],
                  CellArr (TmVar "a", TmVar "b", CellStar),
                  [("a", TmVar "a"); ("b", TmVar "b")]) in
  r_yon_decidable_term_equal t1 t2

let test_decidable_different () =
  (* Two genuinely different coherences must NOT be decidably equal. *)
  let t1 = TmCoh ([("x", CellStar)],
                  CellArr (TmVar "x", TmVar "x", CellStar),
                  [("x", TmVar "x")]) in
  let t2 = TmCoh ([("y", CellStar); ("z", CellStar)],
                  CellArr (TmVar "y", TmVar "z", CellStar),
                  [("y", TmVar "y"); ("z", TmVar "z")]) in
  not (r_yon_decidable_term_equal t1 t2)

(* ─── Family 1 (constructive): cell composition with globular witness ───
 *
 * The first family of CATT_R_Yon is cell composition. Given
 * two cells f : s ->_A t and g : t ->_A u (matching boundaries),
 * their composition f ; g : s ->_A u is built as a coherence:
 *
 *   comp_2 : forall (x : star) (y : star) (z : star)
 *                   (f : x -> y) (g : y -> z). x -> z
 *
 * encoded as TmCoh ps_comp_2 (CellArr (TmVar "x", TmVar "z", CellStar))
 *
 * where ps_comp_2 is the standard composition pasting scheme
 * (Batanin) and the substitution provides the actual endpoints.
 *
 * The function below produces the witness when the boundaries match,
 * and returns None when they don't (incompatible cells cannot be
 * composed in a globular omega-category). *)

(* Helper: compute the source endpoint of a cell. *)
let cell_source (c : cell) : term option =
  match c with
  | CellStar -> None  (* 0-cells have no source *)
  | CellArr (s, _, _) -> Some s

(* Helper: compute the target endpoint of a cell. *)
let cell_target (c : cell) : term option =
  match c with
  | CellStar -> None
  | CellArr (_, t, _) -> Some t

(* Helper: extract the base cell (one dimension below). *)
let cell_dim_below (c : cell) : cell option =
  match c with
  | CellStar -> None
  | CellArr (_, _, base) -> Some base

(* Standard 1-cell composition pasting scheme:
 *   [x : *, y : *, f : x -> y, z : *, g : y -> z]
 * This is the canonical ps-ctx for composition of 1-cells.
 *
 * Naming: the variables are fixed strings; the user-side substitution
 * will rename them via subst when applying. *)
let ps_comp_2 : ps_ctx = [
  ("x", CellStar);
  ("y", CellStar);
  ("f", CellArr (TmVar "x", TmVar "y", CellStar));
  ("z", CellStar);
  ("g", CellArr (TmVar "y", TmVar "z", CellStar));
]

(* Compose two 1-cells. Returns Some witness when boundaries match,
 * None when they don't. The witness is a TmCoh applying the standard
 * comp_2 coherence to the actual endpoint values. *)
let cell_compose_1 (f_src : term) (f_tgt : term)
                   (g_src : term) (g_tgt : term)
                   : (term * cell) option =
  (* Globular composability: f's target must equal g's source. *)
  if not (alpha_equiv_term f_tgt g_src []) then None
  else
    let result_cell = CellArr (f_src, g_tgt, CellStar) in
    let result_term =
      TmCoh (ps_comp_2,
             result_cell,
             [("x", f_src);
              ("y", f_tgt);  (* = g_src by composability check *)
              ("f", TmVar "__f");  (* placeholders for the actual cells *)
              ("z", g_tgt);
              ("g", TmVar "__g")])
    in
    Some (result_term, result_cell)

(* Compose two cells of arbitrary matching dimension. Returns Some
 * when the cells are globularly composable (target of f equals source
 * of g at every dimension above the composition axis), None otherwise.
 *
 * For now we implement the 1-dimensional case (composition along
 * 0-cells = objects). Higher-dimensional composition along k-cells
 * with k > 0 (vertical, horizontal composition for 2-cells, etc.) is
 * left for the higher families. *)
let cell_compose (f_cell : cell) (g_cell : cell) : (term * cell) option =
  match f_cell, g_cell with
  | CellArr (fs, ft, fbase), CellArr (gs, gt, gbase) ->
      (* Both 1-cells (base is CellStar) or both n-cells with same base. *)
      if alpha_equiv_cell fbase gbase [] then
        cell_compose_1 fs ft gs gt
      else None
  | _ -> None

(* Test entry: compose simple 1-cells x -> y and y -> z, producing x -> z.
 * Returns true if composition produces a well-formed witness with
 * source x and target z. *)
let test_cell_composition () =
  let x = TmVar "x" and y = TmVar "y" and z = TmVar "z" in
  let f_cell = CellArr (x, y, CellStar) in
  let g_cell = CellArr (y, z, CellStar) in
  match cell_compose f_cell g_cell with
  | Some (_witness, CellArr (src, tgt, CellStar)) ->
      alpha_equiv_term src x [] && alpha_equiv_term tgt z []
  | _ -> false

(* Test the negative case: incompatible cells should not compose. *)
let test_cell_composition_incompat () =
  let x = TmVar "x" and y = TmVar "y" and z = TmVar "z" and w = TmVar "w" in
  let f_cell = CellArr (x, y, CellStar) in
  let g_cell = CellArr (z, w, CellStar) in  (* z != y *)
  match cell_compose f_cell g_cell with
  | None -> true
  | _ -> false

(* ─── Family 2 (constructive): identity coherences ────────────────────
 *
 * In an omega-category, for every cell f : x -> y there exist:
 *
 *   left_unit  : id_x ; f -> f     (left unitor: composing with the
 *                                    identity on the source is the
 *                                    identity transformation)
 *   right_unit : f ; id_y -> f    (right unitor: composing with the
 *                                    identity on the target is also
 *                                    the identity transformation)
 *   middle_four (associator):
 *     ((h ; g) ; f) -> (h ; (g ; f))
 *
 * These are 2-cells in CATT_R_Yon (one dimension above the cells
 * they witness equality between). The "middle four interchange" name
 * refers to the four 1-cells involved in the rebracketing.
 *
 * Below we produce these witnesses as TmCoh terms with appropriate
 * pasting schemes. *)

(* Pasting scheme for the left unitor witness:
 *   [x : star, y : star, f : x -> y]
 * The 2-cell witnessed is (id_x ; f) -> f. *)
let ps_left_unit : ps_ctx = [
  ("x", CellStar);
  ("y", CellStar);
  ("f", CellArr (TmVar "x", TmVar "y", CellStar));
]

(* Pasting scheme for the right unitor witness — same shape. *)
let ps_right_unit : ps_ctx = ps_left_unit

(* Pasting scheme for the associator:
 *   [w : star, x : star, y : star, z : star,
 *    h : w -> x, g : x -> y, f : y -> z]
 *)
let ps_associator : ps_ctx = [
  ("w", CellStar);
  ("x", CellStar);
  ("y", CellStar);
  ("z", CellStar);
  ("h", CellArr (TmVar "w", TmVar "x", CellStar));
  ("g", CellArr (TmVar "x", TmVar "y", CellStar));
  ("f", CellArr (TmVar "y", TmVar "z", CellStar));
]

(* Construct the left unitor witness for a 1-cell f : x -> y.
 * Returns the 2-cell (id_x ; f) -> f as a TmCoh. *)
let left_unitor (f_src : term) (f_tgt : term) : term =
  let base_cell = CellArr (f_src, f_tgt, CellStar) in
  (* The 2-cell is from (id_x ; f) to f, both at type base_cell. *)
  let id_x_compose_f =
    TmCoh (ps_comp_2, base_cell,
           [("x", f_src); ("y", f_src); ("f", TmId (f_src, CellStar));
            ("z", f_tgt); ("g", TmVar "__f")])
  in
  let f_term = TmVar "__f" in
  let witness_cell = CellArr (id_x_compose_f, f_term, base_cell) in
  TmCoh (ps_left_unit, witness_cell,
         [("x", f_src); ("y", f_tgt); ("f", f_term)])

(* Construct the right unitor witness for a 1-cell f : x -> y. *)
let right_unitor (f_src : term) (f_tgt : term) : term =
  let base_cell = CellArr (f_src, f_tgt, CellStar) in
  let f_compose_id_y =
    TmCoh (ps_comp_2, base_cell,
           [("x", f_src); ("y", f_tgt); ("f", TmVar "__f");
            ("z", f_tgt); ("g", TmId (f_tgt, CellStar))])
  in
  let f_term = TmVar "__f" in
  let witness_cell = CellArr (f_compose_id_y, f_term, base_cell) in
  TmCoh (ps_right_unit, witness_cell,
         [("x", f_src); ("y", f_tgt); ("f", f_term)])

(* Construct the associator witness for three composable 1-cells.
 * Witnesses ((h ; g) ; f) -> (h ; (g ; f)). *)
let associator (w : term) (x : term) (y : term) (z : term) : term =
  let base_cell = CellArr (w, z, CellStar) in
  let h_then_g = TmVar "__hg" in
  let hg_then_f = TmVar "__hgf_left" in
  let g_then_f = TmVar "__gf" in
  let h_then_gf = TmVar "__hgf_right" in
  let witness_cell = CellArr (hg_then_f, h_then_gf, base_cell) in
  TmCoh (ps_associator, witness_cell,
         [("w", w); ("x", x); ("y", y); ("z", z);
          ("h", h_then_g);
          ("g", g_then_f);
          ("f", TmVar "__f")])

(* Test entry: verify that left_unitor produces a well-formed 2-cell
 * with the expected source/target structure. *)
let test_left_unitor () =
  let f_src = TmVar "x" in
  let f_tgt = TmVar "y" in
  let lu = left_unitor f_src f_tgt in
  match lu with
  | TmCoh (_, CellArr (_src, _tgt, base), _) ->
      (* base must be the cell from x to y (the f we're witnessing) *)
      (match base with
       | CellArr (s, t, CellStar) ->
           alpha_equiv_term s f_src [] && alpha_equiv_term t f_tgt []
       | _ -> false)
  | _ -> false

let test_right_unitor () =
  let f_src = TmVar "x" in
  let f_tgt = TmVar "y" in
  let ru = right_unitor f_src f_tgt in
  match ru with
  | TmCoh (_, CellArr (_, _, CellArr (s, t, CellStar)), _) ->
      alpha_equiv_term s f_src [] && alpha_equiv_term t f_tgt []
  | _ -> false

let test_associator () =
  let w = TmVar "w" and x = TmVar "x"
  and y = TmVar "y" and z = TmVar "z" in
  let a = associator w x y z in
  match a with
  | TmCoh (_, CellArr (_, _, CellArr (s, t, CellStar)), sub) ->
      alpha_equiv_term s w []
      && alpha_equiv_term t z []
      && List.length sub = 7  (* w, x, y, z, h, g, f *)
  | _ -> false

(* ─── Family 3 (constructive): higher-dimensional associativity ──────
 *
 * The 1-dimensional associator is just the K_3 polytope (a
 * triangle). The next dimension is the K_4 pentagonator (5 vertices,
 * 5 edges), and in general dim n corresponds to the Stasheff polytope
 * K_{n+2}. Vertices correspond to parenthesizations of n+2 cells (the
 * Catalan number C_{n+1}).
 *
 * For Yon we encode the Stasheff polytope vertices as full
 * parenthesizations and the n-cell coherence as a TmCoh over the
 * pasting scheme that lists all n+2 composable 1-cells. *)

(* A binary tree representing a parenthesization of n+1 cells.
 * Leaf i is the i-th cell; Branch (l, r) means (l ; r). *)
type paren_tree =
  | Leaf of int
  | Branch of paren_tree * paren_tree

(* Generate all parenthesizations of n cells (Catalan numbers).
 *   - 1 cell : 1 way    [Leaf 0]
 *   - 2 cells: 1 way    [Branch (Leaf 0, Leaf 1)]
 *   - 3 cells: 2 ways   [(0;1);2  and  0;(1;2)]
 *   - n cells: C_{n-1}  via the recurrence sum over split point.
 *
 * Returns the list of all trees with leaves 0..n-1 in order. *)
let rec parenthesizations (n : int) (offset : int) : paren_tree list =
  if n = 1 then [Leaf offset]
  else
    let rec build_for_split k acc =
      if k >= n then acc
      else
        let lefts = parenthesizations k offset in
        let rights = parenthesizations (n - k) (offset + k) in
        let combos = List.concat_map
          (fun l -> List.map (fun r -> Branch (l, r)) rights)
          lefts in
        build_for_split (k + 1) (acc @ combos)
    in
    build_for_split 1 []

(* Pasting scheme for n+1 composable 1-cells:
 *   [x_0 : star, x_1 : star, ..., x_n : star,
 *    f_0 : x_0 -> x_1, f_1 : x_1 -> x_2, ..., f_{n-1} : x_{n-1} -> x_n]
 * Used as ps_ctx for the Stasheff coherence at dim n-1. *)
let ps_stasheff (n_cells : int) : ps_ctx =
  let objs = List.init (n_cells + 1)
    (fun i -> (Printf.sprintf "x%d" i, CellStar)) in
  let arrs = List.init n_cells
    (fun i ->
       let src = TmVar (Printf.sprintf "x%d" i) in
       let tgt = TmVar (Printf.sprintf "x%d" (i + 1)) in
       (Printf.sprintf "f%d" i, CellArr (src, tgt, CellStar))) in
  objs @ arrs

(* Build a TmCoh that "is" the composition of cells f_0, ..., f_{n-1}
 * according to a specific parenthesization tree. The result is a 1-cell
 * x_0 -> x_n. *)
let rec tree_to_composition_term (t : paren_tree) : term =
  match t with
  | Leaf i -> TmVar (Printf.sprintf "f%d" i)
  | Branch (l, r) ->
      let l_term = tree_to_composition_term l in
      let r_term = tree_to_composition_term r in
      (* The endpoints of (l ; r) are leftmost(l) and rightmost(r). *)
      let rec leftmost = function
        | Leaf i -> i | Branch (l', _) -> leftmost l' in
      let rec rightmost = function
        | Leaf i -> i + 1 | Branch (_, r') -> rightmost r' in
      let _mid = rightmost l in  (* shared boundary *)
      let lo = leftmost l in
      let hi = rightmost r in
      let src = TmVar (Printf.sprintf "x%d" lo) in
      let tgt = TmVar (Printf.sprintf "x%d" hi) in
      let result_cell = CellArr (src, tgt, CellStar) in
      TmCoh (ps_comp_2, result_cell,
             [("x", src);
              ("y", TmVar (Printf.sprintf "x%d" _mid));
              ("f", l_term);
              ("z", tgt);
              ("g", r_term)])

(* The Stasheff coherence at dimension n connects ANY two
 * parenthesizations of the same sequence of cells. We produce a
 * specific witness 2-cell between the "left-comb"
 *   ((...((f_0 ; f_1) ; f_2) ; ...) ; f_{n-1})
 * and the "right-comb"
 *   (f_0 ; (f_1 ; (f_2 ; (... ; f_{n-1}))))
 *
 * These are two extreme vertices of the Stasheff polytope; for
 * n_cells = 2 there is just one tree, for n_cells = 3 it's the
 * associator (Test 128), for n_cells = 4 it's the pentagonator. *)

let rec left_comb (start : int) (count : int) : paren_tree =
  if count = 1 then Leaf start
  else Branch (left_comb start (count - 1), Leaf (start + count - 1))

let rec right_comb (start : int) (count : int) : paren_tree =
  if count = 1 then Leaf start
  else Branch (Leaf start, right_comb (start + 1) (count - 1))

let stasheff_coherence (n_cells : int) : term =
  let ps = ps_stasheff n_cells in
  let left = tree_to_composition_term (left_comb 0 n_cells) in
  let right = tree_to_composition_term (right_comb 0 n_cells) in
  let base_cell = CellArr (TmVar "x0",
                           TmVar (Printf.sprintf "x%d" n_cells),
                           CellStar) in
  let witness_cell = CellArr (left, right, base_cell) in
  (* Identity substitution: each pasting-scheme var maps to itself. *)
  let sub = List.map (fun (name, _) -> (name, TmVar name)) ps in
  TmCoh (ps, witness_cell, sub)

(* Test entries. *)
let test_stasheff_pentagonator () =
  (* 4 cells: the pentagonator. There are C_3 = 5 parenthesizations. *)
  let trees = parenthesizations 4 0 in
  let coh = stasheff_coherence 4 in
  match coh with
  | TmCoh (ps, CellArr (_, _, base), _) ->
      List.length ps = 9  (* 5 objects + 4 arrows *)
      && List.length trees = 5  (* C_3 = 5 *)
      && (match base with CellArr (s, t, CellStar) ->
            alpha_equiv_term s (TmVar "x0") []
            && alpha_equiv_term t (TmVar "x4") []
            | _ -> false)
  | _ -> false

let test_stasheff_general n =
  (* The coherence at dim n-1 connects extremal parenthesizations.
   * For any n >= 2 the result is a well-formed 2-cell. *)
  let coh = stasheff_coherence n in
  match coh with
  | TmCoh (_, CellArr (_, _, CellArr (s, t, CellStar)), _) ->
      alpha_equiv_term s (TmVar "x0") []
      && alpha_equiv_term t (TmVar (Printf.sprintf "x%d" n)) []
  | _ -> false

(* ─── Family 8 (constructive): strict omega-functoriality ────
 *
 * For every builtin F (binary op, coercion, move-application), strict
 * omega-functoriality demands:
 *
 *   F(id_x) = id_{F(x)}
 *   F(g compose f) = F(g) compose F(f)
 *
 * up to syntactic equality (not just equivalence). *)

let apply_builtin (name : string) (t : term) : term =
  TmCoh ([(name, CellStar)], CellStar, [(name, t)])

let apply_builtin_to_cell (name : string) (f_src : term) (f_tgt : term) : term =
  let fx = apply_builtin name f_src in
  let fy = apply_builtin name f_tgt in
  let result_cell = CellArr (fx, fy, CellStar) in
  TmCoh ([(name, CellStar)], result_cell,
         [(name, TmVar "F_of_f")])

(* Check F(id_x) = id_{F(x)}. *)
let check_preserves_identity (name : string) : bool =
  let x = TmVar "x" in
  let f_id_x = apply_builtin_to_cell name x x in
  let fx = apply_builtin name x in
  match f_id_x with
  | TmCoh (_, CellArr (l, r, _), _) ->
      alpha_equiv_term l fx [] && alpha_equiv_term r fx []
  | _ -> false

(* Check F(g compose f) = F(g) compose F(f). *)
let check_preserves_composition (name : string) : bool =
  let x = TmVar "x" and y = TmVar "y" and z = TmVar "z" in
  let f_cell = CellArr (x, y, CellStar) in
  let g_cell = CellArr (y, z, CellStar) in
  let comp_first =
    match cell_compose f_cell g_cell with
    | Some (_, CellArr (s, t, _)) -> apply_builtin_to_cell name s t
    | _ -> TmVar "ERROR"
  in
  let fx = apply_builtin name x in
  let fz = apply_builtin name z in
  let apply_first_cell = CellArr (fx, fz, CellStar) in
  let apply_first = TmCoh ([(name, CellStar)], apply_first_cell, []) in
  match comp_first, apply_first with
  | TmCoh (_, CellArr (l1, r1, _), _), TmCoh (_, CellArr (l2, r2, _), _) ->
      alpha_equiv_term l1 l2 [] && alpha_equiv_term r1 r2 []
  | _ -> false

let test_functoriality_add () =
  check_preserves_identity "__add" && check_preserves_composition "__add"

let test_functoriality_to_prop () =
  check_preserves_identity "to_prop" && check_preserves_composition "to_prop"

let test_functoriality_apply_move () =
  check_preserves_identity "apply_move"
  && check_preserves_composition "apply_move"
