(* cubical.ml — Cubical Type Theory fragment for Yon.
 *
 * A prototype of the (∞,1)-decidable layer of the federation, modelled on
 * Cohen-Coquand-Huber-Mörtberg 2016 "Cubical Type Theory: a
 * constructive interpretation of the univalence axiom." Scoped to a future
 * version (1.2): the composition/transport/glue rules below handle the basic
 * cases and fall back to a canonical form for the rest (see the "prototype"
 * notes in reduce_comp and the HIT comp), so this is not a complete CCHM
 * implementation.
 *
 * The cubical layer provides (in prototype form):
 *
 *   1. The interval I with endpoints 0 and 1, and connections
 *      (min, max, negation) for face formulas.
 *   2. Path types Path A x y, with path abstraction <i> t and
 *      path application p @ i.
 *   3. Composition: comp A φ u u_0 fills the cube whose sides
 *      agree on the face formula φ.
 *   4. Homogeneous composition (hcomp), a special case for fixed type.
 *   5. Glue types Glue [φ ↦ (T, e)] A for univalence: a type that
 *      agrees with T on φ and with A elsewhere via equivalence e.
 *   6. Transport: transp A i a, the iterated composition along a
 *      path of types.
 *   7. Higher Inductive Types (HIT): quotients, suspensions, circle,
 *      defined by point constructors and path constructors.
 *
 * For Yon, the cubical layer handles:
 *   - Identity types between values of base types (text, number, ...).
 *   - Univalence-via-equivalence between places that are R_Yon structural place equivalence
 *     equivalent (delegated to CATT_R_Yon for actual signature check).
 *   - Quotient types (e.g., Currency / equivalent_currency_set).
 *
 * The cubical fragment is decidable because cubical type checking is
 * decidable (the original CCHM result). In this prototype the composition
 * and glue operations reduce to canonical forms on the basic cases and are
 * left as a canonical (un-reduced) form otherwise.
 *)

open Surface_ast

(* ─── The interval ─────────────────────────────────────────────────── *)

(* The interval I has two endpoints, 0 and 1. Interval expressions are
 * built from variables, endpoints, and connections (min ⊓, max (+),
 * and negation ~i which sends 0 ↔ 1).
 *)

type interval =
  | I0                                  (* the endpoint 0 *)
  | I1                                  (* the endpoint 1 *)
  | IVar of string                      (* an interval variable i *)
  | IMin of interval * interval         (* i ⊓ j: minimum *)
  | IMax of interval * interval         (* i (+) j: maximum *)
  | INeg of interval                    (* ~i: 1 - i *)

let rec interval_to_string (i : interval) : string =
  match i with
  | I0 -> "0"
  | I1 -> "1"
  | IVar x -> x
  | IMin (a, b) -> "(" ^ interval_to_string a ^ " ⊓ " ^ interval_to_string b ^ ")"
  | IMax (a, b) -> "(" ^ interval_to_string a ^ " (+) " ^ interval_to_string b ^ ")"
  | INeg a -> "~" ^ interval_to_string a

(* Normalize an interval expression to a canonical form. The cubical
 * algebra is a free distributive lattice with negation generated by
 * the interval variables. *)

let rec normalize_interval (i : interval) : interval =
  match i with
  | I0 | I1 | IVar _ -> i
  | INeg I0 -> I1
  | INeg I1 -> I0
  | INeg (INeg a) -> normalize_interval a
  | INeg a -> INeg (normalize_interval a)
  | IMin (I0, _) | IMin (_, I0) -> I0
  | IMin (I1, b) -> normalize_interval b
  | IMin (a, I1) -> normalize_interval a
  | IMin (a, b) when a = b -> normalize_interval a
  | IMin (a, b) -> IMin (normalize_interval a, normalize_interval b)
  | IMax (I1, _) | IMax (_, I1) -> I1
  | IMax (I0, b) -> normalize_interval b
  | IMax (a, I0) -> normalize_interval a
  | IMax (a, b) when a = b -> normalize_interval a
  | IMax (a, b) -> IMax (normalize_interval a, normalize_interval b)

(* Equality on intervals after normalization. *)
let interval_equal (i1 : interval) (i2 : interval) : bool =
  normalize_interval i1 = normalize_interval i2

(* Substitute an interval variable in an interval expression. *)
let rec subst_interval (var : string) (replacement : interval) (i : interval) : interval =
  match i with
  | I0 | I1 -> i
  | IVar x -> if x = var then replacement else i
  | IMin (a, b) -> IMin (subst_interval var replacement a,
                         subst_interval var replacement b)
  | IMax (a, b) -> IMax (subst_interval var replacement a,
                         subst_interval var replacement b)
  | INeg a -> INeg (subst_interval var replacement a)

(* ─── Face formulas ────────────────────────────────────────────────── *)

(* A face formula φ is a disjunction of conjunctions of atomic faces
 * of the form (i = 0) or (i = 1). It identifies a sub-cube of the
 * n-cube on which a partial element is defined.
 *
 * We represent a face as a list of atoms, and a formula as a list
 * of faces (disjunction).
 *)

type face_atom = string * bool         (* (i, b): i = if b then 1 else 0 *)
type face = face_atom list             (* conjunction *)
type face_formula = face list          (* disjunction *)

let face_is_consistent (f : face) : bool =
  (* No variable assigned both 0 and 1. *)
  let rec check seen = function
    | [] -> true
    | (x, b) :: rest ->
        (match List.assoc_opt x seen with
         | Some b' when b' <> b -> false
         | _ -> check ((x, b) :: seen) rest)
  in
  check [] f

(* Evaluate a face under an interval substitution. *)
let face_holds (f : face) (sub : (string * interval) list) : bool =
  List.for_all
    (fun (var, expected_b) ->
       match List.assoc_opt var sub with
       | Some I0 -> not expected_b
       | Some I1 -> expected_b
       | _ -> false)
    f

let formula_holds (phi : face_formula) (sub : (string * interval) list) : bool =
  List.exists (fun f -> face_holds f sub) phi

(* ─── Cubical types ────────────────────────────────────────────────── *)

(* The syntax of cubical types extends ordinary types with:
 *   - Path A x y: identity type between x and y in A
 *   - Glue: glue type for univalence
 *   - HIT: higher inductive types
 *
 * For interoperation with the surface language, we wrap a surface
 * ty in CTBase and add cubical-specific constructors.
 *)

type ctype =
  | CTBase of ty                                          (* a surface type *)
  | CTPath of ctype * cterm * cterm                       (* Path A x y *)
  | CTPathP of (string * ctype) * cterm * cterm          (* PathP (<i> A i) x y :
                                                            dependent path over a line of
                                                            types A(i); x : A 0, y : A 1 *)
  | CTGlue of ctype * face_formula * (ctype * cterm) list (* Glue [φ ↦ (T, e)] A *)
  | CTQuotient of ctype * (cterm * cterm) list            (* A / ~ via path constructors *)
  | CTHIT of string * cterm list                          (* user-defined HIT *)

and cterm =
  | CVar of string                                        (* a term variable *)
  | CPathLam of string * cterm                            (* <i> t — path abstraction *)
  | CPathApp of cterm * interval                          (* p @ i — path application *)
  | CComp of ctype * face_formula
            * (string * face * cterm) list                (* partial sides u *)
            * cterm                                       (* base u_0 *)
  | CHComp of ctype * face_formula
             * (string * face * cterm) list * cterm       (* homogeneous comp *)
  | CGlueElem of face_formula * cterm * cterm             (* glue [phi |-> t] a *)
  | CUnglue of cterm                                      (* unglue projector *)
  | CTransport of (string * ctype) * cterm                (* transp <i>A i_0 t *)
  | CInhabitant of cterm                                  (* lift a non-cubical term *)
  | CCore of Ast.term                                     (* opaque lift of a core term:
                                                             carries an Ast.term the engine
                                                             never inspects; the bridge
                                                             unfolds it back on the way out.
                                                             Invariant: lifted terms do not
                                                             mention the cubical dimensions
                                                             active in the surrounding comp/
                                                             transp (equivalences and maps are
                                                             dimension-closed), so dimension
                                                             substitution treats it opaquely. *)
  | CHITConstr of string * cterm list                     (* HIT constructor application *)
  | CHITElim of (string * string list * cterm) list * cterm (* generic HIT eliminator:
                                                             branches (constructor name |-> case)
                                                             applied to a scrutinee *)

(* ─── Path types and path computation ──────────────────────────────── *)

(* A path p : Path A x y has the property that p @ 0 = x and p @ 1 = y.
 * Path application reduces:
 *   (<i> t) @ 0 = t[i := 0]
 *   (<i> t) @ 1 = t[i := 1]
 *   (<i> t) @ j = t[i := j] for non-endpoint j
 *)

let rec subst_interval_in_cterm
    (var : string) (replacement : interval) (t : cterm) : cterm =
  match t with
  | CVar _ -> t
  | CPathLam (i, _body) when i = var ->
      (* Bound variable shadows — don't substitute inside. *)
      t
  | CPathLam (i, body) ->
      CPathLam (i, subst_interval_in_cterm var replacement body)
  | CPathApp (p, j) ->
      CPathApp (subst_interval_in_cterm var replacement p,
                subst_interval var replacement j)
  | CComp (ty, phi, sides, base) ->
      let ty' = subst_interval_in_ctype var replacement ty in
      let phi' = subst_interval_in_formula var replacement phi in
      let sides' = List.filter_map
        (fun (i, face, term) ->
           match subst_interval_in_face var replacement face with
           | None -> None
           | Some f' -> Some (i, f', subst_interval_in_cterm var replacement term))
        sides in
      let base' = subst_interval_in_cterm var replacement base in
      CComp (ty', phi', sides', base')
  | CHComp (ty, phi, sides, base) ->
      let ty' = subst_interval_in_ctype var replacement ty in
      let phi' = subst_interval_in_formula var replacement phi in
      let sides' = List.filter_map
        (fun (i, face, term) ->
           match subst_interval_in_face var replacement face with
           | None -> None
           | Some f' -> Some (i, f', subst_interval_in_cterm var replacement term))
        sides in
      let base' = subst_interval_in_cterm var replacement base in
      CHComp (ty', phi', sides', base')
  | CGlueElem (phi, t', a') ->
      CGlueElem (subst_interval_in_formula var replacement phi,
                 subst_interval_in_cterm var replacement t',
                 subst_interval_in_cterm var replacement a')
  | CUnglue t' -> CUnglue (subst_interval_in_cterm var replacement t')
  | CTransport ((i, ty), t') ->
      let ty' = if i = var then ty
                else subst_interval_in_ctype var replacement ty in
      CTransport ((i, ty'), subst_interval_in_cterm var replacement t')
  | CInhabitant _ -> t
  | CCore _ -> t   (* dimension-closed by invariant: no active dimension occurs *)
  | CHITConstr (n, args) ->
      CHITConstr (n, List.map (subst_interval_in_cterm var replacement) args)
  | CHITElim (branches, scrut) ->
      CHITElim (List.map (fun (n, vs, c) ->
        (n, vs, subst_interval_in_cterm var replacement c)) branches,
                subst_interval_in_cterm var replacement scrut)

and subst_interval_in_ctype
    (var : string) (replacement : interval) (ty : ctype) : ctype =
  match ty with
  | CTBase _ -> ty
  | CTPath (a, x, y) ->
      CTPath (subst_interval_in_ctype var replacement a,
              subst_interval_in_cterm var replacement x,
              subst_interval_in_cterm var replacement y)
  | CTPathP ((i, a), x, y) ->
      let a' = if i = var then a
               else subst_interval_in_ctype var replacement a in
      CTPathP ((i, a'),
               subst_interval_in_cterm var replacement x,
               subst_interval_in_cterm var replacement y)
  | CTGlue (base, phi, partial) ->
      (* phi (the disjunction of glue faces) is aligned POSITIONALLY with the
       * per-face pair list `partial`: phi.(k) <-> partial.(k) = (T_k, e_k).
       * A dimension substitution can KILL a face (subst_interval_in_face -> None,
       * e.g. (i=0) under i:=1) or make it a TAUTOLOGY ([] under the matching
       * endpoint). We must keep phi and partial aligned by processing them
       * TOGETHER: drop the pair whenever its face dies, keep it (with the face,
       * possibly now []) otherwise. A plain filter_map on phi + map on partial
       * de-syncs the two lists and would make a surviving glue face borrow the
       * wrong equivalence — the root of the multi-face restriction bug. *)
      let subst_pair (t, e) =
        (subst_interval_in_ctype var replacement t,
         subst_interval_in_cterm var replacement e) in
      let rec go fs ps = match fs, ps with
        | [], [] -> ([], [])
        | f :: fs', p :: ps' ->
            let (phi', partial') = go fs' ps' in
            (match subst_interval_in_face var replacement f with
             | None -> (phi', partial')                     (* face dies: drop pair too *)
             | Some f' -> (f' :: phi', subst_pair p :: partial'))
        | _, _ ->
            (* lengths already out of sync (should not happen): fall back to the
             * independent maps rather than crash, so at least each list is
             * self-consistent. *)
            (subst_interval_in_formula var replacement fs,
             List.map subst_pair ps) in
      let (phi', partial') = go phi partial in
      CTGlue (subst_interval_in_ctype var replacement base, phi', partial')
  | CTQuotient (a, paths) ->
      CTQuotient (subst_interval_in_ctype var replacement a,
                  List.map (fun (x, y) ->
                    (subst_interval_in_cterm var replacement x,
                     subst_interval_in_cterm var replacement y))
                    paths)
  | CTHIT (n, args) ->
      CTHIT (n, List.map (subst_interval_in_cterm var replacement) args)

and subst_interval_in_face
    (var : string) (replacement : interval) (f : face) : face option =
  (* Resolve the bound var inside a face (a conjunction of atoms (x,b),
     b=true meaning x=1, b=false meaning x=0).
     - a satisfied atom is dropped (an empty result face = tautology, holds);
     - a contradicted atom makes the whole face FALSE -> None (drop it from
       the disjunction);
     - an atom on another/symbolic dimension is kept. *)
  let rec go acc = function
    | [] -> Some (List.rev acc)
    | (x, b) :: rest ->
        if x = var then
          (match normalize_interval replacement with
           | I1 -> if b then go acc rest else None
           | I0 -> if b then None else go acc rest
           | _ -> go ((x, b) :: acc) rest)
        else go ((x, b) :: acc) rest
  in
  go [] f

and subst_interval_in_formula
    (var : string) (replacement : interval) (phi : face_formula) : face_formula =
  List.filter_map (subst_interval_in_face var replacement) phi

(* Path application — the key reduction rule of path types. *)
let path_app (p : cterm) (j : interval) : cterm =
  match p with
  | CPathLam (i, body) -> subst_interval_in_cterm i j body
  | _ -> CPathApp (p, j)

(* ─── Glue constructors and projectors ─────────────────────────────── *)

(* Constructors used by the composition rule below; defined here so
 * that reduce_comp can reference them. *)

let glue_type
    (base : ctype) (phi : face_formula)
    (partial : (ctype * cterm) list) : ctype =
  CTGlue (base, phi, partial)

let glue_elem (phi : face_formula) (t : cterm) (a : cterm) : cterm = CGlueElem (phi, t, a)

let unglue (t : cterm) : cterm =
  match t with
  | CGlueElem (_, _, a) -> a
  | _ -> CUnglue t

(* ─── Composition operation ────────────────────────────────────────── *)

(* The composition operation comp A φ u u_0 has these reduction rules:
 *
 *   comp A 1 u u_0 = u[i := 1]
 *   comp A 0 u u_0 = u_0  (when φ is the always-false formula)
 *
 * Plus equations for specific types: comp at a Path type unfolds to
 * a nested composition, comp at a Glue type uses transport, etc.
 *
 * The full computation rules require recursion on the structure of
 * the type. For the prototype we handle the basic cases and leave
 * a structural fallback for the rest.
 *)

let rec reduce_comp (ty : ctype) (phi : face_formula)
                    (sides : (string * face * cterm) list)
                    (base : cterm) : cterm =
  match phi with
  | [] -> base                            (* empty disjunction = false *)
  | _ ->
      (* face-active rule: a tautological face ([]) is always on, so the
         system is solved by that side (CCHM adjacency). *)
      match List.find_opt (fun (_, fc, _) -> fc = []) sides with
      | Some (_, _, v) -> v
      | None ->
      match ty with
      | CTPath (inner_ty, p_left, p_right) ->
          (* comp at Path type: build a path-abstraction whose body
           * is the composition in the inner type, with extended
           * boundary conditions from the path endpoints. *)
          let j = "_comp_j" in
          let extended_phi =
            phi @ [ [(j, false)]; [(j, true)] ] in
          let extended_sides =
            sides
            @ [ ("_pathbnd_l", [(j, false)], p_left);
                ("_pathbnd_r", [(j, true)], p_right) ] in
          let base_at_j = path_app base (IVar j) in
          CPathLam (j,
            reduce_comp inner_ty extended_phi extended_sides base_at_j)

      | CTPathP ((pi, a), p_left, p_right) ->
          (* comp at a DEPENDENT path type. Same shape as comp at Path,
           * but the inner line of types a = A(pi) varies along the path
           * binder pi; the composition happens in that varying type. *)
          let extended_phi =
            phi @ [ [(pi, false)]; [(pi, true)] ] in
          let extended_sides =
            sides
            @ [ ("_pathpbnd_l", [(pi, false)], p_left);
                ("_pathpbnd_r", [(pi, true)], p_right) ] in
          let base_at_pi = path_app base (IVar pi) in
          CPathLam (pi,
            reduce_comp a extended_phi extended_sides base_at_pi)

      | CTGlue (base_ty, glue_phi, partial_pairs) ->
          (match partial_pairs with
           | [] ->
               (* Degenerate Glue with no partial equivalences = the base
                * type B. comp reduces to comp in the base. *)
               let base_sides =
                 List.map (fun (i, f, t) -> (i, f, unglue t)) sides in
               let base_u0 = unglue base in
               let combined_phi = phi @ glue_phi in
               let a_comp = reduce_comp base_ty combined_phi base_sides base_u0 in
               CGlueElem ([], a_comp, a_comp)  (* degenerate: empty face, no T part *)
           | _ ->
               (* Non-degenerate Glue at a constant type: composition at a type
                * that does not vary along the dimension IS the homogeneous rule
                * (comp = hcomp). The heterogeneous case — a Glue varying along
                * i, i.e. ua(e) — is handled by the transp-Glue rule, which
                * applies the forward map. So comp-Glue delegates to hcomp-Glue,
                * which pushes the composition into T and A with a w.f coherence
                * patch (no isEquiv needed). *)
               reduce_hcomp ty phi sides base)

      | CTQuotient (underlying_ty, _path_constructors) ->
          (* comp at quotient: compose in the underlying type, then
           * project back into the quotient via the canonical
           * embedding inj. *)
          let inner_comp = reduce_comp underlying_ty phi sides base in
          CHITConstr ("inj", [inner_comp])

      | CTHIT (hit_name, _params) ->
          (* comp at a HIT type: consult the HIT signature to dispatch
           * on the constructor of the base term.
           *
           * Semantics (prototype):
           *   - If base is CHITConstr (cname, cargs) where cname is a
           *     POINT constructor with NO arguments (a "vertex" like
           *     S¹.base or S².base): the composition is the constant
           *     point itself. Composing over a constant produces the
           *     constant.
           *   - If base is CHITConstr with arguments: recursively
           *     compose each argument; reassemble.
           *   - If base is a PATH constructor: leave as canonical form
           *     (full path composition is the heart of cubical
           *     reduction, beyond the prototype's scope).
           *   - If signature not found or base shape unrecognized:
           *     fall back to canonical CComp.
           *)
          (match Hit_env.lookup Hit_env.builtin_env hit_name with
           | None -> CComp (ty, phi, sides, base)
           | Some sig_ ->
               match base with
               | CHITConstr (cname, []) ->
                   (* Zero-arity point constructor: comp is the point. *)
                   if List.exists (fun pc -> pc.Hit_env.pc_name = cname)
                                  sig_.Hit_env.hit_points
                   then base
                   else CComp (ty, phi, sides, base)
               | CHITConstr (cname, cargs) ->
                   (* Multi-arity point constructor: comp each arg.
                    * Each arg is itself a cterm; we conservatively
                    * recurse only if the arg type can be inferred as
                    * the SAME HIT (self-referential). Without full
                    * dependent reduction we just recompose. *)
                   if List.exists (fun pc -> pc.Hit_env.pc_name = cname)
                                  sig_.Hit_env.hit_points
                   then CHITConstr (cname, cargs)
                   else CComp (ty, phi, sides, base)
               | _ -> CComp (ty, phi, sides, base))

      | CTBase _ ->
          (* comp at a constant (base) type IS hcomp at that type. With a
           * non-trivial phi it is NOT the base, so delegate to hcomp, which
           * keeps the faces (the face-active rule fires once a face becomes
           * tautological, e.g. after a path-beta specializes the dimension).
           * The phi = [] (false) case already returned base above. *)
          reduce_hcomp ty phi sides base

(* Homogeneous composition: type doesn't vary along the dimension. *)
and reduce_hcomp (ty : ctype) (phi : face_formula)
                 (sides : (string * face * cterm) list)
                 (base : cterm) : cterm =
  match phi with
  | [] -> base
  | _ ->
      (match List.find_opt (fun (_, fc, _) -> fc = []) sides with
       | Some (_, _, v) -> v
       | None ->
      match ty with
      | CTGlue (a_ty, gphi, partial) ->
          (match partial with
           | [] ->
               (* degenerate Glue = base type A: hcomp in A, re-wrap *)
               let u_sides = List.map (fun (nm, f, u) -> (nm, f, unglue u)) sides in
               let a1 = reduce_hcomp a_ty phi u_sides (unglue base) in
               CGlueElem ([], a1, a1)
           | _ :: _ ->
               (* CCHM homogeneous composition at a Glue type. The type is
                * constant along the dimension, so this needs only the forward
                * maps w_k.f (no isEquiv): push the hcomp into the T-component
                * and the A-component, patching coherence on EVERY glue face.
                *
                * A Glue's partial element is a face SYSTEM
                *   [ psi_1 |-> (T_1, e_1), ..., psi_n |-> (T_n, e_n) ]
                * where gphi = [psi_1; ...; psi_n] is aligned POSITIONALLY with
                * `partial` = [(T_1,e_1); ...; (T_n,e_n)] (invariant preserved by
                * to_ctype/of_ctype in builtins.ml). Composition must handle ALL
                * faces: on each psi_k the A-component is patched by the k-th
                * forward map e_k applied to the filler computed in the k-th type
                * T_k. The old code used (T_1,e_1) for the whole system, so any
                * restriction to psi_k (k>1) produced e_1 — the multi-face bug. *)
               let tpart v = match v with CGlueElem (_, t, _) -> t | _ -> v in
               let t_sides = List.map (fun (nm, f, u) -> (nm, f, tpart u)) sides in
               let t0 = tpart base in
               let l = "_hg_l" in
               (* the length invariant between the disjunction gphi and the
                * per-face pair list `partial`. If they ever diverge (they must
                * not) we pad/truncate to the common prefix so every handled face
                * keeps its own equivalence rather than borrowing the head's. *)
               let faces =
                 let rec zip fs ps = match fs, ps with
                   | f :: fs', p :: ps' -> (f, p) :: zip fs' ps'
                   | _, _ -> [] in
                 zip gphi partial in
               (* one coherence side PER glue face:
                *   on psi_k:  <l> e_k.f (hfill_{T_k} @ l)
                * where hfill_{T_k} @ l = hcomp T_k [phi |-> t-part u, (l=0)|->t0] t0
                * equals t0 at l=0 and t1_k at l=1. Both the filler type and the
                * forward map are taken from the k-th pair. *)
               let coh_sides =
                 List.map
                   (fun (psi_k, (tk_ty, ek)) ->
                      let hfill_k =
                        reduce_hcomp tk_ty (phi @ [[(l, false)]])
                          (t_sides @ [("_hg_fill", [(l, false)], t0)]) t0 in
                      let wf_k x = CHITConstr ("__equiv_fwd", [ek; x]) in
                      (l, psi_k, wf_k hfill_k))
                   faces in
               (* t1 : T = the fiber component of the result glue-elem. It is a
                * PARTIAL element on gphi: on psi_k it lives in T_k, and there it
                * must be the composition IN T_k of the t-part sides — hcomp^phi T_k
                * [phi |-> t-part u] t0. Composing once in the first pair's type is
                * per-face WRONG when the T_k genuinely vary (different reduction
                * rules): restricting the result to psi_k would then read the fiber
                * in T_1's type, not T_k. So we build t1 as a system that FORCES each
                * glue face psi_k to its own T_k-composite; restricting the result to
                * psi_k then yields the correct per-face fiber. The base stays t0 and
                * the default dispatch is the first pair's (off every psi_k the fiber
                * is unobserved — a glue-elem degenerates to its base there). When all
                * T_k share a rule (e.g. all CTBase) every per-face composite
                * coincides, so this reduces to the old single composite: no change on
                * the existing (non-varying) tests, correct on the varying ones. *)
               let t1_ty = match partial with (tk, _) :: _ -> tk | [] -> a_ty in
               let t1_faces =
                 List.mapi
                   (fun idx (psi_k, (tk_ty, _ek)) ->
                      (Printf.sprintf "_hg_t1_%d" idx, psi_k,
                       reduce_hcomp tk_ty phi t_sides t0))
                   faces in
               let t1 = reduce_hcomp t1_ty (phi @ gphi) (t_sides @ t1_faces) t0 in
               (* a1 : A = hcomp A [phi |-> unglue u,
                *                    psi_k |-> <l> e_k.f(hfill_{T_k})] (unglue base) *)
               let u_sides = List.map (fun (nm, f, u) -> (nm, f, unglue u)) sides in
               let a1 = reduce_hcomp a_ty (phi @ gphi) (u_sides @ coh_sides) (unglue base) in
               CGlueElem (gphi, t1, a1))
      | _ -> CHComp (ty, phi, sides, base))

(* ─── Transport ────────────────────────────────────────────────────── *)

(* transp <i> A i_0 t transports t along the line of types A(i).
 * Key reduction:
 *   transp <i> A 0 t : A(1)  with t : A(0)
 *
 * For specific A:
 *   transp <i> (Path B x y) i_0 p = ...     (composition equation)
 *   transp <i> (X -> Y) i_0 f = ...           (function transport)
 *   transp <i> (CTBase T) i_0 t = t          (constant: identity)
 *)

let rec reduce_transport ((i, ty) : string * ctype) (t : cterm) : cterm =
  match ty with
  | CTBase _ -> t                            (* constant type: identity *)
  | CTPath (a, x, y) ->
      (* transp <i> (Path A x y) t reduces to a comp expression.
       * In CCHM:
       *   transp <i> (Path A x y) t =
       *     <j> comp A (j=0 -> x (+) j=1 -> y) (t @ j)
       *)
      let fresh_j = "_transp_j" in
      CPathLam (fresh_j,
        reduce_comp a
          [[(fresh_j, false)]; [(fresh_j, true)]]
          [(i, [(fresh_j, false)], x);
           (i, [(fresh_j, true)], y)]
          (path_app t (IVar fresh_j)))
  | CTPathP ((pi, a), x, y) ->
      (* transp <i> (PathP (<pi> A i pi) x y) t.
       * Rename the path binder off the transport dimension i, then
       * comp in the (doubly-varying) line with the endpoints as the
       * boundary along the fresh path dimension. *)
      let fresh_j = "_transp_j" in
      let a_j = subst_interval_in_ctype pi (IVar fresh_j) a in
      CPathLam (fresh_j,
        reduce_comp a_j
          [[(fresh_j, false)]; [(fresh_j, true)]]
          [(i, [(fresh_j, false)], x);
           (i, [(fresh_j, true)], y)]
          (path_app t (IVar fresh_j)))
  | CTGlue (base, glue_phi, partial) ->
      (* ── CCHM transport at a Glue type ─────────────────────────────────
       * Cohen–Coquand–Huber–Mörtberg 2018, §6.2 (transp = comp with the
       * empty system). Line of types, moving the transport dimension i:0→1:
       *
       *     B(i) = Glue [ φ ↦ (T_k, e_k)_k ] A          A = the base type
       *
       * φ = glue_phi is the glue extent, aligned POSITIONALLY with `partial`
       * = [(T_1,e_1); …; (T_n,e_n)] (invariant preserved by to_ctype/of_ctype
       * in builtins.ml and by subst_interval_in_ctype above). Each e_k : T_k ≃ A
       * is the core Σ (f,(g,(η,ε))); the engine reaches the forward map f via
       * the marker __equiv_fwd (lowered to `App (Fst e, ·)` in builtins.ml)
       * and the inverse g via __equiv_bwd (`App (Fst (Snd e), ·)`).
       *
       * The six CCHM steps, at the prototype level:
       *
       *  (1) a0 = unglue^{i:=0} t0, the base value at the start.  On any glue
       *      face φ_k that is a TAUTOLOGY at i=0 the start type collapses to
       *      T_k and `unglue` there IS the forward map, so a0 = e_k.f(t0).
       *      (In the engine t0 is then a bare fibre element, not a glue-elem,
       *      so we emit e_k.f(t0) directly instead of calling `unglue`.)  Off
       *      every start face, a0 = unglue t0.
       *
       *  (2) a1 = transp^i A a0 : A[i:=1]  — the base transported to the target
       *      (identity when A is constant, e.g. CTBase; recurses otherwise).
       *
       *  (3)/(4) fibre correction.  On each glue face φ_k the corrected result
       *      fibre is the centre of the contractible fibre of e_k.f over a1,
       *      t1'_k = e_k.g(a1), with a coherence path ω_k : e_k.f(t1'_k) ~ a1.
       *
       *  (5) a1' = comp^j A [ φ ↦ ω ] a1 adjusts the base along ω.  RESIDUAL:
       *      ω needs the ε-homotopy of e_k as a genuine filler, which this
       *      prototype does not compute, so we keep a1' = a1 (the un-adjusted
       *      transport).  This leaves the base-boundary unglue(result)=a1 exact
       *      and the fibre-boundary result|φ_k = t1'_k exact; the only thing
       *      NOT enforced is that a1 = e_k.f(t1'_k) on φ_k (that is ω, the open
       *      coherence — see the report).
       *
       *  (6) result = glue [ φ[i:=1] ↦ t1' ] a1'.  On a target face φ_k that is
       *      a TAUTOLOGY at i=1 the target type collapses to T_k and the
       *      glue-elem degenerates to its fibre, so the observable result is
       *      that face's corrected fibre t1'_k = e_k.g(a1) directly.
       *
       * Specialisation to ua.  For `ua e` the line is
       *   Glue [(i=0) ↦ (A,e), (i=1) ↦ (B, idEquiv)] B :
       *     • start face (i=0) taut  ⇒ a0 = e.f(t0);
       *     • A = B constant         ⇒ a1 = a0 = e.f(t0);
       *     • target face (i=1) taut ⇒ result = idEquiv.g(a1) = a1 = e.f(t0)
       *       (idEquiv.g β-reduces to the identity in the core).
       *   So `transp (ua e) t0` = e.f(t0) — the univalence computation rule,
       *   the transport_ua_succ anchor.  EVERY face is handled per-face (the
       *   start/target faces via their own e_k above, interior faces via the
       *   per-face fibre system below), never "just the first pair". *)
      let fwd e x = CHITConstr ("__equiv_fwd", [e; x]) in
      let bwd e x = CHITConstr ("__equiv_bwd", [e; x]) in
      (* pair each glue face with its (T_k, e_k), keeping φ and partial aligned *)
      let faces =
        let rec zip fs ps = match fs, ps with
          | f :: fs', p :: ps' -> (f, p) :: zip fs' ps'
          | _, _ -> [] in
        zip glue_phi partial in
      (match faces with
       | [] ->
           (* degenerate Glue with no partial system = its base type A *)
           reduce_transport (i, base) t
       | _ ->
           let taut_at endpoint f =
             (subst_interval_in_face i endpoint f = Some []) in
           (* (1) base value at the start = unglue^{i:=0} t0. *)
           let a0 =
             match List.find_opt (fun (f, _) -> taut_at I0 f) faces with
             | Some (_, (_tk, ek)) -> fwd ek t   (* start face taut: unglue = e.f *)
             | None ->
                 (match t with
                  | CGlueElem (_, _, a) -> a      (* genuine glue-elem: base part *)
                  | _ -> t)                       (* extent ⊥ at i=0: type = A, t : A,
                                                     so unglue is the identity here *)
           in
           (* (2) transport the base to A[i:=1] *)
           let a1 = reduce_transport (i, base) a0 in
           (* (6) result — target-face collapse vs. glue-elem *)
           (match List.find_opt (fun (f, _) -> taut_at I1 f) faces with
            | Some (_, (_tk, ek)) ->
                (* target face taut: glue degenerates to the fibre; observable
                 * result is that face's corrected fibre e_k.g(a1) *)
                bwd ek a1
            | None ->
                (* one corrected fibre e_k.g(a1) per SURVIVING target face
                 * φ_k[i:=1] (faces that die under i:=1 leave the extent) *)
                let t1_faces =
                  List.concat
                    (List.mapi
                       (fun idx (f, (_tk, ek)) ->
                          match subst_interval_in_face i I1 f with
                          | Some f1 when f1 <> [] ->
                              [ (Printf.sprintf "_tg_fib_%d" idx, f1, bwd ek a1) ]
                          | _ -> [])
                       faces) in
                (match t1_faces with
                 | [] -> a1                     (* target extent empty: type = A *)
                 | (_, _, v0) :: _ ->
                     let phi1 = List.map (fun (_, f, _) -> f) t1_faces in
                     let t1_ty =
                       match partial with (tk, _) :: _ -> tk | [] -> base in
                     (* one system that FORCES each target face to its own fibre,
                      * so restricting the result to φ_k yields e_k.g(a1), never
                      * the head's — the same per-face device as the hcomp-Glue
                      * T-component fix. Off the extent the glue-elem degenerates
                      * to its base a1, so the fibre's default dispatch (v0) and
                      * its type (t1_ty) are unobserved there. *)
                     let fiber = reduce_hcomp t1_ty phi1 t1_faces v0 in
                     CGlueElem (phi1, fiber, a1))))
  | _ -> CTransport ((i, ty), t)

(* ─── Glue types and univalence ────────────────────────────────────── *)

(* Glue [φ ↦ (T, e)] A is a type that equals T on the face φ and A
 * everywhere else, where e is an equivalence T ~= A. Its inhabitants
 * are constructed by glue-elem: given t : T on φ and a : A in general
 * agreeing via e, glue-elem(t, a) : Glue.
 *
 * For univalence: given an equivalence e : A ~= B, we form the
 * line of types <i> Glue [i=0 -> (A, e), i=1 -> (B, id)] B, which
 * gives a path A == B.
 *)

(* ─── Higher Inductive Types ───────────────────────────────────────── *)

(* HITs are inductive types with two kinds of constructors:
 *   - Point constructors: usual constructors producing elements
 *   - Path constructors: producing equalities between elements
 *
 * Examples:
 *   - S¹: point base, path loop : base = base
 *   - Quotient A R: inj : A -> A/R, quot : forallx y, R x y -> inj x = inj y
 *   - Suspension A: north, south, merid : A -> north = south
 *
 * For Yon, HITs are declared via sum types extended with path equations.
 * We represent a HIT signature here and check inhabitants against it.
 *)

type hit_signature = {
  hit_name : string;
  hit_points : (string * ctype list) list;     (* name + arg types *)
  hit_paths : (string * (string * ctype) list  (* params *)
              * cterm * cterm) list;            (* endpoints *)
}

let hit_constructor_arity (sig_ : hit_signature) (cname : string) : int option =
  (* First check point constructors *)
  match List.assoc_opt cname sig_.hit_points with
  | Some args -> Some (List.length args)
  | None ->
      match List.find_opt (fun (n, _, _, _) -> n = cname) sig_.hit_paths with
      | Some (_, params, _, _) -> Some (List.length params)
      | None -> None

(* ─── Decidable equality on cubical terms ──────────────────────────── *)

(* Cubical type checking is decidable because:
 *   1. Path application reduces by interval substitution
 *   2. Composition reduces by structural rules on the type
 *   3. Transport reduces to identity on constant types and recursion
 *      on indexed types
 *   4. Glue terms are normalized by the boundary conditions
 *
 * We implement a normalizer and a structural-equality comparator.
 *)

let rec normalize_cterm (t : cterm) : cterm =
  match t with
  | CVar _ -> t
  | CPathLam (i, body) -> CPathLam (i, normalize_cterm body)
  | CPathApp (p, j) ->
      let p' = normalize_cterm p in
      let j' = normalize_interval j in
      (match p', j' with
       | CPathLam (i, body), _ ->
           normalize_cterm (subst_interval_in_cterm i j' body)
       | CHITConstr ("loop", []), I0 -> CHITConstr ("base", [])  (* loop @ 0 = base *)
       | CHITConstr ("loop", []), I1 -> CHITConstr ("base", [])  (* loop @ 1 = base *)
       | _ -> CPathApp (p', j'))
  | CComp (ty, phi, sides, base) ->
      let result = reduce_comp ty phi sides base in
      (match result with
       | CComp _ -> result                 (* couldn't reduce further *)
       | other -> normalize_cterm other)
  | CHComp (ty, phi, sides, base) ->
      let result = reduce_hcomp ty phi sides base in
      (match result with
       | CHComp _ -> result
       | other -> normalize_cterm other)
  | CGlueElem (phi, t', a') -> CGlueElem (phi, normalize_cterm t', normalize_cterm a')
  | CUnglue t' ->
      let t'' = normalize_cterm t' in
      (match t'' with
       | CGlueElem (_, _, a) -> a
       | _ -> CUnglue t'')
  | CTransport ((i, ty), t') ->
      let result = reduce_transport (i, ty) (normalize_cterm t') in
      (match result with
       | CTransport _ -> result
       | other -> normalize_cterm other)
  | CInhabitant _ -> t
  | CCore _ -> t   (* opaque: the core reducer handles it after of_cterm *)
  | CHITElim (branches, scrut) ->
      (* generic HIT eliminator, any dimension. For any HIT, given a case per
       * constructor:
       *   elim (c a1..an)        = (case_c) a1 .. an
       *   elim (p a1..an @r1..@rk) = ((case_p) a1 .. an) @ r1 .. @ rk
       * Argument application is deferred to the core via "__app"; path
       * applications (one per path dimension) are peeled off and re-applied,
       * so 1-dim (loop, merid, quot, inj) and 2-dim (S2 surf) are uniform. *)
      let scrut' = normalize_cterm scrut in
      let apply_args case args =
        List.fold_left (fun f a -> CHITConstr ("__app", [f; a])) case args in
      (* peel nested path applications down to the head HIT constructor,
       * collecting the interval arguments outermost-application-first *)
      let rec peel t acc =
        match t with
        | CPathApp (inner, j) -> peel inner (j :: acc)
        | CHITConstr (pname, pargs) -> Some (pname, pargs, acc)
        | _ -> None in
      (match scrut' with
       | CHITConstr (cname, cargs) ->
           (match List.find_opt (fun (name, _, _) -> name = cname) branches with
            | Some (_, _, case) -> normalize_cterm (apply_args case cargs)
            | None -> CHITElim (branches, scrut'))
       | CPathApp _ ->
           (match peel scrut' [] with
            | Some (pname, pargs, ints) ->
                (match List.find_opt (fun (name, _, _) -> name = pname) branches with
                 | Some (_, _, case) ->
                     let applied = apply_args case pargs in
                     normalize_cterm
                       (List.fold_left (fun acc j -> path_app acc j) applied ints)
                 | None -> CHITElim (branches, scrut'))
            | None -> CHITElim (branches, scrut'))
       | _ -> CHITElim (branches, scrut'))
  | CHITConstr (n, args) -> CHITConstr (n, List.map normalize_cterm args)

let rec cterm_equal (t1 : cterm) (t2 : cterm) : bool =
  let n1 = normalize_cterm t1 in
  let n2 = normalize_cterm t2 in
  cterm_syntactic_equal n1 n2

and cterm_syntactic_equal (t1 : cterm) (t2 : cterm) : bool =
  match t1, t2 with
  | CVar x, CVar y -> x = y
  | CPathLam (i, b1), CPathLam (j, b2) ->
      (* alpha-equivalent: rename j to i in b2 and compare. *)
      let b2' = subst_interval_in_cterm j (IVar i) b2 in
      cterm_syntactic_equal b1 b2'
  | CPathApp (p1, j1), CPathApp (p2, j2) ->
      cterm_syntactic_equal p1 p2 && interval_equal j1 j2
  | CGlueElem (p1, t1, a1), CGlueElem (p2, t2, a2) ->
      p1 = p2 && cterm_syntactic_equal t1 t2 && cterm_syntactic_equal a1 a2
  | CUnglue t1, CUnglue t2 -> cterm_syntactic_equal t1 t2
  | CTransport ((i1, ty1), t1), CTransport ((i2, ty2), t2) ->
      let ty2' = subst_interval_in_ctype i2 (IVar i1) ty2 in
      ctype_equal ty1 ty2' && cterm_syntactic_equal t1 t2
  | CInhabitant _, CInhabitant _ -> t1 = t2
  | CHITConstr (n1, a1), CHITConstr (n2, a2) ->
      n1 = n2
      && List.length a1 = List.length a2
      && List.for_all2 cterm_syntactic_equal a1 a2
  | CComp _, CComp _ | CHComp _, CHComp _ ->
      t1 = t2                                (* structural after normalization *)
  | CCore a, CCore b -> Ast.term_equal_env [] a b
  | CHITElim (b1, s1), CHITElim (b2, s2) ->
      List.length b1 = List.length b2
      && List.for_all2 (fun (n1, vs1, c1) (n2, vs2, c2) ->
           n1 = n2 && vs1 = vs2 && cterm_syntactic_equal c1 c2) b1 b2
      && cterm_syntactic_equal s1 s2
  | _, _ -> false

and ctype_equal (a : ctype) (b : ctype) : bool =
  match a, b with
  | CTBase t1, CTBase t2 ->
      Catt_r_yon.ty_structural_eq t1 t2
  | CTPath (a1, x1, y1), CTPath (a2, x2, y2) ->
      ctype_equal a1 a2
      && cterm_equal x1 x2
      && cterm_equal y1 y2
  | CTPathP ((i1, a1), x1, y1), CTPathP ((i2, a2), x2, y2) ->
      let a2' = subst_interval_in_ctype i2 (IVar i1) a2 in
      ctype_equal a1 a2' && cterm_equal x1 x2 && cterm_equal y1 y2
  | CTGlue (a1, phi1, p1), CTGlue (a2, phi2, p2) ->
      ctype_equal a1 a2
      && phi1 = phi2
      && List.length p1 = List.length p2
      && List.for_all2
           (fun (t1, e1) (t2, e2) ->
              ctype_equal t1 t2 && cterm_equal e1 e2)
           p1 p2
  | CTQuotient (a1, ps1), CTQuotient (a2, ps2) ->
      ctype_equal a1 a2
      && List.length ps1 = List.length ps2
      && List.for_all2
           (fun (x1, y1) (x2, y2) ->
              cterm_equal x1 x2 && cterm_equal y1 y2)
           ps1 ps2
  | CTHIT (n1, a1), CTHIT (n2, a2) ->
      n1 = n2
      && List.length a1 = List.length a2
      && List.for_all2 cterm_equal a1 a2
  | _, _ -> false

(* ─── Univalence ───────────────────────────────────────────────────── *)

(* Univalence says: equality of types is equivalent to equivalence of
 * types. (A == B) ~= (A ~= B). The computational content via Glue is:
 *
 *   ua : (A ~= B) -> (A == B)
 *   ua e = <i> Glue [i=0 -> (A, e), i=1 -> (B, id)] B
 *
 * We expose a helper that constructs this path given an equivalence.
 *)

(* ua : (A ~= B) -> Path U A B
 *
 * Computational content (CCHM):
 *   ua e = <i> Glue [(i=0) ↦ (A, e), (i=1) ↦ (B, id)] B
 *
 * The resulting path, at endpoint i=0, is A (via the equivalence e);
 * at endpoint i=1, is B (via identity). At all interior points i it
 * is the Glue type that mediates between them.
 *
 * We return a path *between types* — represented as a path-abstraction
 * whose body is a Glue type lifted to the term layer via CInhabitant.
 * This is the standard way cubical implementations encode "paths in
 * the universe": types appear as inhabitants of a type universe, and
 * a path between types is a function from I to that universe.
 *)

(* Helper: identity equivalence on a type A.
 *
 * An equivalence A ~= B in CCHM is a pair (f, isEquiv f). The
 * identity equivalence is (id_A, id-is-equiv). We don't track the
 * "isEquiv" proof at the prototype level — it's a coherence witness.
 *)
let id_equiv (_a : ctype) : cterm =
  CVar "__id"   (* the identity function as the underlying map *)

(* Encode a type-as-term for the universe layer.
 *
 * In a full cubical implementation, types live in a universe `U` and
 * are themselves terms of type U. The constructor CTypeAsTerm
 * promotes a type to a term inhabiting the universe. We use
 * CInhabitant for this lift; downstream code recognizes it as a
 * universe element via tagged pattern matching.
 *)
let type_as_term (t : ctype) : cterm =
  CInhabitant (
    match t with
    | CTBase _ -> CVar "__type_base"
    | CTPath _ -> CVar "__type_path"
    | CTPathP _ -> CVar "__type_pathp"
    | CTGlue _ -> CVar "__type_glue"
    | CTQuotient _ -> CVar "__type_quot"
    | CTHIT (n, _) -> CVar ("__type_hit_" ^ n)
  )

let ua (a : ctype) (b : ctype) (e : cterm) : cterm =
  let i = "_ua_i" in
  (* Build the Glue type:
   *   Glue [(i=0) ↦ (A, e), (i=1) ↦ (B, id_B)] B
   *
   * As ctype: CTGlue base phi partial
   * where phi = [(i=0); (i=1)] and partial pairs (A, e) and (B, id).
   *)
  let glue_ty = CTGlue (
    b,                                    (* base type B *)
    [ [(i, false)];                       (* face i=0 *)
      [(i, true)] ],                      (* face i=1 *)
    [ (a, e);                             (* on i=0: type A with equiv e *)
      (b, id_equiv b) ]                   (* on i=1: type B with id *)
  ) in
  (* The result is a path: <i> (glue_ty as universe element) *)
  CPathLam (i, type_as_term glue_ty)

(* ─── Decidable typechecking entry point ───────────────────────────── *)

(* For the dispatcher: check whether two surface types should be
 * considered cubically equal. This handles the case where two
 * surface types are equipped with a cubical path between them. *)

let decidable_equal_cubical (a : ctype) (b : ctype) : bool =
  ctype_equal a b
