(* cubical.ml — Cubical Type Theory fragment for Yon.
 *
 * Implements the (∞,1)-decidable layer of the federation, per
 * Cohen-Coquand-Huber-Mörtberg 2016 "Cubical Type Theory: a
 * constructive interpretation of the univalence axiom."
 *
 * The cubical layer provides:
 *
 *   1. The interval I with endpoints 0 and 1, and connections
 *      (min, max, negation) for face formulas.
 *   2. Path types Path A x y, with path abstraction <i> t and
 *      path application p @ i.
 *   3. Composition: comp A φ u u_0 fills the cube whose sides
 *      agree on the face formula φ.
 *   4. Homogeneous composition (hcomp), a special case for fixed type.
 *   5. Glue types Glue [φ ↦ (T, e)] A for univalence: a type that
 *      agrees with T on φ and with A elsewhere via equivalence e.
 *   6. Transport: transp A i a, the iterated composition along a
 *      path of types.
 *   7. Higher Inductive Types (HIT): quotients, suspensions, circle,
 *      defined by point constructors and path constructors.
 *
 * For Yon, the cubical layer handles:
 *   - Identity types between values of base types (text, number, ...).
 *   - Univalence-via-equivalence between places that are R_Yon Family-4
 *     equivalent (delegated to CATT_R_Yon for actual signature check).
 *   - Quotient types (e.g., Currency / equivalent_currency_set).
 *
 * The cubical fragment is decidable because cubical type checking is
 * decidable (the original CCHM result). The composition and glue
 * operations all reduce to canonical forms.
 *)

open Surface_ast

(* ─── The interval ─────────────────────────────────────────────────── *)

(* The interval I has two endpoints, 0 and 1. Interval expressions are
 * built from variables, endpoints, and connections (min ⊓, max (+),
 * and negation ~i which sends 0 ↔ 1).
 *)

type interval =
  | I0                                  (* the endpoint 0 *)
  | I1                                  (* the endpoint 1 *)
  | IVar of string                      (* an interval variable i *)
  | IMin of interval * interval         (* i ⊓ j: minimum *)
  | IMax of interval * interval         (* i (+) j: maximum *)
  | INeg of interval                    (* ~i: 1 - i *)

let rec interval_to_string (i : interval) : string =
  match i with
  | I0 -> "0"
  | I1 -> "1"
  | IVar x -> x
  | IMin (a, b) -> "(" ^ interval_to_string a ^ " ⊓ " ^ interval_to_string b ^ ")"
  | IMax (a, b) -> "(" ^ interval_to_string a ^ " (+) " ^ interval_to_string b ^ ")"
  | INeg a -> "~" ^ interval_to_string a

(* Normalize an interval expression to a canonical form. The cubical
 * algebra is a free distributive lattice with negation generated by
 * the interval variables. *)

let rec normalize_interval (i : interval) : interval =
  match i with
  | I0 | I1 | IVar _ -> i
  | INeg I0 -> I1
  | INeg I1 -> I0
  | INeg (INeg a) -> normalize_interval a
  | INeg a -> INeg (normalize_interval a)
  | IMin (I0, _) | IMin (_, I0) -> I0
  | IMin (I1, b) -> normalize_interval b
  | IMin (a, I1) -> normalize_interval a
  | IMin (a, b) when a = b -> normalize_interval a
  | IMin (a, b) -> IMin (normalize_interval a, normalize_interval b)
  | IMax (I1, _) | IMax (_, I1) -> I1
  | IMax (I0, b) -> normalize_interval b
  | IMax (a, I0) -> normalize_interval a
  | IMax (a, b) when a = b -> normalize_interval a
  | IMax (a, b) -> IMax (normalize_interval a, normalize_interval b)

(* Equality on intervals after normalization. *)
let interval_equal (i1 : interval) (i2 : interval) : bool =
  normalize_interval i1 = normalize_interval i2

(* Substitute an interval variable in an interval expression. *)
let rec subst_interval (var : string) (replacement : interval) (i : interval) : interval =
  match i with
  | I0 | I1 -> i
  | IVar x -> if x = var then replacement else i
  | IMin (a, b) -> IMin (subst_interval var replacement a,
                         subst_interval var replacement b)
  | IMax (a, b) -> IMax (subst_interval var replacement a,
                         subst_interval var replacement b)
  | INeg a -> INeg (subst_interval var replacement a)

(* ─── Face formulas ────────────────────────────────────────────────── *)

(* A face formula φ is a disjunction of conjunctions of atomic faces
 * of the form (i = 0) or (i = 1). It identifies a sub-cube of the
 * n-cube on which a partial element is defined.
 *
 * We represent a face as a list of atoms, and a formula as a list
 * of faces (disjunction).
 *)

type face_atom = string * bool         (* (i, b): i = if b then 1 else 0 *)
type face = face_atom list             (* conjunction *)
type face_formula = face list          (* disjunction *)

let face_is_consistent (f : face) : bool =
  (* No variable assigned both 0 and 1. *)
  let rec check seen = function
    | [] -> true
    | (x, b) :: rest ->
        (match List.assoc_opt x seen with
         | Some b' when b' <> b -> false
         | _ -> check ((x, b) :: seen) rest)
  in
  check [] f

(* Evaluate a face under an interval substitution. *)
let face_holds (f : face) (sub : (string * interval) list) : bool =
  List.for_all
    (fun (var, expected_b) ->
       match List.assoc_opt var sub with
       | Some I0 -> not expected_b
       | Some I1 -> expected_b
       | _ -> false)
    f

let formula_holds (phi : face_formula) (sub : (string * interval) list) : bool =
  List.exists (fun f -> face_holds f sub) phi

(* ─── Cubical types ────────────────────────────────────────────────── *)

(* The syntax of cubical types extends ordinary types with:
 *   - Path A x y: identity type between x and y in A
 *   - Glue: glue type for univalence
 *   - HIT: higher inductive types
 *
 * For interoperation with the surface language, we wrap a surface
 * ty in CTBase and add cubical-specific constructors.
 *)

type ctype =
  | CTBase of ty                                          (* a surface type *)
  | CTPath of ctype * cterm * cterm                       (* Path A x y *)
  | CTGlue of ctype * face_formula * (ctype * cterm) list (* Glue [φ ↦ (T, e)] A *)
  | CTQuotient of ctype * (cterm * cterm) list            (* A / ~ via path constructors *)
  | CTHIT of string * cterm list                          (* user-defined HIT *)

and cterm =
  | CVar of string                                        (* a term variable *)
  | CPathLam of string * cterm                            (* <i> t — path abstraction *)
  | CPathApp of cterm * interval                          (* p @ i — path application *)
  | CComp of ctype * face_formula
            * (string * face * cterm) list                (* partial sides u *)
            * cterm                                       (* base u_0 *)
  | CHComp of ctype * face_formula
             * (string * face * cterm) list * cterm       (* homogeneous comp *)
  | CGlueElem of cterm                                    (* glue-elem constructor *)
  | CUnglue of cterm                                      (* unglue projector *)
  | CTransport of (string * ctype) * cterm                (* transp <i>A i_0 t *)
  | CInhabitant of cterm                                  (* lift a non-cubical term *)
  | CHITConstr of string * cterm list                     (* HIT constructor application *)

(* ─── Path types and path computation ──────────────────────────────── *)

(* A path p : Path A x y has the property that p @ 0 = x and p @ 1 = y.
 * Path application reduces:
 *   (<i> t) @ 0 = t[i := 0]
 *   (<i> t) @ 1 = t[i := 1]
 *   (<i> t) @ j = t[i := j] for non-endpoint j
 *)

let rec subst_interval_in_cterm
    (var : string) (replacement : interval) (t : cterm) : cterm =
  match t with
  | CVar _ -> t
  | CPathLam (i, _body) when i = var ->
      (* Bound variable shadows — don't substitute inside. *)
      t
  | CPathLam (i, body) ->
      CPathLam (i, subst_interval_in_cterm var replacement body)
  | CPathApp (p, j) ->
      CPathApp (subst_interval_in_cterm var replacement p,
                subst_interval var replacement j)
  | CComp (ty, phi, sides, base) ->
      let ty' = subst_interval_in_ctype var replacement ty in
      let phi' = subst_interval_in_formula var replacement phi in
      let sides' = List.map
        (fun (i, face, term) ->
           (i, subst_interval_in_face var replacement face,
            subst_interval_in_cterm var replacement term))
        sides in
      let base' = subst_interval_in_cterm var replacement base in
      CComp (ty', phi', sides', base')
  | CHComp (ty, phi, sides, base) ->
      let ty' = subst_interval_in_ctype var replacement ty in
      let phi' = subst_interval_in_formula var replacement phi in
      let sides' = List.map
        (fun (i, face, term) ->
           (i, subst_interval_in_face var replacement face,
            subst_interval_in_cterm var replacement term))
        sides in
      let base' = subst_interval_in_cterm var replacement base in
      CHComp (ty', phi', sides', base')
  | CGlueElem t' -> CGlueElem (subst_interval_in_cterm var replacement t')
  | CUnglue t' -> CUnglue (subst_interval_in_cterm var replacement t')
  | CTransport ((i, ty), t') ->
      let ty' = if i = var then ty
                else subst_interval_in_ctype var replacement ty in
      CTransport ((i, ty'), subst_interval_in_cterm var replacement t')
  | CInhabitant _ -> t
  | CHITConstr (n, args) ->
      CHITConstr (n, List.map (subst_interval_in_cterm var replacement) args)

and subst_interval_in_ctype
    (var : string) (replacement : interval) (ty : ctype) : ctype =
  match ty with
  | CTBase _ -> ty
  | CTPath (a, x, y) ->
      CTPath (subst_interval_in_ctype var replacement a,
              subst_interval_in_cterm var replacement x,
              subst_interval_in_cterm var replacement y)
  | CTGlue (base, phi, partial) ->
      CTGlue (subst_interval_in_ctype var replacement base,
              subst_interval_in_formula var replacement phi,
              List.map (fun (t, e) ->
                (subst_interval_in_ctype var replacement t,
                 subst_interval_in_cterm var replacement e))
                partial)
  | CTQuotient (a, paths) ->
      CTQuotient (subst_interval_in_ctype var replacement a,
                  List.map (fun (x, y) ->
                    (subst_interval_in_cterm var replacement x,
                     subst_interval_in_cterm var replacement y))
                    paths)
  | CTHIT (n, args) ->
      CTHIT (n, List.map (subst_interval_in_cterm var replacement) args)

and subst_interval_in_face
    (var : string) (replacement : interval) (f : face) : face =
  (* Faces are atomic; if the bound var is mentioned, attempt to resolve. *)
  List.filter_map
    (fun (x, b) ->
       if x = var then
         match normalize_interval replacement with
         | I0 -> if b then None else Some (x, b) (* contradiction with i = 1? *)
         | I1 -> if b then Some (x, b) else None
         | _ -> Some (x, b)
       else Some (x, b))
    f

and subst_interval_in_formula
    (var : string) (replacement : interval) (phi : face_formula) : face_formula =
  List.map (subst_interval_in_face var replacement) phi

(* Path application — the key reduction rule of path types. *)
let path_app (p : cterm) (j : interval) : cterm =
  match p with
  | CPathLam (i, body) -> subst_interval_in_cterm i j body
  | _ -> CPathApp (p, j)

(* ─── Glue constructors and projectors ─────────────────────────────── *)

(* Constructors used by the composition rule below; defined here so
 * that reduce_comp can reference them. *)

let glue_type
    (base : ctype) (phi : face_formula)
    (partial : (ctype * cterm) list) : ctype =
  CTGlue (base, phi, partial)

let glue_elem (t : cterm) : cterm = CGlueElem t

let unglue (t : cterm) : cterm =
  match t with
  | CGlueElem inner -> inner
  | _ -> CUnglue t

(* ─── Composition operation ────────────────────────────────────────── *)

(* The composition operation comp A φ u u_0 has these reduction rules:
 *
 *   comp A 1 u u_0 = u[i := 1]
 *   comp A 0 u u_0 = u_0  (when φ is the always-false formula)
 *
 * Plus equations for specific types: comp at a Path type unfolds to
 * a nested composition, comp at a Glue type uses transport, etc.
 *
 * The full computation rules require recursion on the structure of
 * the type. For the prototype we handle the basic cases and leave
 * a structural fallback for the rest.
 *)

let rec reduce_comp (ty : ctype) (phi : face_formula)
                    (sides : (string * face * cterm) list)
                    (base : cterm) : cterm =
  match phi with
  | [] -> base                            (* empty disjunction = false *)
  | _ ->
      match ty with
      | CTPath (inner_ty, p_left, p_right) ->
          (* comp at Path type: build a path-abstraction whose body
           * is the composition in the inner type, with extended
           * boundary conditions from the path endpoints. *)
          let j = "_comp_j" in
          let extended_phi =
            phi @ [ [(j, false)]; [(j, true)] ] in
          let extended_sides =
            sides
            @ [ ("_pathbnd_l", [(j, false)], p_left);
                ("_pathbnd_r", [(j, true)], p_right) ] in
          let base_at_j = path_app base (IVar j) in
          CPathLam (j,
            reduce_comp inner_ty extended_phi extended_sides base_at_j)

      | CTGlue (base_ty, glue_phi, _partial_pairs) ->
          (* comp at Glue: compose along the base type, then re-glue
           * using the partial equivalences. *)
          let base_sides =
            List.map (fun (i, f, t) -> (i, f, unglue t)) sides in
          let base_u0 = unglue base in
          let combined_phi = phi @ glue_phi in
          let result_base = reduce_comp base_ty combined_phi base_sides base_u0 in
          CGlueElem result_base

      | CTQuotient (underlying_ty, _path_constructors) ->
          (* comp at quotient: compose in the underlying type, then
           * project back into the quotient via the canonical
           * embedding inj. *)
          let inner_comp = reduce_comp underlying_ty phi sides base in
          CHITConstr ("inj", [inner_comp])

      | CTHIT (hit_name, _params) ->
          (* comp at a HIT type: consult the HIT signature to dispatch
           * on the constructor of the base term.
           *
           * Semantics (prototype):
           *   - If base is CHITConstr (cname, cargs) where cname is a
           *     POINT constructor with NO arguments (a "vertex" like
           *     S¹.base or S².base): the composition is the constant
           *     point itself. Composing over a constant produces the
           *     constant.
           *   - If base is CHITConstr with arguments: recursively
           *     compose each argument; reassemble.
           *   - If base is a PATH constructor: leave as canonical form
           *     (full path composition is the heart of cubical
           *     reduction, beyond the prototype's scope).
           *   - If signature not found or base shape unrecognized:
           *     fall back to canonical CComp.
           *)
          (match Hit_env.lookup Hit_env.builtin_env hit_name with
           | None -> CComp (ty, phi, sides, base)
           | Some sig_ ->
               match base with
               | CHITConstr (cname, []) ->
                   (* Zero-arity point constructor: comp is the point. *)
                   if List.exists (fun pc -> pc.Hit_env.pc_name = cname)
                                  sig_.Hit_env.hit_points
                   then base
                   else CComp (ty, phi, sides, base)
               | CHITConstr (cname, cargs) ->
                   (* Multi-arity point constructor: comp each arg.
                    * Each arg is itself a cterm; we conservatively
                    * recurse only if the arg type can be inferred as
                    * the SAME HIT (self-referential). Without full
                    * dependent reduction we just recompose. *)
                   if List.exists (fun pc -> pc.Hit_env.pc_name = cname)
                                  sig_.Hit_env.hit_points
                   then CHITConstr (cname, cargs)
                   else CComp (ty, phi, sides, base)
               | _ -> CComp (ty, phi, sides, base))

      | CTBase t ->
          (* comp at primitive: composition over a constant type is
           * the identity. For user types we treat the same way at
           * the prototype level. *)
          (match t with
           | Surface_ast.TyPrim _ | Surface_ast.TyPrimIn _ -> base
           | Surface_ast.TyUser _ -> base
           | _ -> CComp (ty, phi, sides, base))

(* Homogeneous composition: type doesn't vary along the dimension. *)
let reduce_hcomp (ty : ctype) (phi : face_formula)
                 (sides : (string * face * cterm) list)
                 (base : cterm) : cterm =
  match phi with
  | [] -> base
  | _ -> CHComp (ty, phi, sides, base)

(* ─── Transport ────────────────────────────────────────────────────── *)

(* transp <i> A i_0 t transports t along the line of types A(i).
 * Key reduction:
 *   transp <i> A 0 t : A(1)  with t : A(0)
 *
 * For specific A:
 *   transp <i> (Path B x y) i_0 p = ...     (composition equation)
 *   transp <i> (X -> Y) i_0 f = ...           (function transport)
 *   transp <i> (CTBase T) i_0 t = t          (constant: identity)
 *)

let reduce_transport ((i, ty) : string * ctype) (t : cterm) : cterm =
  match ty with
  | CTBase _ -> t                            (* constant type: identity *)
  | CTPath (a, x, y) ->
      (* transp <i> (Path A x y) t reduces to a comp expression.
       * In CCHM:
       *   transp <i> (Path A x y) t =
       *     <j> comp A (j=0 -> x (+) j=1 -> y) (t @ j)
       *)
      let fresh_j = "_transp_j" in
      CPathLam (fresh_j,
        reduce_comp a
          [[(fresh_j, false)]; [(fresh_j, true)]]
          [(i, [(fresh_j, false)], x);
           (i, [(fresh_j, true)], y)]
          (path_app t (IVar fresh_j)))
  | CTGlue (_base, _phi, partial) ->
      (* Univalence as a COMPUTATION RULE.
       *
       * transp <i> (Glue [(i=0)↦(A,e), (i=1)↦(B,id)] B) t
       *   reduces to e.fun(t)
       *
       * i.e., transporting along a path built from an equivalence
       * e : A ~= B applies the forward map of e. This is the
       * COMPUTATIONAL content of univalence — not an axiom, a
       * reduction rule of the cubical machine.
       *
       * For a generic Glue, we apply the partial equivalence on the
       * face (i=0) — taking the first partial pair as the relevant
       * equivalence (this is the standard ua(e) shape). *)
      (match partial with
       | (_t_ty, equiv) :: _ ->
           (* equiv is a cterm of type T ~= A; apply its forward map
            * to t. We model equiv-application as CHITConstr "fwd"
            * since we don't have a first-class App at this layer. *)
           CHITConstr ("__equiv_fwd", [equiv; t])
       | [] -> t)
  | _ -> CTransport ((i, ty), t)

(* ─── Glue types and univalence ────────────────────────────────────── *)

(* Glue [φ ↦ (T, e)] A is a type that equals T on the face φ and A
 * everywhere else, where e is an equivalence T ~= A. Its inhabitants
 * are constructed by glue-elem: given t : T on φ and a : A in general
 * agreeing via e, glue-elem(t, a) : Glue.
 *
 * For univalence: given an equivalence e : A ~= B, we form the
 * line of types <i> Glue [i=0 -> (A, e), i=1 -> (B, id)] B, which
 * gives a path A == B.
 *)

(* ─── Higher Inductive Types ───────────────────────────────────────── *)

(* HITs are inductive types with two kinds of constructors:
 *   - Point constructors: usual constructors producing elements
 *   - Path constructors: producing equalities between elements
 *
 * Examples:
 *   - S¹: point base, path loop : base = base
 *   - Quotient A R: inj : A -> A/R, quot : forallx y, R x y -> inj x = inj y
 *   - Suspension A: north, south, merid : A -> north = south
 *
 * For Yon, HITs are declared via sum types extended with path equations.
 * We represent a HIT signature here and check inhabitants against it.
 *)

type hit_signature = {
  hit_name : string;
  hit_points : (string * ctype list) list;     (* name + arg types *)
  hit_paths : (string * (string * ctype) list  (* params *)
              * cterm * cterm) list;            (* endpoints *)
}

let hit_constructor_arity (sig_ : hit_signature) (cname : string) : int option =
  (* First check point constructors *)
  match List.assoc_opt cname sig_.hit_points with
  | Some args -> Some (List.length args)
  | None ->
      match List.find_opt (fun (n, _, _, _) -> n = cname) sig_.hit_paths with
      | Some (_, params, _, _) -> Some (List.length params)
      | None -> None

(* ─── Decidable equality on cubical terms ──────────────────────────── *)

(* Cubical type checking is decidable because:
 *   1. Path application reduces by interval substitution
 *   2. Composition reduces by structural rules on the type
 *   3. Transport reduces to identity on constant types and recursion
 *      on indexed types
 *   4. Glue terms are normalized by the boundary conditions
 *
 * We implement a normalizer and a structural-equality comparator.
 *)

let rec normalize_cterm (t : cterm) : cterm =
  match t with
  | CVar _ -> t
  | CPathLam (i, body) -> CPathLam (i, normalize_cterm body)
  | CPathApp (p, j) ->
      let p' = normalize_cterm p in
      let j' = normalize_interval j in
      (match p' with
       | CPathLam (i, body) ->
           normalize_cterm (subst_interval_in_cterm i j' body)
       | _ -> CPathApp (p', j'))
  | CComp (ty, phi, sides, base) ->
      let result = reduce_comp ty phi sides base in
      (match result with
       | CComp _ -> result                 (* couldn't reduce further *)
       | other -> normalize_cterm other)
  | CHComp (ty, phi, sides, base) ->
      let result = reduce_hcomp ty phi sides base in
      (match result with
       | CHComp _ -> result
       | other -> normalize_cterm other)
  | CGlueElem t' -> CGlueElem (normalize_cterm t')
  | CUnglue t' ->
      let t'' = normalize_cterm t' in
      (match t'' with
       | CGlueElem inner -> inner
       | _ -> CUnglue t'')
  | CTransport ((i, ty), t') ->
      let result = reduce_transport (i, ty) (normalize_cterm t') in
      (match result with
       | CTransport _ -> result
       | other -> normalize_cterm other)
  | CInhabitant _ -> t
  | CHITConstr (n, args) -> CHITConstr (n, List.map normalize_cterm args)

let rec cterm_equal (t1 : cterm) (t2 : cterm) : bool =
  let n1 = normalize_cterm t1 in
  let n2 = normalize_cterm t2 in
  cterm_syntactic_equal n1 n2

and cterm_syntactic_equal (t1 : cterm) (t2 : cterm) : bool =
  match t1, t2 with
  | CVar x, CVar y -> x = y
  | CPathLam (i, b1), CPathLam (j, b2) ->
      (* alpha-equivalent: rename j to i in b2 and compare. *)
      let b2' = subst_interval_in_cterm j (IVar i) b2 in
      cterm_syntactic_equal b1 b2'
  | CPathApp (p1, j1), CPathApp (p2, j2) ->
      cterm_syntactic_equal p1 p2 && interval_equal j1 j2
  | CGlueElem t1, CGlueElem t2 -> cterm_syntactic_equal t1 t2
  | CUnglue t1, CUnglue t2 -> cterm_syntactic_equal t1 t2
  | CTransport ((i1, ty1), t1), CTransport ((i2, ty2), t2) ->
      let ty2' = subst_interval_in_ctype i2 (IVar i1) ty2 in
      ctype_equal ty1 ty2' && cterm_syntactic_equal t1 t2
  | CInhabitant _, CInhabitant _ -> t1 = t2
  | CHITConstr (n1, a1), CHITConstr (n2, a2) ->
      n1 = n2
      && List.length a1 = List.length a2
      && List.for_all2 cterm_syntactic_equal a1 a2
  | CComp _, CComp _ | CHComp _, CHComp _ ->
      t1 = t2                                (* structural after normalization *)
  | _, _ -> false

and ctype_equal (a : ctype) (b : ctype) : bool =
  match a, b with
  | CTBase t1, CTBase t2 ->
      Catt_r_yon.ty_structural_eq t1 t2
  | CTPath (a1, x1, y1), CTPath (a2, x2, y2) ->
      ctype_equal a1 a2
      && cterm_equal x1 x2
      && cterm_equal y1 y2
  | CTGlue (a1, phi1, p1), CTGlue (a2, phi2, p2) ->
      ctype_equal a1 a2
      && phi1 = phi2
      && List.length p1 = List.length p2
      && List.for_all2
           (fun (t1, e1) (t2, e2) ->
              ctype_equal t1 t2 && cterm_equal e1 e2)
           p1 p2
  | CTQuotient (a1, ps1), CTQuotient (a2, ps2) ->
      ctype_equal a1 a2
      && List.length ps1 = List.length ps2
      && List.for_all2
           (fun (x1, y1) (x2, y2) ->
              cterm_equal x1 x2 && cterm_equal y1 y2)
           ps1 ps2
  | CTHIT (n1, a1), CTHIT (n2, a2) ->
      n1 = n2
      && List.length a1 = List.length a2
      && List.for_all2 cterm_equal a1 a2
  | _, _ -> false

(* ─── Univalence ───────────────────────────────────────────────────── *)

(* Univalence says: equality of types is equivalent to equivalence of
 * types. (A == B) ~= (A ~= B). The computational content via Glue is:
 *
 *   ua : (A ~= B) -> (A == B)
 *   ua e = <i> Glue [i=0 -> (A, e), i=1 -> (B, id)] B
 *
 * We expose a helper that constructs this path given an equivalence.
 *)

(* ua : (A ~= B) -> Path U A B
 *
 * Computational content (CCHM):
 *   ua e = <i> Glue [(i=0) ↦ (A, e), (i=1) ↦ (B, id)] B
 *
 * The resulting path, at endpoint i=0, is A (via the equivalence e);
 * at endpoint i=1, is B (via identity). At all interior points i it
 * is the Glue type that mediates between them.
 *
 * We return a path *between types* — represented as a path-abstraction
 * whose body is a Glue type lifted to the term layer via CInhabitant.
 * This is the standard way cubical implementations encode "paths in
 * the universe": types appear as inhabitants of a type universe, and
 * a path between types is a function from I to that universe.
 *)

(* Helper: identity equivalence on a type A.
 *
 * An equivalence A ~= B in CCHM is a pair (f, isEquiv f). The
 * identity equivalence is (id_A, id-is-equiv). We don't track the
 * "isEquiv" proof at the prototype level — it's a coherence witness.
 *)
let id_equiv (_a : ctype) : cterm =
  CVar "__id"   (* the identity function as the underlying map *)

(* Encode a type-as-term for the universe layer.
 *
 * In a full cubical implementation, types live in a universe `U` and
 * are themselves terms of type U. The constructor CTypeAsTerm
 * promotes a type to a term inhabiting the universe. We use
 * CInhabitant for this lift; downstream code recognizes it as a
 * universe element via tagged pattern matching.
 *)
let type_as_term (t : ctype) : cterm =
  CInhabitant (
    match t with
    | CTBase _ -> CVar "__type_base"
    | CTPath _ -> CVar "__type_path"
    | CTGlue _ -> CVar "__type_glue"
    | CTQuotient _ -> CVar "__type_quot"
    | CTHIT (n, _) -> CVar ("__type_hit_" ^ n)
  )

let ua (a : ctype) (b : ctype) (e : cterm) : cterm =
  let i = "_ua_i" in
  (* Build the Glue type:
   *   Glue [(i=0) ↦ (A, e), (i=1) ↦ (B, id_B)] B
   *
   * As ctype: CTGlue base phi partial
   * where phi = [(i=0); (i=1)] and partial pairs (A, e) and (B, id).
   *)
  let glue_ty = CTGlue (
    b,                                    (* base type B *)
    [ [(i, false)];                       (* face i=0 *)
      [(i, true)] ],                      (* face i=1 *)
    [ (a, e);                             (* on i=0: type A with equiv e *)
      (b, id_equiv b) ]                   (* on i=1: type B with id *)
  ) in
  (* The result is a path: <i> (glue_ty as universe element) *)
  CPathLam (i, type_as_term glue_ty)

(* ─── Decidable typechecking entry point ───────────────────────────── *)

(* For the dispatcher: check whether two surface types should be
 * considered cubically equal. This handles the case where two
 * surface types are equipped with a cubical path between them. *)

let decidable_equal_cubical (a : ctype) (b : ctype) : bool =
  ctype_equal a b
