(* site.ml — the world reified as a Grothendieck site C(W), and its topology J.
 *
 * A world W is the base category (the site) on which its places are presheaves
 * P : C(W)^op -> Type. The Grothendieck topology J(W) is NOT declared by hand
 * on a place; it is GENERATED by the operations that build the world:
 *
 *   world C = A + B          (coproduct)     -> the injections cover disjointly
 *   world Q = W / Rel        (quotient)      -> the R-classes cover W
 *   world Q = coeq(f, g)     (coequalizer)   -> the coequalizing family covers
 *   world S subset of V      (dense inclusion)-> S <-> V generates a cover
 *
 * The categorical PRODUCT A * B is a limit, not a colimit, and does not cover:
 * it contributes no generator. A bare world (only `Code is X`, no construction)
 * has no generators: J is trivial, Sh(C(W)) = PSh(C(W)), and every place is a
 * sheaf vacuously.
 *
 * The topologies on a fixed category form a COMPLETE lattice (arbitrary meets
 * exist, hence all joins). J(W) is the join, in that lattice, of the elementary
 * topology each construction generates. We represent J intensionally by its
 * generators (`get_J`); the join is their union. This module is the single home
 * for reading J off a world; the sheaf predicate (a later step) consumes it. *)

module C = Ast

(* J(W): the generators of the Grothendieck topology of the site C(W). *)
let get_J (w : C.world_decl) : C.site_generator list = w.C.w_generators

(* A site is trivial when it has no covering generators: then Sh = PSh and every
 * presheaf is a sheaf vacuously. This is the case that must stay inert, and for
 * the right reason — not because a check was skipped. *)
let is_trivial (w : C.world_decl) : bool = get_J w = []

(* Two worlds carry the same topology when their generator SETS coincide — the
 * join in the lattice is order- and multiplicity-insensitive (idempotent,
 * commutative). This is the equality of J as a topology, coarser than the
 * structural [world_equal] (which also compares names and object lists). *)
let same_topology (w1 : C.world_decl) (w2 : C.world_decl) : bool =
  let norm w = List.sort_uniq compare (get_J w) in
  norm w1 = norm w2
