(* subst.ml — capture-avoiding substitution
 *
 * Implements t[x ↦ u] for Yon Core terms.
 *
 * The hard case is substitution under a binder: lambday:T.body where we're
 * computing (lambday:T.body)[x ↦ u]. Three sub-cases:
 *   1. x = y      — the binder shadows the substitution; result is the lambda unchanged.
 *   2. y not-in FV(u)  — the binder doesn't capture; recurse into body.
 *   3. y in FV(u)  — capture would occur; alpha-rename y to fresh, then recurse.
 *
 * Family 1 of R_Yon (alpha-renaming) is implemented implicitly through
 * this on-the-fly fresh naming. After substitution, the resulting term
 * is alpha-equivalent to what the math says — and the fresh names
 * generated by Ast.fresh_var keep things distinct.
 *)

open Ast

let rec subst x u t =
  match t with
  | Var y -> if x = y then u else t
  | Lam (y, ty, body) ->
      if x = y then t                                   (* case 1: shadowed *)
      else if not (let module S = Set.Make (String) in S.mem y (free_vars u))
      then Lam (y, ty, subst x u body)                  (* case 2: safe *)
      else                                              (* case 3: rename *)
        let module S = Set.Make (String) in
        let avoid = S.union (free_vars body) (free_vars u) in
        let avoid = S.add x avoid in
        let y' = fresh_var avoid in
        let body' = subst y (Var y') body in
        Lam (y', ty, subst x u body')
  | App (f, a) -> App (subst x u f, subst x u a)
  | Place _ -> t                                        (* place declarations are closed *)
  | Reduction r ->
      let handlers' = List.map (subst_handler x u) r.r_handlers in
      Reduction { r with r_handlers = handlers' }
  | Scope (s, body) -> Scope (s, subst x u body)
  | With (r, body) ->
      (* If we are substituting x with a Var "realname" and x = r (the name of
       * the reduction inside `with r { ... }`), then r must become "realname".
       * This enables the higher-order inlining of a reduction handle. *)
      let r' = match u with
        | Var realname when x = r -> realname
        | _ -> r
      in
      With (r', subst x u body)
  | Emit t' -> Emit (subst x u t')
  | Refl t' -> Refl (subst x u t')
  | J (mx, ty, c, d, p, b) ->
      (* The motive binder mx shadows like a Lam binder. For substitution
       * in c we treat it via the standard shadow rule, but at this level
       * we conservatively substitute in all sub-terms; the motive is
       * structurally a Lam so its own internal shadowing is handled. *)
      J (mx, ty, subst x u c, subst x u d, subst x u p, subst x u b)
  | Pair (a, b) -> Pair (subst x u a, subst x u b)
  | Fst t' -> Fst (subst x u t')
  | Snd t' -> Snd (subst x u t')
  | StreamCons (h, k) -> StreamCons (subst x u h, subst x u k)
  | Unit -> Unit

(* Substitute through a handler clause.
 * Handler parameters bind names in the body, so the same shadowing
 * logic as Lam applies, but for multiple binders.
 *)
and subst_handler x u h =
  let module S = Set.Make (String) in
  let bound_names = List.map fst h.hc_params in
  (* If x is bound by the handler parameters, no substitution happens in the body. *)
  if List.mem x bound_names then h
  else
    (* Check whether any handler parameter would capture a variable in u. *)
    let fv_u = free_vars u in
    let needs_rename =
      List.exists (fun (p, _) -> S.mem p fv_u) h.hc_params
    in
    if not needs_rename then
      { h with hc_body = subst x u h.hc_body }
    else
      (* Alpha-rename each conflicting parameter to fresh. *)
      let avoid = ref (S.union (free_vars h.hc_body) fv_u) in
      avoid := S.add x !avoid;
      let renamings = ref [] in
      let params' = List.map (fun (p, ty) ->
        if S.mem p fv_u then begin
          let p' = fresh_var !avoid in
          avoid := S.add p' !avoid;
          renamings := (p, p') :: !renamings;
          (p', ty)
        end else (p, ty)
      ) h.hc_params in
      (* Apply all renamings to the body. *)
      let body_renamed = List.fold_left
        (fun b (old_name, new_name) -> subst old_name (Var new_name) b)
        h.hc_body !renamings in
      { h with
        hc_params = params';
        hc_body = subst x u body_renamed }
