(* SPDX-License-Identifier: AGPL-3.0-only *)
(* Copyright (c) 2026 Antonio Mennillo <antoniomennillo87@gmail.com> *)
(* subst.ml — capture-avoiding substitution
 *
 * Implements t[x ↦ u] for Yon Core terms.
 *
 * The hard case is substitution under a binder: lambday:T.body where we're
 * computing (lambday:T.body)[x ↦ u]. Three sub-cases:
 *   1. x = y      — the binder shadows the substitution; result is the lambda unchanged.
 *   2. y not-in FV(u)  — the binder doesn't capture; recurse into body.
 *   3. y in FV(u)  — capture would occur; alpha-rename y to fresh, then recurse.
 *
 * alpha-renaming in R_Yon is implemented implicitly through
 * this on-the-fly fresh naming. After substitution, the resulting term
 * is alpha-equivalent to what the math says — and the fresh names
 * generated by Ast.fresh_var keep things distinct.
 *)

open Ast

let rec subst x u t =
  match t with
  | Var y -> if x = y then u else t
  | Lam (y, ty, body) ->
      if x = y then t                                   (* case 1: shadowed *)
      else if not (let module S = Set.Make (String) in S.mem y (free_vars u))
      then Lam (y, ty, subst x u body)                  (* case 2: safe *)
      else                                              (* case 3: rename *)
        let module S = Set.Make (String) in
        let avoid = S.union (free_vars body) (free_vars u) in
        let avoid = S.add x avoid in
        let y' = fresh_var avoid in
        let body' = subst y (Var y') body in
        Lam (y', ty, subst x u body')
  | App (f, a) -> App (subst x u f, subst x u a)
  | Place _ | World _ -> t                              (* place/world declarations are closed *)
  | Reduction r ->
      let handlers' = List.map (subst_handler x u) r.r_handlers in
      Reduction { r with r_handlers = handlers' }
  | Scope (s, body) -> Scope (s, subst x u body)
  | Emit t' -> Emit (subst x u t')
  | Refl t' -> Refl (subst x u t')
  | J (mx, ty, c, d, p, b) ->
      (* The motive binder mx shadows like a Lam binder. For substitution
       * in c we treat it via the standard shadow rule, but at this level
       * we conservatively substitute in all sub-terms; the motive is
       * structurally a Lam so its own internal shadowing is handled. *)
      J (mx, ty, subst x u c, subst x u d, subst x u p, subst x u b)
  | Pair (a, b) -> Pair (subst x u a, subst x u b)
  | Fst t' -> Fst (subst x u t')
  | Snd t' -> Snd (subst x u t')
  | StreamCons (h, k) -> StreamCons (subst x u h, subst x u k)
  | Unit -> Unit
  | PLam (i, t') -> PLam (i, subst x u t')
  | PApp (p, r) -> PApp (subst x u p, r)
  | Transp ((i, a), t') -> Transp ((i, a), subst x u t')
  | Comp (ty, phi, sides, base) ->
      Comp (ty, phi, List.map (fun (i, f, t') -> (i, f, subst x u t')) sides, subst x u base)
  | HComp (ty, phi, sides, base) ->
      HComp (ty, phi, List.map (fun (i, f, t') -> (i, f, subst x u t')) sides, subst x u base)
  | GlueElem (phi, t', a') -> GlueElem (phi, subst x u t', subst x u a')
  | Unglue t' -> Unglue (subst x u t')
  | HITElim (branches, scrut) ->
      (* A branch (n, vars, b) binds the payload variables [vars] over [b],
       * exactly like a handler clause binds its params. Substitution must be
       * capture-avoiding HERE TOO: if x is not shadowed by [vars] but some
       * v ∈ vars is free in u, naively recursing into b would CAPTURE v.
       * Route through the single multi-binder helper so this binder is
       * capture-proof by construction, like Lam and the handler clauses. *)
      HITElim
        (List.map (fun (n, vars, b) ->
           let (vars', b') = subst_under_binders x u vars b in
           (n, vars', b')) branches,
         subst x u scrut)
  | HITConstr (n, args) -> HITConstr (n, List.map (subst x u) args)

(* Substitute through a handler clause.
 * Handler parameters bind names in the body, so the same shadowing
 * logic as Lam applies, but for multiple binders.
 *)
and subst_handler x u h =
  (* Handler parameters bind names over the body; the same multi-binder
   * shadowing logic as HIT-eliminator branches applies. Single source of
   * truth: subst_under_binders. The param TYPES are not term-substituted
   * (unchanged from the original behaviour); only names can be freshened,
   * positionally, so re-pairing with the original types is order-correct. *)
  let names = List.map fst h.hc_params in
  let tys   = List.map snd h.hc_params in
  let (names', body') = subst_under_binders x u names h.hc_body in
  { h with hc_params = List.combine names' tys; hc_body = body' }

(* Capture-avoiding substitution under a LIST of binders [vars] that scope over
 * [body], computing  body[x ↦ u]  with [vars] in scope. Generalizes the Lam
 * case-3 rename to many simultaneous binders, and is THE shared routine for
 * every multi-binder form (handler clauses, HIT-eliminator branches):
 *   - x ∈ vars            → x is shadowed; body is left untouched.
 *   - no v ∈ vars in FV(u)→ no capture possible; recurse into body.
 *   - some v ∈ vars in FV(u) → those v would capture; alpha-rename each such v
 *                              to a fresh name (avoiding x, FV(body), FV(u) and
 *                              the names already chosen), rewrite body, then
 *                              substitute. Capture-proof by construction.
 * Renaming is positional (List.map preserves order), so a caller carrying
 * per-binder annotations can re-pair them with [vars'] safely. *)
and subst_under_binders x u vars body =
  let module S = Set.Make (String) in
  if List.mem x vars then (vars, body)
  else
    let fv_u = free_vars u in
    if not (List.exists (fun v -> S.mem v fv_u) vars)
    then (vars, subst x u body)
    else begin
      let avoid = ref (S.add x (S.union (free_vars body) fv_u)) in
      let renamings = ref [] in
      let vars' = List.map (fun v ->
        if S.mem v fv_u then begin
          let v' = fresh_var !avoid in
          avoid := S.add v' !avoid;
          renamings := (v, v') :: !renamings;
          v'
        end else v) vars in
      let body_renamed = List.fold_left
        (fun b (oldn, newn) -> subst oldn (Var newn) b)
        body !renamings in
      (vars', subst x u body_renamed)
    end

(* ─────────────────────────────────────────────────────────────────────────
 * subst_term_in_ty x u t  =  t[x := u]  where x is a TERM variable occurring
 * inside the term-carrying type formers. In Yon a type depends on a term only
 * through TyId (its endpoints), TyEl (its code), and TyGlue (its equivalences);
 * everywhere else the recursion is structural. This is the type-level dependent
 * substitution the checker was missing — "motive application": if a motive's
 * body is a dependent type C(x), then C(arg) = subst_term_in_ty x arg C_body.
 * Capture-avoiding at the dependent binders TyPi / TySigma.
 * ───────────────────────────────────────────────────────────────────────── *)
let rec subst_term_in_ty (x : string) (u : term) (t : ty) : ty =
  let module S = Set.Make (String) in
  match t with
  | TyType _ | TyDirUniverse _ | TyPlace _ -> t
  | TyArrow (a, b) ->
      TyArrow (subst_term_in_ty x u a, subst_term_in_ty x u b)
  | TyStream a -> TyStream (subst_term_in_ty x u a)
  | TyId (a, t1, t2) ->
      TyId (subst_term_in_ty x u a, subst x u t1, subst x u t2)
  | TyEl c -> TyEl (subst x u c)
  | TyGlue (a, phi, pairs) ->
      TyGlue (subst_term_in_ty x u a, phi,
              List.map (fun (ty_i, e) ->
                (subst_term_in_ty x u ty_i, subst x u e)) pairs)
  | TyPathP ((i, a), l, r) ->
      (* i is an interval binder, not a term var; no capture on x *)
      TyPathP ((i, subst_term_in_ty x u a), subst x u l, subst x u r)
  | TyPi (y, a, b) ->
      let a' = subst_term_in_ty x u a in
      if x = y then TyPi (y, a', b)                          (* binder shadows b *)
      else if not (S.mem y (free_vars u))
      then TyPi (y, a', subst_term_in_ty x u b)              (* no capture *)
      else                                                   (* rename y to fresh *)
        let avoid = S.add x (S.add y (free_vars u)) in
        let y' = fresh_var avoid in
        let b' = subst_term_in_ty y (Var y') b in
        TyPi (y', a', subst_term_in_ty x u b')
  | TySigma (y, a, b) ->
      let a' = subst_term_in_ty x u a in
      if x = y then TySigma (y, a', b)
      else if not (S.mem y (free_vars u))
      then TySigma (y, a', subst_term_in_ty x u b)
      else
        let avoid = S.add x (S.add y (free_vars u)) in
        let y' = fresh_var avoid in
        let b' = subst_term_in_ty y (Var y') b in
        TySigma (y', a', subst_term_in_ty x u b')
