/* SPDX-License-Identifier: AGPL-3.0-only */
/* Copyright (c) 2026 Antonio Mennillo <antoniomennillo87@gmail.com> */
/* Generate runtime/yon_curtis_canon.c: precomputed canon_map LUTs for the
 * fixed Curtis frame. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include "mmgroup_generators.h"
#include "xleech2_mphf.h"
#include "xleech2_coord.h"
#include "yon_curtis_frame.h"
typedef struct { uint64_t cls; uint32_t idx; } ci_t;
static int cmp(const void*a,const void*b){const ci_t*x=a,*y=b; if(x->cls!=y->cls)return(x->cls>y->cls)-(x->cls<y->cls); return(x->idx>y->idx)-(x->idx<y->idx);}
static uint32_t t2(uint32_t t){return t==0?0u:t==2?1u:t==3?2u:t==4?3u:0u;}
int main(void){
    uint32_t N=196560u;
    ci_t *ci=malloc((size_t)N*sizeof(ci_t));
    for(uint32_t i=0;i<N;i++){
        uint32_t v=(uint32_t)yon_mphf_unindex(i);
        uint64_t cls=0;
        for(uint32_t r=0;r<YON_CURTIS_FRAME_N;r++){uint32_t s=(v^YON_CURTIS_FRAME[r])&0x1FFFFFFu; cls=cls*4+t2(gen_leech2_type((uint64_t)s)&7);}
        ci[i].cls=cls; ci[i].idx=i;
    }
    qsort(ci,N,sizeof(ci_t),cmp);
    uint32_t *rep_idx=malloc((size_t)N*sizeof(uint32_t));
    uint32_t gi=0;
    while(gi<N){uint64_t c=ci[gi].cls; uint32_t r=ci[gi].idx; uint32_t gj=gi; while(gj<N&&ci[gj].cls==c){rep_idx[ci[gj].idx]=r;gj++;} gi=gj;}
    FILE*f=fopen("yon_curtis_canon.c","w");
    fprintf(f,"/* GENERATED by tools_gen_canon.c -- do not edit by hand.\n * Precomputed canon_map LUTs for the fixed Curtis frame. */\n#include <stdint.h>\n\n");
    fprintf(f,"const uint32_t YON_CURTIS_CANON_XC[%u] = {\n",N);
    for(uint32_t i=0;i<N;i++){fprintf(f,"0x%xu,",(uint32_t)yon_mphf_unindex(rep_idx[i])); if((i&15)==15)fputc('\n',f);}
    fprintf(f,"\n};\nconst uint32_t YON_CURTIS_CANON_IDX[%u] = {\n",N);
    for(uint32_t i=0;i<N;i++){fprintf(f,"%uu,",rep_idx[i]); if((i&15)==15)fputc('\n',f);}
    fprintf(f,"\n};\n");
    fclose(f);
    printf("wrote yon_curtis_canon.c\n");
    return 0;
}
