/* SPDX-License-Identifier: AGPL-3.0-only */
/* Copyright (c) 2026 Antonio Mennillo <antoniomennillo87@gmail.com> */
/* yon_rt.h — the runtime API that code generated by the Yon compiler calls
 * directly. A wrapper over xleech2_*.
 *
 * Cross-space single-process:
 *   - Multiple heaps identified by heap_id (uint32_t).
 *   - heap_id = 0 is __Default (back-compat with single-Space examples).
 *   - heap_id = 1..N are user-defined Spaces.
 *   - All heap_ids currently point to the same physical heap (semantic
 *     indexing). Later each heap_id will have its own separate yon_xheap_t,
 *     and eventually they will map to remote nodes.
 *
 * Section identity:
 *   yon_section_t = packed (heap_id << 32) | xcoord = uint64_t
 *   All APIs that receive/return sections use yon_section_t.
 *
 * ABI stability: these signatures are fixed to stay stable across levels. The
 * heap backend may change; the ABI toward the generated code does not.
 */

#ifndef YON_RT_H
#define YON_RT_H

#include "xleech2_coord.h"
#include "xleech2_heap.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Section identity (packed) ---- */

/* yon_section_t: a compact encoding of (heap_id, xcoord) as a uint64.
 *
 * Bit layout:
 *   [63..32] heap_id  (uint32_t)
 *   [31..0]  xcoord   (yon_xcoord_t = uint32_t)
 *
 * Invariant: heap_id=0 is __Default, always valid.
 * heap_id=YON_HEAP_ID_INVALID indicates an error.
 */
typedef uint64_t yon_section_t;

#define YON_HEAP_ID_DEFAULT  ((uint32_t)0)
#define YON_HEAP_ID_INVALID  ((uint32_t)0xFFFFFFFFu)
#define YON_SECTION_INVALID  ((yon_section_t)0xFFFFFFFFFFFFFFFFull)

/* Hybrid design:
 *
 * yon_section_t = u64 packed (heap_id : u32 | slot_index : u32).
 *
 * The low 32 bits are sequential arena slot_index values (0 .. N_SLOTS-1).
 * The external ABI stays identical (a packed opaque u64). */

static inline yon_section_t yon_section_pack(uint32_t heap_id,
                                              uint32_t slot_index) {
    return ((uint64_t)heap_id << 32) | (uint64_t)slot_index;
}

static inline uint32_t yon_section_heap(yon_section_t s) {
    return (uint32_t)(s >> 32);
}

/* Legacy name kept for compatibility: now returns the hybrid slot_index. */
static inline uint32_t yon_section_slot(yon_section_t s) {
    return (uint32_t)(s & 0xFFFFFFFFu);
}

/* Deprecated alias — transitional use. Previously this was xcoord. */
static inline uint32_t yon_section_xcoord(yon_section_t s) {
    return yon_section_slot(s);
}

/* ---- Lifecycle ---- */

/* The policy enum was removed semantically.
 *
 * The policy enum was an anti-pattern: 4 hardcoded values that pretended to
 * encode distributed semantics but were only opaque flags. The correct
 * distributed semantics lives in the geometric_morphism declared between
 * topoi, and the coordination shape is derived from its properties
 * (adjunction, exact f_star, exact f_lower_star).
 *
 * The symbols below remain as empty 0 definitions so as not to break includes
 * of legacy code that references them. They no longer have any effect on the
 * runtime. yon_rt_register_space_with_policy ignores the policy parameter and
 * behaves like yon_rt_register_space.
 *
 * To declare distributed semantics, use geom_morphism in the .yon. The policy
 * functionality is replaced by:
 *   - yon_rt_register_space_with_fold for the topos semilattice fold
 *   - yon_rt_register_geom_morphism for cross-space relations
 * The coordination shape is derived categorically by
 * yon_rt_derive_coordination_from_gm. */

/* Runtime initialization. Idempotent. */
void yon_rt_init(void);

/* Register a Space (a logical heap). Returns the assigned heap_id. Idempotent:
 * calling twice with the same name returns the same id.
 *
 * This function simply assigns an incremental heap_id to distinct names. Later
 * it will bind to a physical yon_xheap_t or to a remote node. */
uint32_t yon_rt_register_space(const char *name);

/* Register a Space with a declared semilattice fold. fold_name is a whitelist
 * (sum_f64, max_f64, min_f64, sum_i64, max_i64, min_i64, sum_vec_f64,
 * max_vec_f64, or_bitset).
 *
 * Runtime effect: the constructor __new_in_<S>_<P> emitted by the compiler
 * sees sd_fold declared and calls yon_rt_fold_named instead of yon_rt_new for
 * writes into the space. */
uint32_t yon_rt_register_space_with_fold(const char *name, const char *fold_name);

/* Look up a heap_id by name. Returns YON_HEAP_ID_INVALID if absent. */
uint32_t yon_rt_lookup_space(const char *name);

/* Reclaim a dropped Space: hand its heap's live arena back to the OS via
 * yon_xheap_drop. heap_id is an f64 (the IR's universal type). The compiler emits
 * this only where Space_liveness.check_drops has proven the Space dead downstream,
 * so it honors a compile-time decision and carries no runtime policy. Safe no-op
 * for an out-of-range id or a Space with no private heap. Returns heap_id as an
 * inert f64 (the drop statement's value). Observe drops via yon_xheap_drops(). */
double yon_rt_drop_space(double heap_id);

/* ---- Space death-watch (1.2 region-reaping; NOT a garbage collector) ----
 *
 * Automatic reclaim of a Space's WHOLE heap when all its statically NAMED
 * incoming communication arcs (the inter-Space graph in-degree, wire + import)
 * have closed, without an explicit `drop`. The compiler arms each watched Space
 * once at startup with yon_rt_space_expect_inputs(id, in_degree); every real arc
 * EOF calls yon_rt_space_input_closed(id); the last one reaps via the same
 * yon_xheap_drop primitive `drop X` uses. This counts a small named set of ARCS
 * at REGION granularity — no per-object refcount, no barrier, no tracing. */

/* Arm the death-watch for Space `id` with its static in-degree n. Only n > 0
 * arms it; n <= 0 leaves the Space unwatched. Safe no-op for an out-of-range id. */
void yon_rt_space_expect_inputs(uint32_t id, int32_t n);

/* Signal one named incoming arc of Space `id` has closed (clean EOF). Decrements
 * the armed count; reaps the whole Space heap exactly when it reaches 0, then
 * disarms. Idempotent no-op for an out-of-range, unwatched, or already-reaped
 * Space. Observe the reap via yon_xheap_drops(). */
void yon_rt_space_input_closed(uint32_t id);

/* ---- Place instance management ---- */

/* Allocate a new section in the given Space.
 *
 * heap_id: the heap to allocate in. Use YON_HEAP_ID_DEFAULT for single-Space.
 * payload_bytes: pointer to the raw field bytes in declaration order,
 *   contiguous.
 * n_bytes: total payload size.
 *
 * Returns: an opaque yon_section_t (i64) usable as a handle. Content-addressed
 * allocation: the same (heap_id, payload) -> the same section.
 */
yon_section_t yon_rt_new(uint32_t heap_id,
                          const void *payload_bytes,
                          uint32_t n_bytes);

/* Load a field from the section.
 *
 * sec: section handle (heap_id + xcoord packed)
 * offset: byte offset of the field in the payload (compile-time)
 * size: size of the field in bytes (typically 1/4/8)
 * out: output buffer, at least `size` bytes
 *
 * Returns: 0 on success, -1 if the section is invalid or the slot is empty.
 */
int yon_rt_field_load(yon_section_t sec, uint32_t offset,
                      uint32_t size, void *out);

/* Flatten a place into position-independent content bytes (the outbound half
 * of the cross-process wormhole). Writes the raw payload into out_buf and
 * returns the byte count, or -1 on error / if cap is too small. Rebuild with
 * yon_rt_new(consumer_heap, buf, n). All-scalar places only at this seal;
 * handle-valued fields are not yet followed. */
int32_t yon_rt_flatten(yon_section_t sec, void *out_buf, uint32_t cap);

/* ---- Wire DTO transport, seal 2: the recursive, length-prefixed frame ----
 *
 * Inline encoding, schema-driven, decided on paper (design-wire-dto.md). A
 * frame is [u32 schema_id][u32 payload_len][payload]; the payload concatenates
 * the field encodings in declaration order, positional, no per-field type tag
 * (the schema is nominal and known on both sides). Field encodings:
 *   - scalar: 8 raw bytes, no prefix (size known from the schema)
 *   - string: [u32 len][len bytes] (NUL excluded on the wire)
 * The frame-level schema_id is the single cross-process type guard: it finds
 * the descriptor and lets the consumer assert the shape it awaited, turning a
 * schema drift into a loud error instead of silent corruption. Length prefixes
 * are u32 native-endian: producer and consumer are the same build on one
 * machine for the shm wire, so no byte-swap; a fixed width keeps every read
 * trivially bounded (unlike a varint, which can run off a drifted frame).
 *
 * Both the producer pump and the consumer drain are generic runtime code, so
 * both recover the descriptor at runtime through this registry, keyed by the
 * schema_id stamped on the instance (yon_rt_new_v) and carried in the frame. */
#define YON_WIRE_TAG_SCALAR 0u
#define YON_WIRE_TAG_STRING 1u
#define YON_WIRE_TAG_NESTED 4u
/* reserved for later seals: 2=LIST, 3=MAP */

/* Register the field-tag descriptor for a transportable place type. The
 * emitter emits one call per type at startup; tags points to n_fields bytes,
 * one YON_WIRE_TAG_* per field in declaration order. Idempotent per id. */
void yon_rt_register_schema(uint32_t schema_id, uint32_t n_fields,
                            const uint8_t *tags);

/* Serialize a place instance into a wire frame. Reads the schema_id stamped on
 * the section, looks up its descriptor, writes the frame into out_buf. Returns
 * the total frame length, or -1 on error / unregistered schema / cap too
 * small. */
int32_t yon_rt_serialize(yon_section_t sec, void *out_buf, uint32_t cap);

/* Rebuild a place instance from a wire frame into heap_id (the consumer's own
 * heap, the wormhole's copy semantics). Strings are reallocated locally. The
 * walk asserts it consumes exactly payload_len; a mismatch is a loud -1, not a
 * corrupt instance. Returns the reconstructed section, or YON_SECTION_INVALID
 * on error. */
yon_section_t yon_rt_deserialize(const void *in_buf, uint32_t len,
                                 uint32_t heap_id);


/* ---- Non-trivial FREE_MERGE via a fold function ----
 *
 * When the space is CRDT_MERGE, each "write" is not a replace but a fold of
 * the new value over the existing payload. The fold function is provided by
 * the caller (ideally derived from the `backed_by sharded`/`crdt` reduction in
 * the .yon, currently passed as a C function pointer).
 *
 * Semantics:
 *   prev == YON_SECTION_INVALID
 *     -> allocate a new slot with `initial` (the base case, semilattice bottom)
 *   prev is a valid section
 *     -> read the current payload, call fold(payload, initial), overwrite the
 *        payload in place, return the same section
 *
 * CRDT invariant: the fold must be commutative, associative, idempotent (a
 * semilattice join). Without these properties, eventual convergence is not
 * guaranteed under concurrent writes.
 *
 * In-place mutation: the returned section is identical to prev (same
 * slot_index). The bytes in the slot change. To guarantee atomicity of
 * concurrent reads the heap lock is needed; under the FREE_MERGE shape we do
 * not take it (a semilattice -> no observable race).
 */
typedef void (*yon_fold_fn)(void *acc,
                             const void *new_val,
                             uint32_t size);

yon_section_t yon_rt_fold(uint32_t heap_id,
                          yon_section_t prev,
                          const void *initial,
                          uint32_t n_bytes,
                          yon_fold_fn fold);

/* "named" variant: the Yon compiler emits this with the fold name ("sum_f64",
 * "max_f64", "min_f64") without having to pass a C function pointer. Maps
 * internally to the registered fold. */
yon_section_t yon_rt_fold_named(uint32_t heap_id,
                                 yon_section_t prev,
                                 const void *initial,
                                 uint32_t n_bytes,
                                 const char *fold_name);

/* Canonical example folds (commutative + associative + idempotent; idempotence
 * fails for sum, but for a CRDT counter commutative+associative suffices if the
 * operation is "increment" not "set"). */
void yon_fold_sum_f64(void *acc, const void *new_val, uint32_t size);
void yon_fold_max_f64(void *acc, const void *new_val, uint32_t size);
void yon_fold_min_f64(void *acc, const void *new_val, uint32_t size);

/* fold for int64 (a G-counter over the integers). */
void yon_fold_sum_i64(void *acc, const void *new_val, uint32_t size);
void yon_fold_max_i64(void *acc, const void *new_val, uint32_t size);
void yon_fold_min_i64(void *acc, const void *new_val, uint32_t size);

/* element-wise fold over an f64 vector. size must be a multiple of
 * sizeof(double). Local idempotence depends on the chosen scalar fold (max/min
 * idempotent, sum not). */
void yon_fold_sum_vec_f64(void *acc, const void *new_val, uint32_t size);
void yon_fold_max_vec_f64(void *acc, const void *new_val, uint32_t size);

/* OR-set (a semilattice of bitsets). size in bytes, fold = element-wise
 * bitwise OR. Idempotent, commutative, associative -> a true monotonic CRDT
 * set. */
void yon_fold_or_bitset(void *acc, const void *new_val, uint32_t size);

/* ---- Stop-the-world checkpoint ----
 *
 * Temporarily suspends all cross-process operations on the registered heaps by
 * taking flock(LOCK_EX) on each in ascending heap_id order (no deadlock).
 * During the checkpoint:
 *   - Cross-process readers block waiting for the lock
 *   - New writes are serialized after the checkpoint ends
 *
 * The snapshot collects occupancy + arena_used + magic for each registered
 * heap. The basic coherence check verifies magic and version. Semantic
 * coherence (e.g. section convergence across spaces) requires knowledge of the
 * .yon program and is not done here.
 *
 * Lifecycle:
 *   yon_rt_checkpoint_begin(out) -> acquire all locks, write the snapshot
 *   yon_rt_checkpoint_check(snap)  -> verify basic invariants
 *   yon_rt_checkpoint_end(snap)    -> release the locks in reverse order
 */
#define YON_MAX_CHECKPOINT_HEAPS 64

typedef struct {
    uint32_t n_heaps;
    uint32_t heap_ids[YON_MAX_CHECKPOINT_HEAPS];
    uint32_t occupancy[YON_MAX_CHECKPOINT_HEAPS];
    uint32_t arena_used[YON_MAX_CHECKPOINT_HEAPS];
    uint32_t magic[YON_MAX_CHECKPOINT_HEAPS];
    uint32_t version[YON_MAX_CHECKPOINT_HEAPS];
} yon_rt_checkpoint_t;

/* Open a checkpoint. Locks all registered heaps (ascending order). Fills `out`
 * with the snapshot. Returns 0 on success, -1 on error. */
int yon_rt_checkpoint_begin(yon_rt_checkpoint_t *out);

/* Basic coherence check:
 *  - magic == YON_HEAP_MAGIC for each heap
 *  - version == YON_HEAP_VERSION
 *  - n_heaps > 0
 * Returns 0 if all ok, -1 if a violation is found (logged to stderr). Out
 * parameters: n_violations and (optional) the first violator heap_id. */
int yon_rt_checkpoint_check(const yon_rt_checkpoint_t *snap,
                             uint32_t *out_n_violations,
                             uint32_t *out_first_violator);

/* Close a checkpoint: release the locks in reverse order. */
int yon_rt_checkpoint_end(yon_rt_checkpoint_t *snap);

/* ---- Online schema evolution (versioning + lazy migration) ----
 *
 * The ability to evolve the place schema at runtime without a restart.
 * Layer 0:
 *   - Each slot carries a schema_version (default 0 = unspecified)
 *   - Migration functions registered at runtime: (place, v_from, v_to, fn)
 *   - yon_rt_field_load_v(sec, version, ...) applies the migration on the fly
 *     if the payload is written in a version different from the one requested
 *
 * Higher layers (future): `.yon` syntax to declare versions, hot-swap via
 * dlopen, deployment tooling, etc.
 *
 * Honest: layer 0 is only the runtime infrastructure. Without the layers
 * above, the programmer must register migrations in C and use the API
 * directly. Enough to demonstrate the pattern. */

typedef int (*yon_migration_fn)(const void *old_payload, uint32_t old_size,
                                 void *new_payload, uint32_t new_size);

/* Register a migration. Returns 0 on success, -1 if the registry is full or
 * the entry is a duplicate. */
int yon_rt_register_migration(const char *place_name,
                               uint32_t v_from,
                               uint32_t v_to,
                               uint32_t new_payload_size,
                               yon_migration_fn fn);

/* Variant of yon_rt_new with an explicit schema_version. yon_rt_new(...) is
 * equivalent to yon_rt_new_v(..., 0). */
yon_section_t yon_rt_new_v(uint32_t heap_id,
                            const void *payload_bytes, uint32_t n_bytes,
                            const char *place_name, uint32_t schema_version);

/* Variant of yon_rt_field_load with migration. If the slot has schema_version
 * != requested_version, looks up the migration registry and applies the chain
 * of migrate functions. If no chain is found, returns -1.
 *
 * Note: the migration produces a temporary, non-persisted payload (lazy
 * read-only). An "upgrade in place" would need write-back, left to a future
 * layer. */
int yon_rt_field_load_v(yon_section_t sec,
                         const char *place_name,
                         uint32_t requested_version,
                         uint32_t offset, uint32_t size, void *out);

/* Diagnostic: the number of registered migrations. */
int yon_rt_migration_count(void);

/* ---- Heap accessor (for the SAGA layer / debug) ----
 *
 * Returns the physical yon_xheap_t* for the current heap_id, per backend.
 * Needed by modules like yon_saga.c that call yon_xheap_clear on slots for
 * compensating actions.
 *
 * Note: the returned pointer has a lifetime until yon_rt destroy. Currently it
 * always returns the same global heap.
 */
yon_xheap_t *yon_rt_heap_for(uint32_t heap_id);

/* ---- Handler dispatch ---- */

int yon_rt_handler_push(uint64_t hash, void *fn_ptr);
int yon_rt_handler_pop(uint64_t hash);
void *yon_rt_handler_lookup(uint64_t hash);

/* ---- P8 #83: Coordination protocol cross-Space ---- */

/* When a function crosses multiple Spaces, the coordination protocol is
 * derived from the set of policies of the Spaces involved:
 *   - All STRONG          -> 2PC (two-phase commit)
 *   - Mix STRONG+EVENTUAL -> SAGA (compensating actions)
 *   - All CRDT_MERGE      -> FREE_MERGE (no coordination)
 *   - Single Space        -> LOCAL (no coordination)
 *
 * In single-process mode these protocols are not operative (no failure, no
 * race); the framework is here to demonstrate the derivation and to be
 * materialized later in IPC and network modes. */
#define YON_COORD_LOCAL      0   /* single space, no coordination */
#define YON_COORD_TWO_PHASE  1   /* 2PC: all STRONG */
#define YON_COORD_LAX        2   /* mix STRONG+EVENTUAL (one_exact adjunction) */
#define YON_COORD_FREE_MERGE 3   /* all CRDT_MERGE */

/* Open a "cross-space op" announcing the set of heap_ids involved. The runtime
 * deduces the coordination protocol and logs it to stderr (diagnostic).
 * Returns an opaque token to pass to yon_rt_end_cross_space_op. */
uint32_t yon_rt_begin_cross_space_op(const uint32_t *heap_ids, uint32_t n);

/* Close a cross-space op opened with begin. Currently a no-op plus a
 * diagnostic log. Later it will close the 2PC transaction or the saga, or
 * commit the CRDT merge. */
void yon_rt_end_cross_space_op(uint32_t token);

/* Derive the coordination shape from the properties of the geometric morphism.
 *
 * Categorically honest mapping:
 *
 *   adjunction + f_star_exact + f_lower_star_exact
 *     -> TWO_PHASE
 *     (both adjoints preserve their limits, guaranteeing cross-space
 *      linearizability)
 *
 *   adjunction + (f_star_exact XOR f_lower_star_exact)
 *     -> SAGA
 *     (only one is exact: compensation is needed on the non-exact side)
 *
 *   adjunction + neither_exact
 *     -> FREE_MERGE
 *     (both lax: eventual convergence via a semilattice)
 *
 *   no adjunction declared
 *     -> LOCAL (no cross-topos relation)
 *
 * Completely replaces the old policy enum table. */
typedef struct {
    uint32_t adjunction;          /* 1 if declared, 0 otherwise */
    uint32_t f_star_exact;        /* 1 if f^* preserves finite limits */
    uint32_t f_lower_star_exact;  /* 1 if f_* preserves finite colimits */
} yon_geom_morphism_props_t;

uint32_t yon_rt_derive_coordination_from_gm(
    const yon_geom_morphism_props_t *props);

/* Runtime registry of the geometric morphisms declared in the .yon program.
 *
 * When a program declares
 *   geom_morphism F from SiteA to SiteB { f_star ... adjunction exact f_star }
 * the compiler emits at the startup of main() a call to
 * yon_rt_register_geom_morphism to populate g_geom_morphisms[].
 *
 * The dispatch in begin_cross_space_op looks among the registered gm for the
 * one connecting the topoi involved in the operation and uses the categorical
 * derivation (yon_rt_derive_coordination_from_gm) instead of the legacy enum
 * table.
 *
 * Limit: the registry is a global singleton (max 32 gm). It is not propagated
 * cross-process (each process registers its own at startup). */
#define YON_MAX_GEOM_MORPHISMS 32

/* Register a geometric morphism. Returns 0 on success, -1 on error. */
int yon_rt_register_geom_morphism(const char *name,
                                   const char *source_topos,
                                   const char *target_topos,
                                   const yon_geom_morphism_props_t *props);

/* Diagnostic: the number of registered gm. */
int yon_rt_geom_morphism_count(void);

/* Look up the gm connecting source -> target. Returns 1 if found, 0 otherwise.
 * If found, *out_props is populated. */
int yon_rt_lookup_geom_morphism(const char *source_topos,
                                 const char *target_topos,
                                 yon_geom_morphism_props_t *out_props);

/* ---- Backend selection (multi-process IPC scaffolding) ---- */

/* Backends:
 *   - SEPARATE : each heap_id has its own private yon_xheap_t (default).
 *                Physically partitioned; same semantics for pure programs
 *                (content-addressing per heap_id), blobs in distinct heaps. A
 *                fork()ed spawn replica inherits a private COW copy, so no Space
 *                heap is shared across processes; shm is reserved for the wire.
 *   - SHM      : POSIX shared memory. Each heap_id is a separate shm region, so
 *                a producer and a consumer in different processes can attach the
 *                same Space heap.
 *
 * Backend selected via env var YON_BACKEND: "shm" selects SHM; any other value
 * (or unset) selects SEPARATE, the default.
 *
 * The exposed ABI stays the same: the caller does not know which backend is
 * active. Sections stay i64 packed (heap_id+xcoord), portable across
 * processes. */

/* ---- P8 #87: Streams cross-Space (emit / produce / await) ---- */

/* A Stream is a FIFO channel of typed values, associated with a Space (the
 * consumer's target space). The producer can be in any space; a cross-space
 * producer->consumer applies the coordination shape of the consumer space's
 * backing reduction.
 *
 * In single-process mode: stream = in-memory ring buffer, no real threading,
 * emit is append, await is shift-front. Later: shared-memory queue / network
 * channel. */

#define YON_STREAM_MAX_SLOTS  64
#define YON_STREAM_INVALID    ((uint32_t)0xFFFFFFFFu)

/* Create a stream with a fixed slot_size (bytes per value). target_heap_id is
 * the consumer's space. Returns stream_id (>=0) or YON_STREAM_INVALID on
 * failure. */
uint32_t yon_rt_stream_create(const char *name,
                               uint32_t target_heap_id,
                               uint32_t slot_size);

/* Look up an existing stream by name. */
uint32_t yon_rt_stream_lookup(const char *name);

/* Emit: append a value at the tail. Fire-and-forget (no ack). Returns 0 on
 * success, -1 if the stream is full or invalid. */
int yon_rt_stream_emit(uint32_t stream_id, const void *value_ptr);

/* Produce: append + ack. Currently == emit (no failure). The semantic
 * difference is preserved for the future (back-pressure). */
int yon_rt_stream_produce(uint32_t stream_id, const void *value_ptr);

/* Await: take the value at the head, copy into out_ptr. Returns 0 on success,
 * -1 if the stream is empty or invalid. Does not block (no threading); the
 * caller must know when emit precedes await. */
int yon_rt_stream_await(uint32_t stream_id, void *out_ptr);

/* Diagnostic: the current occupancy of the stream. */
uint32_t yon_rt_stream_size(uint32_t stream_id);

/* f64 wrappers for the frontend stdlib. */
double yon_rt_stream_make_f64(double target_heap_f64);
double yon_rt_stream_emit_f64(double stream_id_f64, double value);
double yon_rt_stream_await_f64(double stream_id_f64);

/* ---- Coercion / stdlib ---- */

uint8_t yon_rt_text_to_prop(double h);   /* String fusion: handle */
uint8_t yon_rt_to_prop(int8_t b);
int8_t  yon_rt_to_bool(uint8_t prop);
double  yon_rt_transport(double witness, double value);

/* ---- Diagnostic ---- */

uint32_t yon_rt_heap_occupancy(uint32_t heap_id);
uint32_t yon_rt_space_count(void);

/* ============================================================== */
/* Data structures — leveraging the content-addressed yon_xheap   */
/* ============================================================== */

/* Map: number -> number, content-addressed via the singleton xheap.
 *
 * Semantic model: a "map" is identified by a map_id (double for MLIR f64
 * compatibility). map_id=0 = the empty map. Each put creates a new map_id that
 * encapsulates the previous one + (k,v). Automatic content-addressing
 * guarantees that maps with the same content share the same physical slot. */

double yon_rt_map_empty(void);

double yon_rt_map_put(double map_id, double key, double value);

double yon_rt_map_get(double map_id, double key);

double yon_rt_map_contains(double map_id, double key);

double yon_rt_map_size(double map_id);

/* Set: number, content-addressed. A sub-case of Map with value=1. */

double yon_rt_set_empty(void);

double yon_rt_set_add(double set_id, double elem);

double yon_rt_set_contains(double set_id, double elem);

double yon_rt_set_size(double set_id);

/* DAG: node = (label, children_slot_1, ..., children_slot_n).
 * Content-addressing -> identical sub-DAGs collapse into the same slot. */

double yon_rt_merkle_leaf(double label);

double yon_rt_merkle_node2(double label, double child1, double child2);

/* node3 / node4 with S_n canonicalize-by-sort. */
double yon_rt_merkle_node3(double label, double c1, double c2, double c3);
double yon_rt_merkle_node4(double label, double c1, double c2,
                           double c3, double c4);

double yon_rt_merkle_label(double node_id);

double yon_rt_merkle_child(double node_id, double child_idx);

double yon_rt_merkle_equal(double a, double b);

/* ============================================================== */
/* S6 — Leech G_24 sign-flip canonicalization                     */
/* ============================================================== */

/* yon_rt_leech_sign_canonical(label, signs_24bit):
 *   Canonicalize a 24-bit sign pattern under the Golay code G_24 orbit. Two
 *   signs_24bit that differ by a G_24 codeword produce the same xheap slot.
 *   Yon surface API: Leech.sign_canonical(label, signs). */
double yon_rt_leech_sign_canonical(double label, double signs_24bit);

/* Expose the canonical syndrome (cocode rep) for debug. */
double yon_rt_leech_syndrome(double signs_24bit);

/* label-invariant orbit ID and same-orbit check. */
double yon_rt_leech_orbit_id(double signs_24bit);
double yon_rt_leech_same_orbit(double signs_a, double signs_b);

/* Arena: Leech type-2 arena exposed to the language (handle = id+1 into a pool). */
double yon_rt_arena_empty(void);
double yon_rt_arena_put(double h, double point, double value);
double yon_rt_arena_get(double h, double point);
double yon_rt_arena_occupied(double h, double point);
double yon_rt_arena_orbit(double h, double point);
double yon_rt_arena_same_orbit(double h, double pa, double pb);
double yon_rt_arena_fuse(double h, double point, double value, double sigma);
double yon_rt_arena_fusion_count(double h, double point);

/* M_24 Mathieu orbit canonical + xi Conway involution. */
double yon_rt_leech_m24_orbit(double v_24bit);
double yon_rt_leech_gcode_weight(double v_24bit);
double yon_rt_leech_cocode_weight(double v_24bit);
double yon_rt_leech_xi_apply(double v_24bit);
double yon_rt_leech_co0_step(double v_24bit);

/* Transitive Co_0 canonical via BFS. */
double yon_rt_leech_co0_canonical(double v_24bit);
double yon_rt_leech_co0_orbit_size(double v_24bit, double max_iter);

/* Co_0 transport (Curtis): sigma with v*sigma == w. Returns pool id (or 0). */
double yon_rt_leech_transport(double v_24bit, double w_24bit);
double yon_rt_leech_transport_apply(double x_24bit, double transport_id);

/* ============================================================== */
/* S5 — Phased memory: observe payload via geom_morphism           */
/* ============================================================== */

/* yon_rt_observe(slot_id_f64, gm_kind, default_val):
 *
 * Implements the "same memory, different semantics" pattern:
 *
 *   - slot_id_f64: handle of the physical payload in xleech2 (slot)
 *   - gm_kind: the kind of transformation applied by the pull (numeric):
 *       0 = identity, 1 = scale10, 2 = scale100, 3 = cents,
 *       4 = negate, 5 = double
 *   - default_val: fallback value if the slot is invalid
 *
 * The physical payload in xleech2 is unique; this function returns a view of
 * the value, optionally filtered by the kind. */

double yon_rt_observe(double slot_id_f64,
                       double gm_kind,
                       double default_val);

/* yon_rt_observe_alloc(value): allocate a payload (a single double) in the
 * global xheap and return the slot_id as a double. Content-addressed: the same
 * value -> the same slot. */
double yon_rt_observe_alloc(double value);

/* Diagnostic: payloads physically allocated in the global xheap. */
uint32_t yon_rt_xheap_used(void);

/* ============================================================== */
/* spawn — multi-process via fork() of the current program        */
/* ============================================================== */

/* yon_rt_spawn_self(n_replicas):
 *
 * Fork N copies of the current process. Each replica resumes execution from
 * the point immediately after the spawn, but with a distinct "spawn_index"
 * (0..N-1). The original process (parent) waits for all children to complete,
 * then continues.
 *
 * Implementation: uses POSIX fork() + wait(). The child replicas receive an
 * env var YON_SPAWN_INDEX set to 0..N-1; the parent does not set it or sets it
 * to a sentinel.
 *
 * Return (to the caller, post-wait):
 *   - parent: the number of children that completed successfully (0..N)
 *   - child:  immediate exit after the call (does not return to Yon)
 *
 * Cross-process: each child is a fork() COW copy, so under the default
 * L2_SEPARATE backend every Space heap is private to the replica — nothing is
 * shared across processes except the wire (the promote/collect queue). Only
 * under the opt-in L2_SHM backend are Space heaps (and hence a fold
 * accumulator) backed by shared memory. */
double yon_rt_spawn_self(double n_replicas);

/* yon_rt_spawn_index(): returns the spawn_index of the current process (-1 if
 * it is not a spawn child). Lets the Yon code differentiate the work per
 * replica. */
double yon_rt_spawn_index(void);

/* ─── spawn { } collection primitive (step 4a) ──────────────────────────
 * Backs the spawn block-expression. The parent opens a PROCESS_SHARED queue
 * BEFORE forking N replicas; each child runs the block body, pushes every
 * `promote E` (one f64) onto the queue, then exits without running the
 * parent's continuation; the parent interleaves draining the queue with
 * reaping exited children so the bounded queue never deadlocks the join, and
 * collects the promoted values. Opaque handle is the same in parent and child
 * (each a post-fork copy). */
void   *yon_rt_spawn_open(double n_replicas);   /* parent: fork; child: returns its own ctx */
double  yon_rt_spawn_role(void *ctx);           /* 1.0 = child, 0.0 = parent */
double  yon_rt_spawn_index_of(void *ctx);       /* child index 0..n-1 (-1 in parent) */
void    yon_rt_spawn_promote(void *ctx, double value);  /* child: push one value */
void    yon_rt_spawn_child_exit(void *ctx);     /* child: _exit(0), never returns */
int     yon_rt_spawn_join_collect(void *ctx, double *out, int cap); /* parent: drain+reap; returns count */
void    yon_rt_spawn_close(void *ctx);          /* parent: close + unlink + free */

/* Parent bridge: drain the collection and emit the values into a fresh stream,
 * returning the stream id as f64 (the value of the spawn expression). */
double  yon_rt_spawn_join_stream(void *ctx);

/* f64 id-based facade the Core/MLIR lowering calls (names match the emit_mlir
 * externs, like the Stream__ wrappers). Spawn__open returns a session id. */
double  Spawn__open(double n);
double  Spawn__role(double id);
double  Spawn__index(double id);
double  Spawn__promote(double id, double value);
double  Spawn__child_exit(double id);
double  Spawn__join_stream(double id);

/* ============================================================== */
/* Idraulica v2 — actor-model cross-Space RPC                      */
/* ============================================================== */
/* Named request mailbox per Space (/yon_stream_<Space>) + private reply
 * channels per caller session; PROCESS_SHARED mutex/cond wakeup; request
 * correlation via (session nonce, per-call seq). See yon_rt.c for the full
 * design notes (locked decisions of 2026-06-03). */

typedef struct {
    uint64_t nonce;            /* caller session nonce */
    uint64_t seq;              /* per-call sequence within the session */
    char     reply_name[128];  /* private return-channel identity */
    uint32_t selector;         /* operation selector (0 = shutdown) */
    uint32_t argc;
    double   args[8];
} yon_rpc2_req_t;

/* Server/caller mailbox handle (opaque). as_server=1 claims server_pid for
 * caller-side liveness validation. */
void  *yon_rt_rpc2_queue_open(const char *space_name, int as_server);
void   yon_rt_rpc2_queue_close(void *q);
int    yon_rt_rpc2_queue_unlink(const char *space_name);
uint32_t yon_rt_rpc2_queue_epoch(void *q);   /* diagnostic */

/* Server side: take one request (argc >= 0, -1 on idle timeout), then reply
 * into the caller's private channel named in the request. */
int    yon_rt_rpc2_take(void *q, yon_rpc2_req_t *out, uint32_t idle_ms);
int    yon_rt_rpc2_reply(const yon_rpc2_req_t *req, double result);

/* Caller side: one synchronous call to a Space by NAME. -777.0 sentinel on
 * unreachable peer / timeout (turned into a clear error by the language). */
double yon_rt_rpc2_call_named(const char *space_name, double selector,
                              double argc, const double *args,
                              uint32_t reply_timeout_ms);

/* Strato 1 — runtime integration: serve loop, name-keyed lifecycle, invoke.
 * The lowered code passes the Space name as a pointer to a global string. */
double yon_rt_rpc2_serve_loop(const char *space_name);
int    yon_rt_should_serve2(char *out, size_t outsz);
void   yon_rt_rpc2_register_space_binary(const char *space, const char *path);
double yon_rt_rpc2_invoke_named0(const char *sp, double sel);
double yon_rt_rpc2_invoke_named (const char *sp, double sel, double x);
double yon_rt_rpc2_invoke_named2(const char *sp, double sel, double x, double y);
double yon_rt_rpc2_invoke_named3(const char *sp, double sel, double x, double y,
                                 double z);
double yon_rt_rpc2_invoke_named4(const char *sp, double sel, double x, double y,
                                 double z, double w);

/* ============================================================== */
/* S6 — Voyager Seal: Golay code error-correction layer            */
/* ============================================================== */

/* The extended Golay code (24, 12, 8) is the error-correction technology used
 * by Voyager 1 and 2 for interstellar communication (1977-present, data from
 * 23 billion km).
 *
 * Encoding: 12 bits of data -> 24 bits of codeword (Golay code).
 * Minimum distance: 8 -> corrects up to 3 bit-flips per codeword.
 *
 * Implementation: a wrapper over libmmgroup mat24_gcode_to_vect and
 * mat24_vect_to_gcode + mat24_syndrome for syndrome decoding.
 *
 * Yon use cases:
 * - Resilient storage in SHM (cosmic ray, bit rot, RAM corruption)
 * - Distributed conflict resolution at the bit level (beyond CRDT fold)
 * - Self-healing payloads in xleech2 */

/* voyager_seal(data12): encode 12 bits -> 24-bit Golay codeword. Valid input
 * range: data12 in [0, 4096). Out of range = clipping. */
double yon_rt_voyagerlist_seal(double data12);

/* voyager_open(codeword24): decode 24 bits (possibly corrupted) -> the
 * original 12 bits. Applies syndrome decoding for automatic recovery of up to
 * 3 bit-flips. */
double yon_rt_voyagerlist_open(double codeword24);

/* voyager_corrupt(codeword24, n_bits): a test helper. Flips n_bits bits
 * pseudo-randomly in the codeword. n_bits in [0, 3] guarantees recovery;
 * beyond 3 = unrecoverable corruption. */
double yon_rt_voyagerlist_corrupt(double codeword24, double n_bits);

/* ============================================================== */
/* Immutable list (cons-list) over the content-addressed yon_xheap  */
/* ============================================================== */
/*
 * Model: each cons cell is a payload {value: f64, tail_slot: u32,
 * sentinel: u32} = 16 bytes. The cell is placed in g_yon_heap via
 * yon_xheap_put with tag YON_TAG_USER1. The list_id exposed to the frontend is
 * the slot_index of the cons cell (cast to double).
 *
 * Empty list: list_id == YON_RT_LIST_EMPTY ((double)0xFFFFFFFF), a sentinel
 * distinguishable from any valid slot_index (max 196559).
 *
 * Content-addressing: two lists with the same value and the same tail collide
 * in the same slot (automatic dedup). Immutable by construction: head/tail
 * read the payload, no mutation.
 *
 * head/tail on empty: return 0.0 / YON_RT_LIST_EMPTY respectively.
 * length(empty) = 0; length(cons(v,t)) = 1 + length(t).
 */

#define YON_RT_LIST_EMPTY ((double)0xFFFFFFFFu)

double yon_rt_list_empty(double dummy);
double yon_rt_list_cons(double value, double tail_id);
double yon_rt_list_head(double list_id);
double yon_rt_list_tail(double list_id);
double yon_rt_list_length(double list_id);

/* Vec: dynamic array on an arena strip (no malloc). In-place mutable: set()
 * writes a slot, push() appends into spare capacity or reallocs a doubled
 * strip and returns a NEW handle (always use the returned handle). */
double yon_rt_vec_empty(void);
double yon_rt_vec_size(double vec_id);
double yon_rt_vec_get(double vec_id, double idx);
double yon_rt_vec_push(double vec_id, double value);
double yon_rt_vec_set(double vec_id, double idx, double value);

/* ============================================================== */
/* Mutable space cell (a static BSS registry)                       */
/* ============================================================== */
/*
 * Yon semantics: Space.make(v0) allocates a mutable cell initialized to v0;
 * Space.set(s, v) overwrites the current value; Space.get(s) reads the current
 * value.
 *
 * Model: a static registry g_space_cells[MAX] in BSS — no malloc, no
 * content-addressing (mutation is incompatible with the content-addressed
 * xheap allocator). Each Space.make returns the progressive cell id.
 *
 * Limit: process-local. A cross-process Space (cross-fork) would require SHM
 * mapping, out of scope here.
 */

#define YON_RT_MAX_SPACE_CELLS 1024

double yon_rt_space_make(double initial);
double yon_rt_space_set(double space_id, double new_value);
double yon_rt_space_get(double space_id);
double yon_rt_space_mark(void);
double yon_rt_space_reset(double mark);

/* ============================================================== */
/* S7 — LockedRing: capability tokens via the Co_0 group            */
/* ============================================================== */
/*
 * The Conway group Co_0 has order ~8.3x10^18, twice the group Co_1 (~4x10^18, a
 * sporadic simple group). It is the automorphism group of the Leech lattice:
 * it acts transitively on the 196,560 type-2 vectors.
 *
 * A LockedRing "key" is a word of N=8 Co_0 atoms (32 bytes). Sealing a slot
 * consists of applying the Co_0 group action to the slot's Leech coordinate
 * (via the MPHF bijection slot_idx <-> type-2 xcoord). Unsealing applies the
 * inverse.
 *
 * Honest upfront:
 * - This is NOT NIST/FIPS crypto. It is structured obfuscation via a group
 *   action on Leech.
 * - Side-channel vulnerable: lookup timing, key in cleartext RAM, no defense
 *   against ROP/cache timing.
 * - Legitimate use case: internal multi-tenancy capability tokens, a ring of
 *   authority between sub-components of the same program.
 * - Effective key space: 5 generator tags (d, p, x, y, l) x ~10^9 average
 *   value range x 2 signs x 8 atoms ~= 10^77 nominal combinations (with real
 *   Co_0 collisions -> |Co_0|^8 upper bound ~ 5x10^150, net of the fact that
 *   Co_0 itself has only 8.3x10^18 distinct elements). In practice: a key
 *   space sufficient for internal multi-tenancy.
 */

#define YON_RT_LOCKEDRING_KEY_ATOMS 8

double yon_rt_conway_gen_key(double seed);
double yon_rt_conway_seal_slot(double slot_id, double key_id);
double yon_rt_conway_unseal_slot(double sealed_id, double key_id);
double yon_rt_conway_key_equal(double key_a, double key_b);

#ifdef __cplusplus
}
#endif

#endif /* YON_RT_H */


/* Capability registry. */
double yon_rt_cap_grant(double name_hash);
double yon_rt_cap_check(double name_hash);
double yon_rt_cap_revoke(double name_hash);

/* Online schema evolution. */
double yon_rt_move_register_version(double name_hash, double version);
double yon_rt_move_current_version(double name_hash);

/* Stdlib base */

/* Math */
double yon_rt_math_sqrt(double x);
double yon_rt_math_abs(double x);
double yon_rt_math_floor(double x);
double yon_rt_math_ceil(double x);
double yon_rt_math_round(double x);
double yon_rt_math_min(double a, double b);
double yon_rt_math_max(double a, double b);
double yon_rt_math_pow(double a, double b);
double yon_rt_math_log(double x);
double yon_rt_math_exp(double x);
double yon_rt_math_sin(double x);
double yon_rt_math_cos(double x);
double yon_rt_math_pi(void);
double yon_rt_math_e(void);

/* Bits */
double yon_rt_bits_and(double a, double b);
double yon_rt_bits_or(double a, double b);
double yon_rt_bits_xor(double a, double b);
double yon_rt_bits_not(double a);
double yon_rt_bits_shl(double a, double n);
double yon_rt_bits_shr(double a, double n);
double yon_rt_bits_popcount(double a);

/* IO */
double yon_rt_io_print_num(double x);


/* Pluggable canonicalizer.
 * canon_id: 0=identity, 1=G_24, 2=M_24 weight, 3=Co_0 one-shot,
 *           4=Co_0 BFS bounded, 5=popcount, 6=mod_8 */

/* Extended stdlib — String/Time/Random/Crypto. */
double yon_rt_string_from_int(double n);
double yon_rt_string_length(double str_id);
double yon_rt_string_concat(double a_id, double b_id);
double yon_rt_string_equal(double a_id, double b_id);
double yon_rt_string_char_at(double str_id, double idx);
double yon_rt_string_print(double str_id);
double yon_rt_time_now_ms(void);
double yon_rt_time_now_ns(void);
double yon_rt_random_seed(double seed);
double yon_rt_random_int(void);
double yon_rt_random_range(double lo, double hi);
double yon_rt_crypto_fnv1a(double str_id);
double yon_rt_crypto_hash_int(double n);

double yon_rt_math_modulo(double a, double b);
double yon_rt_math_gcd(double a, double b);

/* String / File / Bits helpers. */
double yon_rt_string_parse_number(double str_id);
double yon_rt_string_substring(double str_id, double start, double len);
double yon_rt_string_find_char(double str_id, double char_code, double from_idx);
double yon_rt_string_from_char(double char_code);
double yon_rt_file_read_text(double path_id);
double yon_rt_file_exists(double path_id);
double yon_rt_bits_fold(double value, double op_id, double init);

double yon_rt_seq_range(double n);

/* 64-bit Bits variants. */
double yon_rt_bits_or_64(double a, double b);
double yon_rt_bits_and_64(double a, double b);
double yon_rt_bits_xor_64(double a, double b);

/* try_add returns added/dup flag. */
double yon_rt_hashset_try_add(double set_id, double elem);

/* zero-alloc iteration over HashSet buckets */
double yon_rt_hashset_at_bucket(double set_id, double idx);
double yon_rt_hashset_dir_capacity(double dummy);
