#ifndef YON_CURTIS_CANON_H
#define YON_CURTIS_CANON_H

#include <stdint.h>

/* Precomputed canon_map lookup tables for the fixed Curtis frame.
 * Defined in yon_curtis_canon.c (generated by tools_gen_canon.c).
 * Indexed by the MPHF index of a type-2 vector.
 *
 * With the Curtis frame fixed, the relational class partition is a constant,
 * so its canon_map can be precomputed at build time instead of rebuilt by a
 * qsort over 196560 elements at each XRelMap/XRelSet freeze. XRelMap and
 * XRelSet point their canon directly at these LUTs when the frame is Curtis;
 * a custom frame still builds canon at runtime.
 */
extern const uint32_t YON_CURTIS_CANON_XC[196560];   /* MPHF idx -> representative xcoord (XRelMap) */
extern const uint32_t YON_CURTIS_CANON_IDX[196560];  /* MPHF idx -> representative MPHF idx (XRelSet) */

#endif /* YON_CURTIS_CANON_H */
