/* Minimal __yon_dispatch stub for C runtime UNIT tests.
 *
 * yon_rt.o's cross-Space RPC serve-loop references __yon_dispatch, which in a
 * real program is GENERATED by the Yon compiler (emit_mlir emits one per
 * module). A pure-C runtime test that links yon_rt.o but is not a compiled Yon
 * program therefore lacks the symbol. These tests never invoke the RPC loop, so
 * a no-op stub with the real signature (yon_rt.c:1730) satisfies the linker
 * without changing behaviour. (conway/quantizer embed their own stub; arena and
 * spawn link this one.)
 */
double __yon_dispatch(double selector, double a1, double a2, double a3, double a4) {
    (void)selector; (void)a1; (void)a2; (void)a3; (void)a4;
    return 0.0;
}
