"""C runtime UNIT tests, driven from pytest.

Each runtime self-test .c is compiled against the built runtime objects and run;
the node asserts exit 0 and a layer-specific success marker in stdout. This wires
the previously-orphaned runtime tests (arena, spawn) and the shell-only ones
(conway, quantizer) into the single pytest harness, alongside the MPHF bijection
check already in test_yon_pipeline.

Mirrors test_yon_pipeline.test_runtime_mphf: one node per runtime test, isolated
and named, so a failure points at the exact C module.
"""

import os
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
FT = ROOT / "runtime"
CC = os.environ.get("YONC_CC", "gcc")

# Same runtime object set the end-to-end pipeline links against.
_RT_NAMES = [
    "yon_rt.o", "yon_mmap.o", "leech_orbits.o", "yon_arena.o", "yon_curtis_canon.o",
    "xleech2_coord.o", "xleech2_heap.o", "xleech2_mphf.o",
    "vendor/mmgroup/mat24_tables.o", "vendor/mmgroup/mat24_functions.o",
    "vendor/mmgroup/gen_leech.o", "vendor/mmgroup/gen_leech3.o",
    "vendor/mmgroup/gen_leech_type.o", "vendor/mmgroup/gen_leech_reduce.o",
    "vendor/mmgroup/gen_xi_functions.o", "vendor/mmgroup/mm_group_n.o",
    "vendor/mmgroup/mm_index.o",
]
RTSET = [str(FT / n) for n in _RT_NAMES]

# A no-op __yon_dispatch for tests that link yon_rt.o but don't self-provide it
# (the symbol is normally generated by the Yon compiler per program).
DISPATCH_STUB = str(Path(__file__).resolve().parent / "_dispatch_stub.c")

# (id, source file, expected stdout marker, needs_dispatch_stub)
#   conway/quantizer embed their own __yon_dispatch -> no stub (would duplicate).
#   arena/spawn don't -> link the shared stub.
C_UNIT_TESTS = [
    ("conway_chains", "yon_test_conway_chains.c", b"CONWAY-CHAINS: PASS", False),
    ("quantizer",     "yon_test_quantizer.c",     b"QUANTIZER: PASS",     False),
    ("arena",         "yon_arena_test.c",         b"ALL PASS",            True),
    ("spawn_collect", "test_spawn_collect.c",     b"spawn facade: OK",    True),
    # Memory-safety unit tests for attacker-influenceable runtime paths. Each
    # links the full RTSET (which includes yon_rt.o -> needs the __yon_dispatch
    # stub) and prints a unique final marker.
    ("field_load",    "test_unit_field_load.c",   b"FIELD_LOAD: PASS",    True),
    ("coord_decode",  "test_unit_coord_decode.c", b"COORD_DECODE: PASS",  True),
    ("xheap_bounds",  "test_unit_xheap_bounds.c", b"XHEAP_BOUNDS: PASS",  True),
    ("hsh",           "test_unit_hsh.c",          b"HSH: PASS",           True),
    # Functional unit tests for untested runtime families (string pool, Golay
    # VoyagerList, open-addressed HashMap). Each links the full RTSET (includes
    # yon_rt.o -> needs the __yon_dispatch stub) and prints a unique marker.
    ("string",        "test_unit_string.c",       b"STRING: PASS",        True),
    ("voyagerlist",   "test_unit_voyagerlist.c",  b"VOYAGERLIST: PASS",   True),
    ("map",           "test_unit_map.c",          b"MAP: PASS",           True),
    # Functional unit tests for the linear collections (Vec/Deque/PQ), the
    # Merkle content-addressing DAG, and the bits/crypto hashing families. Each
    # links the full RTSET (includes yon_rt.o -> needs the __yon_dispatch stub)
    # and prints a unique final marker.
    ("vec",           "test_unit_vec.c",          b"VEC: PASS",           True),
    ("merkle",        "test_unit_merkle.c",       b"MERKLE: PASS",        True),
    ("bits",          "test_unit_bits.c",         b"BITS: PASS",          True),
]


@pytest.fixture(scope="session", autouse=True)
def _objs_built():
    missing = [n for n in RTSET if not Path(n).exists()]
    if missing:
        pytest.skip(f"runtime objects not built: {missing[0]} (run `make` in runtime/)")


@pytest.mark.parametrize(
    "name,src,marker,needs_stub", C_UNIT_TESTS, ids=[t[0] for t in C_UNIT_TESTS]
)
def test_runtime_unit(name, src, marker, needs_stub, tmp_path):
    exe = tmp_path / name
    extra = [DISPATCH_STUB] if needs_stub else []
    c = subprocess.run(
        [CC, "-std=c11", "-O2", f"-I{FT}", f"-I{FT}/vendor/mmgroup",
         str(FT / src), *RTSET, *extra, "-lpthread", "-lm", "-o", str(exe)],
        capture_output=True, timeout=120,
    )
    assert c.returncode == 0, "compile failed:\n" + c.stderr.decode(errors="replace")[-2000:]
    r = subprocess.run([str(exe)], capture_output=True, timeout=180)
    out = r.stdout.decode(errors="replace")
    assert r.returncode == 0, f"exit {r.returncode}:\n{out[-2000:]}"
    assert marker in r.stdout, f"missing marker {marker!r}:\n{out[-2000:]}"
