#!/usr/bin/env python3
"""Generate the full 48-taxon Yon trace from taxa.json (the ONE swappable source).

After the grade-vs-clade finding (manuscript/linear-map.md): the CLADE relation is
read by the LINEAR map (Leech.embed(v,3), no quantizer) + Leech.pair_subtype (the
raw subtype of a^b, no type-2 gate). The grade is the mode-0 orbit. omega/triangle
stay on type-2 (mode-0) points.

Emits regression/book/jp/10_taxa_full/Entry.yon, printing in a fixed order:

  Block 1  [N]            m24_orbit(embed(v_i, 0))            GRADE family (popcount)
  Block 2  [N]            m24_orbit(embed(v_i, 3))            type-2 check under linear
  Block 3  [N*(N-1)/2]    pair_subtype(embed(v_i,3),embed(v_j,3))  CLADE matrix (linear)
  Block 4  [6 per triple] of2(ij) of2(jk) of2(ik) triangle triangle_fine omega  (mode-0 type-2)
  Block 5  [4]            xi-frame demo on triple 0 (mode-0): of2(xi) x3 + omega(xi)

Run:  python3 website/scripts/gen-taxa-trace.py   (writes the .yon; gate on the Mac)
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
TAXA = os.path.join(ROOT, "website", "src", "data", "jp-traces", "taxa.json")
OUT_DIR = os.path.join(ROOT, "regression", "book", "jp", "10_taxa_full")

# triples (by taxon NAME) for the omega / triangle viz (on type-2 mode-0 points)
TRIPLES = [
    ("Eoraptor", "Velociraptor", "Gallus"),           # root - maniraptor - bird (xi demo)
    ("Allosaurus", "Velociraptor", "Archaeopteryx"),  # theropod - maniraptor - bird
    ("Velociraptor", "Deinonychus", "Microraptor"),   # close maniraptors
]


def flatten(doc):
    return [(t["name"], t["v"], b["band"]) for b in doc["bands"] for t in b["taxa"]]


def main():
    doc = json.load(open(TAXA))
    taxa = flatten(doc)
    N = len(taxa)
    idx = {name: i for i, (name, _, _) in enumerate(taxa)}
    L = []
    p = lambda expr: L.append(f"  be _{len(L)} holds Output.print(String.from_int({expr}))")

    L.append("place Entry { }")
    L.append("")
    L.append(f"// GENERATED by website/scripts/gen-taxa-trace.py from taxa.json ({N} taxa).")
    L.append("// Do not hand-edit. GRADE = mode-0 orbit; CLADE = linear mode-3 pair_subtype.")
    L.append("// See the script header for the exact output order the harness parses.")
    L.append("")
    L.append("fun main(): number visits Output {")
    # mode-0 (quantized, type-2) embeddings  -- grade orbit + omega/triangle
    for i, (name, v, _) in enumerate(taxa):
        L.append(f"  be e{i} holds Leech.embed({v}, 0)        // {name} (mode 0, type-2)")
    # mode-3 (linear gcode) embeddings  -- clade pair_subtype + type-2 check
    for i, (name, v, _) in enumerate(taxa):
        L.append(f"  be g{i} holds Leech.embed({v}, 3)        // {name} (mode 3, linear)")
    # xi-applied mode-0 embeddings for the frame-change demo (triple 0)
    a, b, c = (idx[n] for n in TRIPLES[0])
    for j in (a, b, c):
        L.append(f"  be x{j} holds Leech.xi_apply(e{j})")
    L.append("")
    # Block 1: GRADE orbit (mode 0)
    for i in range(N):
        p(f"Leech.m24_orbit(e{i})")
    # Block 2: type-2 check under the linear map (mode 3)
    for i in range(N):
        p(f"Leech.m24_orbit(g{i})")
    # Block 3: CLADE matrix, linear pair_subtype upper triangle
    for i in range(N):
        for j in range(i + 1, N):
            p(f"Leech.pair_subtype(g{i}, g{j})")
    # Block 4: triples on type-2 mode-0 points
    for (n1, n2, n3) in TRIPLES:
        i, j, k = idx[n1], idx[n2], idx[n3]
        p(f"XSimplex.of2(e{i}, e{j})")
        p(f"XSimplex.of2(e{j}, e{k})")
        p(f"XSimplex.of2(e{i}, e{k})")
        p(f"XSimplex.triangle(e{i}, e{j}, e{k})")
        p(f"XSimplex.triangle_fine(e{i}, e{j}, e{k})")
        p(f"XSimplex.omega(e{i}, e{j}, e{k})")
    # Block 5: xi-frame demo on triple 0 (mode-0 type-2)
    p(f"XSimplex.of2(x{a}, x{b})")
    p(f"XSimplex.of2(x{b}, x{c})")
    p(f"XSimplex.of2(x{a}, x{c})")
    p(f"XSimplex.omega(x{a}, x{b}, x{c})")
    L.append("  return 0")
    L.append("}")

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "yon.toml"), "w") as f:
        f.write('[package]\nname = "ch05_taxa_full"\n\n[world.Park]\nobjects = ["Dinosaur"]\n\n[runtime]\nbackend = "memory"\n')
    with open(os.path.join(OUT_DIR, "Entry.yon"), "w") as f:
        f.write("\n".join(L) + "\n")
    n_pair = N * (N - 1) // 2
    print(f"wrote {OUT_DIR}/Entry.yon")
    print(f"  {N} taxa, {n_pair} pair_subtype (clade) pairs, {len(TRIPLES)} triples")
    print(f"  expected stdout ints: {N}(grade) + {N}(type2-chk) + {n_pair}(clade) + "
          f"{6*len(TRIPLES)}(triples) + 4(xi) = {N + N + n_pair + 6*len(TRIPLES) + 4}")


if __name__ == "__main__":
    main()
