#!/usr/bin/env python3
"""Generate the alphabetical keyword index in syntax-reference.md from the keyword
reference (22-keywords.md), so the index never drifts out of order or out of sync.

The index is the sorted set of identifier-like `#### `kw`` entries in 22-keywords.md
(every keyword plus the type words Id/Pi/Sigma/Type). Each links to its anchor
(`/book/keywords#<lowercase>`), so every link has a target. The block is delimited by
managed markers; everything outside them is left untouched.

Usage:
  python website/scripts/gen-keyword-index.py            # rewrite the block in place
  python website/scripts/gen-keyword-index.py --check     # exit 1 if out of sync (CI gate)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
KEYWORDS_MD = ROOT / "website" / "docs" / "book" / "22-keywords.md"
SYNREF_MD = ROOT / "website" / "docs" / "syntax-reference.md"

BEGIN = "<!-- BEGIN keyword-index (generated by website/scripts/gen-keyword-index.py) -->"
END = "<!-- END keyword-index -->"
# the prose anchors that bracket the index when the markers are not yet present
INTRO = "[Keywords, one by one](/book/keywords). Every keyword, alphabetically:"
OUTRO = "Each construct carries a status:"


def documented_keywords() -> list[str]:
    """Identifier-like `#### `kw`` entries in 22-keywords.md, sorted case-insensitively."""
    text = KEYWORDS_MD.read_text()
    kws = re.findall(r"^#### `([A-Za-z_][A-Za-z0-9_]*)`", text, re.MULTILINE)
    return sorted(set(kws), key=str.lower)


def render_index(keywords: list[str]) -> str:
    lines = [f"[`{k}`](/book/keywords#{k.lower()}) ·" for k in keywords]
    if lines:
        lines[-1] = lines[-1][:-2]  # drop the trailing " ·" on the last entry
    return "\n".join(lines)


def build_block(keywords: list[str]) -> str:
    return f"{BEGIN}\n\n{render_index(keywords)}\n\n{END}"


def splice(synref: str, block: str) -> str:
    """Insert/replace the managed block, whether or not the markers exist yet."""
    if BEGIN in synref and END in synref:
        return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block,
                      synref, count=1, flags=re.DOTALL)
    # first run: replace the hand-written list between the intro and outro prose
    pat = re.escape(INTRO) + r"\n\n.*?\n\n(?=" + re.escape(OUTRO) + r")"
    repl = INTRO + "\n\n" + block + "\n\n"
    new, n = re.subn(pat, repl, synref, count=1, flags=re.DOTALL)
    if n != 1:
        raise SystemExit("gen-keyword-index: could not locate the index region "
                         f"(intro/outro markers) in {SYNREF_MD}")
    return new


def main() -> int:
    keywords = documented_keywords()
    block = build_block(keywords)
    synref = SYNREF_MD.read_text()
    updated = splice(synref, block)
    check = "--check" in sys.argv[1:]
    if check:
        if updated != synref:
            print("gen-keyword-index: syntax-reference.md keyword index is OUT OF SYNC.\n"
                  "Run: python website/scripts/gen-keyword-index.py", file=sys.stderr)
            return 1
        print(f"keyword index in sync ({len(keywords)} keywords)")
        return 0
    SYNREF_MD.write_text(updated)
    print(f"wrote keyword index ({len(keywords)} keywords) to {SYNREF_MD.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
